/* SQLD DAG viewer.
 * Data:  window.SQLD_DATA  (generated by scripts/build_learning_graph.py into web/data.js)
 * Logic: window.SQLDLogic  (web/logic.js — DOM-free, unit-tested with node:test)
 * Views: 개념 구조 (Concept Structure DAG: Domain → Cluster → Concept)
 *        학습 순서 (Learning DAG: Stage → 학습 블록 → Concept)
 * No external libraries; each Cluster card is a layered DAG drawn with SVG.
 */
(() => {
  'use strict';

  const D = window.SQLD_DATA;
  const L = window.SQLDLogic;
  const canvas = document.getElementById('canvas');
  const inner = document.getElementById('canvas-inner');
  const panelBody = document.getElementById('panel-body');
  const panel = document.getElementById('panel');
  if (!D || !L) {
    inner.innerHTML = '<p style="padding:24px">web/data.js 또는 web/logic.js가 없습니다. <code>python3 scripts/build_learning_graph.py</code>를 먼저 실행하세요.</p>';
    return;
  }

  // ------------------------------------------------------------------ helpers
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const loadJSON = (k, fb) => { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : fb; } catch { return fb; } };
  const saveJSON = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch { /* storage unavailable */ } };

  // ------------------------------------------------------------------ indexes
  const NODES = new Map(D.nodes.map((n) => [n.id, n]));
  const byTopo = (a, b) => NODES.get(a).topo_index - NODES.get(b).topo_index;
  const ids = D.nodes.map((n) => n.id);
  const { pred: PRED, succ: SUCC } = L.adjacency(ids, D.learning_edges, byTopo);
  const { pred: SPRED, succ: SSUCC } = L.adjacency(ids, D.structure_edges, byTopo); // concept→concept only
  const EDGE = new Map(D.learning_edges.map((e) => [e.source + '>' + e.target, e]));
  const SEDGE = new Map(D.structure_edges.map((e) => [e.source + '>' + e.target, e]));
  const STRUCT = new Map(D.structure_nodes.map((x) => [x.id, x]));

  const CLUSTERS = new Map(D.clusters.map((c) => [c.code, c]));
  const DOMAINS = D.domains.slice().sort((a, b) => a.code.localeCompare(b.code));
  const DOMAIN_BY = new Map(DOMAINS.map((d) => [d.code, d]));
  const STAGES = D.stages.slice().sort((a, b) => a.order - b.order);
  const STAGE_BY = new Map(STAGES.map((s) => [String(s.stage), s]));
  const groupBy = (key) => {
    const m = new Map(D.clusters.map((c) => [c.code, []]));
    for (const n of D.nodes) m.get(n[key]).push(n);
    for (const l of m.values()) l.sort((a, b) => a.topo_index - b.topo_index);
    return m;
  };
  const CLUSTER_NODES = { learning: groupBy('cluster'), structure: groupBy('structure_cluster') };

  const META = new Map();
  for (const r of D.metadata_relations) {
    for (const [a, b, dir] of [[r.source, r.target, 'out'], [r.target, r.source, 'in']]) {
      if (!NODES.has(a) || !NODES.has(b)) continue;
      if (!META.has(a)) META.set(a, []);
      META.get(a).push({ rel: r.relation, other: b, dir, reason: r.reason });
    }
  }
  const CONTENT = D.content;
  const RT = D.rules_and_traps;
  const CMP = new Map(D.comparisons.map((c) => [c.id, c]));
  const EX = new Map(D.examples.map((e) => [e.id, e]));
  const DIA = new Map(D.dialects.map((d) => [d.id, d]));
  const SUPP = D.supplementary;
  const SUPP_CMP = new Map(SUPP.comparisons.map((c) => [c.id, c]));
  const SUPP_DIA = new Map(SUPP.dialects.map((d) => [d.id, d]));
  const EVID = D.evidence || {};
  const VAULT = D.vault || {};

  const STATUS = [['not_started', '미학습'], ['studying', '학습 중'], ['learned', '학습 완료'], ['review_needed', '복습 필요']];
  const STATUS_LABEL = Object.fromEntries(STATUS);
  const EVIDENCE_LABEL = {
    current: '현행 출제', legacy_only: '구범위 전용(Legacy)', reference: '참조', structure: '구조 노드(inferred)', integration: '통합 노드(inferred)',
  };
  const REL_LABEL = {
    CONTRASTS: '시험 비교 (CONTRASTS)', AFFECTS: '영향 / 함정 (AFFECTS)', DIALECT: 'DBMS 방언 (DIALECT)',
    DIALECT_OF: 'DBMS 방언 (DIALECT_OF)', DIALECT_EQUIVALENT: '방언 동치 (DIALECT_EQUIVALENT)', EXCEPTION: '예외 / 함정 (EXCEPTION)',
    IS_A: '분류 (IS_A)', IMPLEMENTS: '구현 (IMPLEMENTS)', USES: '사용 (USES)', ENFORCES: '보장 (ENFORCES)',
    REMOVED_BY: '제거 (REMOVED_BY)', RESOLVED_BY: '해소 (RESOLVED_BY)', INCREASES_NEED_FOR: '필요 증가 (INCREASES_NEED_FOR)',
    ALTERNATIVE_TO: '대안 (ALTERNATIVE_TO)', HUB_LINK: '허브 연결 (20_Hubs_Rules)', RELATED_TO: '관련 개념 (curated, 원본 아님)',
    EXECUTION_ORDER: '논리 실행 순서 (DAG 아님)',
  };
  const PROV_LABEL = (p) => (p === '21_Concept_Content.Prerequisites' ? '21 Prerequisites' : p.replace('17_KG_Edges:', '17 '));

  // ------------------------------------------------------------------ state
  const PROGRESS_KEY = 'sqld-learning-dag:progress:v1';
  const PREF_KEY = 'sqld-learning-dag:prefs:v1';
  const prefs = loadJSON(PREF_KEY, {});
  const state = {
    view: prefs.view === 'structure' ? 'structure' : 'learning',
    includeLegacy: !!prefs.includeLegacy,
    highlight: prefs.highlight || 'none',
    filter: { stage: prefs.stageFilter ?? '', domain: prefs.domainFilter ?? '' },
    sectionCollapsed: { learning: new Set(prefs.stageCollapsed || []), structure: new Set(prefs.domainCollapsed || []) },
    clusterMode: { learning: prefs.clusterMode || {}, structure: prefs.sClusterMode || {} },
    revealed: new Set(),
    selected: null,
    path: null, // {target, set:Set}
    tab: 'detail',
    detailTab: 'overview',
    progress: loadJSON(PROGRESS_KEY, {}),
  };
  if (prefs.theme) document.documentElement.dataset.theme = prefs.theme;

  const savePrefs = () => saveJSON(PREF_KEY, {
    view: state.view, includeLegacy: state.includeLegacy, highlight: state.highlight,
    stageFilter: state.filter.stage, domainFilter: state.filter.domain,
    stageCollapsed: [...state.sectionCollapsed.learning], domainCollapsed: [...state.sectionCollapsed.structure],
    clusterMode: state.clusterMode.learning, sClusterMode: state.clusterMode.structure,
    theme: document.documentElement.dataset.theme || '',
  });
  const status = (id) => state.progress[id] || 'not_started';
  const setStatus = (id, st) => {
    if (st === 'not_started') delete state.progress[id]; else state.progress[id] = st;
    saveJSON(PROGRESS_KEY, state.progress);
  };
  const unmet = (id) => L.unmetPrereqs(PRED, id, status);
  const isReady = (id) => status(id) !== 'learned' && unmet(id).length === 0;

  // ------------------------------------------------------------------ view helpers
  const isStructure = () => state.view === 'structure';
  const clusterKey = (n) => (isStructure() ? n.structure_cluster : n.cluster);
  const graphPred = () => (isStructure() ? SPRED : PRED);
  const graphSucc = () => (isStructure() ? SSUCC : SUCC);
  const clusterMode = (code) => state.clusterMode[state.view][code] || 'core';
  const legacyOK = (n) => n.visible_by_default || state.includeLegacy;
  const tierOf = (n) => (n.visible_by_default ? (isStructure() ? n.structure_tier : n.display_tier) : (n.legacy_display_tier || 'detail'));
  const forced = (id) => state.selected === id || state.revealed.has(id) || (state.path && state.path.set.has(id));
  const inFilter = (n) => L.passesFilter(n, state.filter, state.view);
  const isVisible = (n) => L.isVisible(n, {
    includeLegacy: state.includeLegacy, clusterMode: clusterMode(clusterKey(n)), forced: forced(n.id), tier: tierOf(n),
  }) && (forced(n.id) || inFilter(n));

  // ------------------------------------------------------------------ render: canvas
  const layouts = new Map();

  function nodeClasses(n) {
    const c = ['node', 'prio-' + n.priority, 'st-' + status(n.id), 'tier-' + tierOf(n)];
    if (n.support) c.push('support');
    if (n.synthetic) c.push('synthetic', n.synthetic_kind);
    const sel = state.selected;
    if (sel === n.id) c.push('selected');
    if (sel && sel !== n.id) {
      if (graphPred().get(sel).includes(n.id)) c.push('is-prereq');
      else if (graphSucc().get(sel).includes(n.id)) c.push('is-next');
    }
    if (state.path && state.path.set.has(n.id) && sel !== n.id) c.push('path-member');
    const h = state.highlight;
    if (h === 'unlearned' && status(n.id) !== 'not_started') c.push('dim');
    if (h === 'ready') c.push(isReady(n.id) ? 'ready' : 'dim');
    if (h === 'review' && status(n.id) !== 'review_needed') c.push('dim');
    if (state.path && !state.path.set.has(n.id) && h === 'none') c.push('dim');
    return c.join(' ');
  }

  function nodeHTML(n, { compact = false } = {}) {
    const st = status(n.id);
    const miss = unmet(n.id).length;
    const ext = isStructure() ? 0 : PRED.get(n.id).filter((p) => NODES.get(p).cluster !== n.cluster).length;
    const prio = n.priority === 'Legacy' ? 'L' : n.priority;
    const title = [
      n.name, `Priority ${n.priority} · ${EVIDENCE_LABEL[n.evidence_status]}`,
      `현행 ${n.current_rounds}회 / 구범위 ${n.old_rounds}회`, `상태: ${STATUS_LABEL[st]}`,
      miss ? `선수 미완료 ${miss}개` : '선수 Concept 모두 완료',
    ].join('\n');
    return `<div class="${nodeClasses(n)}${compact ? ' compact' : ''}" data-id="${n.id}" role="button" tabindex="0" title="${esc(title)}">`
      + `<button type="button" class="chk" data-act="toggle-learned" aria-label="학습 완료 체크">${st === 'learned' ? '✓' : ''}</button>`
      + `<span class="nm">${esc(n.name)}</span><span class="pr">${prio}</span>`
      + (miss ? `<span class="lock" title="선수 Concept ${miss}개 미완료">선수 ${miss}</span>` : '')
      + (ext ? `<span class="ext" title="다른 Cluster/Stage의 선수 ${ext}개">↑${ext}</span>` : '')
      + '</div>';
  }

  function clusterLayout(code) {
    const vis = CLUSTER_NODES[state.view].get(code).filter(isVisible);
    const inC = (id) => clusterKey(NODES.get(id)) === code;
    const pred = graphPred();
    return L.layeredLayout(vis, (id) => pred.get(id).filter(inC));
  }

  function clusterHTML(code) {
    const c = CLUSTERS.get(code);
    const mode = clusterMode(code);
    const all = CLUSTER_NODES[state.view].get(code);
    const eligible = all.filter((n) => legacyOK(n) && inFilter(n));
    if (!eligible.length && !all.some((n) => forced(n.id))) return '';
    const lay = clusterLayout(code);
    layouts.set(code, lay);
    const hiddenDetail = eligible.filter((n) => !isVisible(n)).length;
    const legacyHidden = state.includeLegacy ? 0 : all.filter((n) => !n.visible_by_default && !forced(n.id) && inFilter(n)).length;
    const learned = eligible.filter((n) => status(n.id) === 'learned').length;
    const wide = lay.count > 8 || lay.layers.some((l) => l.length > 3);
    let moreBtn = '';
    if (mode !== 'collapsed') {
      if (mode === 'all') moreBtn = '<button type="button" class="more" data-act="cluster-core">핵심만</button>';
      else if (hiddenDetail > 0) moreBtn = `<button type="button" class="more" data-act="cluster-all">+${hiddenDetail} 세부</button>`;
    }
    const sub = isStructure() ? `Stage ${c.stage === 'L' ? 'L' : c.stage}` : esc(c.domain_name);
    const body = lay.count
      ? lay.layers.map((row) => `<div class="layer">${row.map((n) => nodeHTML(n)).join('')}</div>`).join('')
      : '<div class="empty-cluster">표시할 Concept 없음</div>';
    return `<article class="cluster ${mode === 'collapsed' ? 'is-collapsed' : ''} ${wide && mode !== 'collapsed' ? 'wide' : ''}" data-cluster="${code}">`
      + `<div class="cluster-head"><button type="button" class="toggle" data-act="cluster-toggle" aria-expanded="${mode !== 'collapsed'}">`
      + `<span class="chev">▾</span><span class="code">${code}</span><span class="cname">${esc(c.name)}</span>`
      + `<span class="count" title="${sub}">${learned}/${eligible.length}</span></button>${moreBtn}</div>`
      + `<div class="cluster-graph"><svg class="edges" aria-hidden="true"></svg>${body}</div>`
      + (legacyHidden ? `<div class="cluster-foot">Legacy ${legacyHidden}개 숨김 · <button type="button" data-act="show-legacy">Include Legacy</button></div>` : '')
      + '</article>';
  }

  function sectionHTML({ key, label, title, subtitle, clusters, legacy, members }) {
    const collapsed = state.sectionCollapsed[state.view].has(key);
    const cards = clusters.map(clusterHTML).join('');
    if (!cards) return '';
    const learned = members.filter((n) => status(n.id) === 'learned').length;
    const pct = members.length ? Math.round((learned / members.length) * 100) : 0;
    return `<section class="stage ${collapsed ? 'collapsed' : ''} ${legacy ? 'legacy-stage' : ''}" data-section="${esc(key)}">`
      + `<button type="button" class="stage-head" data-act="section-toggle" aria-expanded="${!collapsed}">`
      + `<span class="stage-no">${esc(label)}</span><span class="stage-title"><h2>${title}</h2><p>${subtitle}</p></span>`
      + `<span class="stage-meta">${learned}/${members.length} 완료<span class="mini"><i style="width:${pct}%"></i></span></span>`
      + '<span class="chev">▾</span></button>'
      + `<div class="stage-body">${cards}</div></section>`;
  }

  function learningSections() {
    return STAGES.filter((s) => s.stage !== 'L' || state.includeLegacy || D.nodes.some((n) => n.stage === 'L' && forced(n.id)))
      .map((s) => {
        const label = s.stage === 'L' ? 'L' : String(s.stage);
        const prereq = s.stage === 'L' ? 'Stage 9 이후 (선택)' : (s.prereq_stages.length ? '선수: ' + s.prereq_text : '시작 단계');
        return sectionHTML({
          key: String(s.stage), label, legacy: s.stage === 'L', clusters: s.clusters,
          title: `Stage ${label} · ${esc(s.title)}`, subtitle: `${esc(s.goal)} · ${esc(prereq)}`,
          members: D.nodes.filter((n) => String(n.stage) === String(s.stage) && legacyOK(n) && inFilter(n)),
        });
      });
  }

  function structureSections() {
    return DOMAINS.filter((d) => d.code !== 'D7' || state.includeLegacy || D.nodes.some((n) => n.structure_domain === 'D7' && forced(n.id)))
      .map((d) => sectionHTML({
        key: d.code, label: d.code, legacy: d.code === 'D7', clusters: d.clusters,
        title: `${esc(d.name)} <span class="subj">${esc(d.subject || '')}</span>`,
        subtitle: `SQLD › ${esc(d.name)} · ${esc(d.memo || '')} · Cluster ${d.clusters.length}`,
        members: D.nodes.filter((n) => n.structure_domain === d.code && legacyOK(n) && inFilter(n)),
      }));
  }

  const ARROW = '<div class="stage-arrow" aria-hidden="true"><svg width="16" height="22" viewBox="0 0 16 22"><path d="M8 0v18M2 13l6 7 6-7" fill="none" stroke="currentColor" stroke-width="1.6"/></svg></div>';

  function render() {
    const top = canvas.scrollTop;
    layouts.clear();
    const sections = (isStructure() ? structureSections() : learningSections()).filter(Boolean);
    const head = isStructure()
      ? '<p class="view-hint">개념 구조 — "이 개념은 SQLD 체계에서 어디에 속하는가?" (SQLD › Domain › Cluster › Concept, 선 = BELONGS_TO / IS_A)</p>'
      : '<p class="view-hint">학습 순서 — "이 개념 전에 무엇을 알아야 하는가?" (Stage › 학습 블록 › Concept, 화살표 = 선수 → 다음)</p>';
    inner.innerHTML = head + (sections.join(isStructure() ? '<div class="section-gap"></div>' : ARROW)
      || '<p class="empty-cluster">필터에 맞는 Concept이 없습니다.</p>') + '<svg class="overlay" id="overlay" aria-hidden="true"></svg>';
    canvas.scrollTop = top;
    requestAnimationFrame(drawEdges);
    renderProgress();
    syncControls();
  }

  // ------------------------------------------------------------------ edges
  function center(el, base) {
    const r = el.getBoundingClientRect();
    return { x: r.left - base.left + r.width / 2, top: r.top - base.top, bottom: r.bottom - base.top };
  }
  function curve(a, b) {
    const y1 = a.bottom; const y2 = b.top;
    const dy = Math.max(14, (y2 - y1) / 2);
    return `M${a.x},${y1} C${a.x},${y1 + dy} ${b.x},${y2 - dy} ${b.x},${y2 - 3}`;
  }
  function drawLinks(container, links, { sel = state.selected, path = state.path } = {}) {
    const svg = container.querySelector(':scope > svg.edges');
    const base = container.getBoundingClientRect();
    let out = '';
    for (const l of links) {
      const se = container.querySelector(`.node[data-id="${l.s}"]`);
      const te = container.querySelector(`.node[data-id="${l.t}"]`);
      if (!se || !te) continue;
      const a = center(se, base); const b = center(te, base);
      if (b.top <= a.bottom) continue;
      let cls = 'e' + (l.direct === false ? ' indirect' : '') + (l.inferred ? ' inferred' : '');
      if (sel && l.t === sel) cls += ' hi-in';
      else if (sel && l.s === sel) cls += ' hi-out';
      else if (path && path.set.has(l.s) && path.set.has(l.t)) cls += ' path';
      else if (state.highlight !== 'none' || path) cls += ' dim';
      out += `<path class="${cls}" d="${curve(a, b)}"/>`;
      out += `<circle class="ah ${cls.includes('hi-in') ? 'hi-in' : cls.includes('hi-out') ? 'hi-out' : ''}" cx="${b.x}" cy="${b.top - 2}" r="2.4"/>`;
    }
    svg.innerHTML = out;
  }
  function drawEdges() {
    const edgeMap = isStructure() ? SEDGE : EDGE;
    for (const card of inner.querySelectorAll('.cluster:not(.is-collapsed)')) {
      const lay = layouts.get(card.dataset.cluster);
      if (!lay) continue;
      const links = lay.links.map((l) => ({ ...l, inferred: l.direct && !!edgeMap.get(l.s + '>' + l.t)?.inferred }));
      drawLinks(card.querySelector('.cluster-graph'), links);
    }
    drawOverlay();
    const mini = panelBody.querySelector('.minidag');
    if (mini && mini._links) drawLinks(mini, mini._links, { sel: state.selected, path: null });
  }
  function drawOverlay() {
    const svg = document.getElementById('overlay');
    if (!svg) return;
    svg.setAttribute('width', inner.scrollWidth);
    svg.setAttribute('height', inner.scrollHeight);
    const sel = state.selected;
    const me = sel && inner.querySelector(`.node[data-id="${sel}"]`);
    if (!me) { svg.innerHTML = ''; return; }
    const base = inner.getBoundingClientRect();
    const m = center(me, base);
    const myCluster = clusterKey(NODES.get(sel));
    let out = '';
    const line = (a, b, cls) => {
      const dy = Math.max(30, Math.abs(b.top - a.bottom) / 2);
      const d = b.top > a.bottom ? `M${a.x},${a.bottom} C${a.x},${a.bottom + dy} ${b.x},${b.top - dy} ${b.x},${b.top}`
        : `M${a.x},${a.top} C${a.x - 60},${a.top - dy} ${b.x + 60},${b.bottom + dy} ${b.x},${b.bottom}`;
      out += `<path class="xe ${cls}" d="${d}"/>`;
    };
    for (const p of graphPred().get(sel)) {
      if (clusterKey(NODES.get(p)) === myCluster) continue;
      const el = inner.querySelector(`.node[data-id="${p}"]`);
      if (el) line(center(el, base), m, 'in');
    }
    for (const s of graphSucc().get(sel)) {
      if (clusterKey(NODES.get(s)) === myCluster) continue;
      const el = inner.querySelector(`.node[data-id="${s}"]`);
      if (el) line(m, center(el, base), 'out');
    }
    svg.innerHTML = out;
  }

  // ------------------------------------------------------------------ header
  function renderProgress() {
    const vis = D.nodes.filter(legacyOK);
    const cur = D.nodes.filter((n) => n.evidence_status === 'current');
    const learned = vis.filter((n) => status(n.id) === 'learned').length;
    const curLearned = cur.filter((n) => status(n.id) === 'learned').length;
    const aNodes = D.nodes.filter((n) => n.priority === 'A');
    const aLearned = aNodes.filter((n) => status(n.id) === 'learned').length;
    const studying = vis.filter((n) => status(n.id) === 'studying').length;
    const review = vis.filter((n) => status(n.id) === 'review_needed').length;
    const ready = vis.filter((n) => isReady(n.id)).length;
    const pct = vis.length ? Math.round((learned / vis.length) * 100) : 0;
    document.getElementById('progress').innerHTML =
      `<span>학습 완료 <b>${learned}</b> / ${vis.length}</span><span class="bar"><i style="width:${pct}%"></i></span>`
      + `<span>현행 Concept <b>${curLearned}</b>/${cur.length}</span>`
      + `<span>Priority A <b>${aLearned}</b>/${aNodes.length}</span>`
      + `<span>학습 중 <b>${studying}</b></span><span>복습 필요 <b>${review}</b></span>`
      + `<span>지금 공부 가능 <b>${ready}</b></span>`
      + `<span>${state.includeLegacy ? 'Legacy 포함' : `Legacy ${D.nodes.filter((n) => !n.visible_by_default).length}개 숨김`}</span>`;
    const sm = D.summary;
    document.getElementById('sub').textContent =
      `Concept ${sm['Total source concepts']} · 현행 ${sm['Current concepts']} · 구조 DAG ${sm['Structure Is DAG'] ? '✓' : '✗'} · 학습 DAG ${sm['Learning Is DAG'] ? '✓' : '✗'} (선수 edge ${sm['Explicit learning edges']} + inferred ${sm['Inferred learning edges']})`;
  }
  function syncControls() {
    for (const b of document.querySelectorAll('[data-view]')) b.classList.toggle('on', b.dataset.view === state.view);
    for (const b of document.querySelectorAll('[data-scope]')) b.classList.toggle('on', (b.dataset.scope === 'legacy') === state.includeLegacy);
    document.getElementById('f-stage').value = state.filter.stage;
    document.getElementById('f-domain').value = state.filter.domain;
    document.getElementById('btn-fold').textContent = isStructure() ? 'Domain 접기' : 'Stage 접기';
  }

  // ------------------------------------------------------------------ panel: shared bits
  const nm = (id) => esc(NODES.get(id).name);
  const chip = (id, extra = '') => {
    const n = NODES.get(id);
    return `<button type="button" class="chip ${n.visible_by_default ? '' : 'legacy'}" data-goto="${id}" title="${n.visible_by_default ? '' : 'Legacy — 기본 화면 숨김'}">${nm(id)}${n.visible_by_default ? '' : ' ·L'}${extra}</button>`;
  };
  const conceptBtn = (id, extra = '') => `<button type="button" class="cbtn" data-goto="${id}">${nm(id)}</button>${extra}`;
  const srcTag = (txt) => `<span class="src" title="원본 시트">${esc(txt)}</span>`;
  const empty = (txt) => `<p class="empty">${esc(txt)}</p>`;

  function supplementaryBlock(title, html) {
    if (!html) return '';
    return `<details class="supp"><summary>${esc(title)} <span class="supp-label">${esc(SUPP.label)}</span></summary>${html}</details>`;
  }

  function edgeLine(src, dst, viewpoint) {
    const e = EDGE.get(src + '>' + dst);
    const other = viewpoint === 'pre' ? src : dst;
    const o = NODES.get(other);
    const tag = e.inferred
      ? `<span class="tag inf" title="curated inferred prerequisite">inferred · ${esc(e.confidence)}</span>`
      : e.provenance.map((p) => `<span class="tag exp" title="${esc(p)}">${esc(PROV_LABEL(p))}</span>`).join('');
    const mine = NODES.get(viewpoint === 'pre' ? dst : src);
    const extra = o.cluster !== mine.cluster ? `<span class="tag">${esc(o.cluster)} · S${o.stage}</span>` : '';
    const leg = o.visible_by_default ? '' : '<span class="tag">Legacy</span>';
    return `<li><span class="sdot st-${status(other)}" title="${STATUS_LABEL[status(other)]}"></span><span>`
      + conceptBtn(other, tag + extra + leg) + `<span class="why-edge">${esc(e.reason)}</span></span></li>`;
  }

  function evidenceHTML(n) {
    const rows = EVID[n.id] || [];
    const table = (rs) => (rs.length ? `<details><summary>회차별 근거 ${rs.length}건 (03_Round_Concepts)</summary><table>${rs.map((r) => `<tr><td>${r.year} · ${r.round}회</td><td>${esc(r.strength)}</td><td>${r.url ? `<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.url.replace(/^https?:\/\//, '').slice(0, 48))}</a>` : ''}${r.memo ? `<div class="exp-note">${esc(r.memo)}</div>` : ''}</td></tr>`).join('')}</table></details>` : '');
    const ce = n.current_evidence; const le = n.legacy_evidence;
    let h = `<h3>Current Exam Evidence <span class="n">52회 이후 · 10_Current_Evidence</span></h3><div class="evi">`;
    if (ce) {
      h += `<div class="rounds">${ce.rounds.map((r) => `<span class="rd cur">${r}회</span>`).join('')}</div>`
        + `<div class="exp-note">현행 ${n.current_rounds}회 · 증거강도 ${esc(ce.strength)} · ${esc(ce.interpretation)}${ce.source ? ` · <a href="${esc(ce.source)}" target="_blank" rel="noopener">대표 출처</a>` : ''}</div>`
        + table(rows.filter((r) => r.round >= 52));
    } else h += empty('52회 이후 현행 출제 증거 없음');
    h += `</div><h3>Legacy Exam Evidence <span class="n">51회 이전 · 11_Legacy_Only</span></h3><div class="evi">`;
    if (n.old_round_list.length) {
      h += `<div class="rounds">${n.old_round_list.map((r) => `<span class="rd">${r}회</span>`).join('')}</div>`
        + (le ? `<div class="exp-note">구범위 ${n.old_rounds}회 · ${esc(le.scope)} · ${esc(le.interpretation)}</div>` : '')
        + table(rows.filter((r) => r.round < 52));
    } else h += empty('구범위 출제 증거 없음');
    return h + '</div>';
  }

  // ------------------------------------------------------------------ panel: detail tabs
  function overviewHTML(n, c) {
    const s = STAGE_BY.get(String(n.stage));
    const scl = CLUSTERS.get(n.structure_cluster);
    const sdom = DOMAIN_BY.get(n.structure_domain);
    const parents = n.structure_parents.filter((p) => NODES.has(p));
    let h = `<h3>Definition ${srcTag(c.source === '21_Concept_Content' ? '21_Concept_Content' : '원본 행 없음 — inferred 노드')}</h3>`
      + `<p class="def">${esc(c.definition) || '<span class="empty">정의 없음</span>'}</p>`;
    if (c.why_it_matters) h += `<h3>Why It Matters ${srcTag('21_Concept_Content')}</h3><p class="why">${esc(c.why_it_matters)}</p>`;
    for (const hub of c.hubs || []) h += `<div class="note"><b>${esc(hub.hub)}</b> 허브 (${esc(hub.role)}) ${srcTag('20_Hubs_Rules')}<br>${esc(hub.core_rule)}<br><span class="exp-note">${esc(hub.study_note)}</span></div>`;
    h += '<h3>위치</h3><dl class="facts">'
      + `<dt>개념 구조</dt><dd>SQLD › ${esc(sdom.name)} › ${esc(scl.code)} ${esc(scl.name)}${parents.length ? ' › ' + parents.map((p) => conceptBtn(p)).join(', ') : ''}</dd>`
      + `<dt>학습 순서</dt><dd>Stage ${n.stage === 'L' ? 'L' : n.stage} ${esc(s.title)} › ${esc(n.cluster)} ${esc(n.cluster_name)}</dd>`
      + `<dt>Domain</dt><dd>${esc(n.domain_name)} (${esc(n.official_subject || '')})</dd>`
      + `<dt>Current / Legacy</dt><dd>${EVIDENCE_LABEL[n.evidence_status]}${n.support ? ' · 현행 Concept의 선수라 기본 화면 표시' : ''}</dd>`
      + `<dt>현행 출제 회차수</dt><dd>${n.current_rounds}회${n.current_round_list.length ? ` (${n.current_round_list.join(', ')}회)` : ''} · 구범위 ${n.old_rounds}회</dd>`
      + `<dt>마인드맵</dt><dd>${esc(n.mindmap_status || '-')}${n.mindmap_gap ? ` · gap: ${esc(n.mindmap_gap_action)}` : ''}</dd>`
      + `<dt>콘텐츠</dt><dd>${esc(c.content_depth || '-')}${c.review_flag ? ` · ${esc(c.review_flag)}` : ''}</dd>`
      + '</dl>';
    if (n.placement_override) {
      const p = n.placement_override;
      h += `<div class="note">학습 화면 배치 조정(inferred): 원본 ${esc(p.from_cluster)}(Stage ${p.from_stage}) → ${esc(p.to_cluster)}(Stage ${p.to_stage}). ${esc(p.reason)}<br><span class="exp-note">개념 구조 화면은 원본 Cluster를 그대로 사용합니다.</span></div>`;
    }
    if (n.structure_children.length) {
      h += `<h3>하위 Concept <span class="n">${n.structure_children.length} · 개념 구조(BELONGS_TO / IS_A)</span></h3><div class="chips">`
        + n.structure_children.map((x) => chip(x)).join('') + '</div>';
    }
    const v = VAULT[n.id];
    if (v) {
      h += '<h3>Obsidian 노트 <span class="n">이 저장소의 기존 노트(읽기 전용)</span></h3><ul class="rules">'
        + (v.note ? `<li>Concept 노트: <code>${esc(v.note)}</code></li>` : '')
        + (v.questions.length ? `<li>이 Concept을 링크하는 모의고사 문항 ${v.questions.length}개 — Exam 탭에서 확인</li>` : '') + '</ul>';
    }
    if (c.source_memo) h += `<p class="exp-note">Source / Memo: ${esc(c.source_memo)}</p>`;
    const supp = SUPP.notes[n.id];
    if (supp && (supp.why || (c.source !== '21_Concept_Content' && supp.definition))) {
      h += supplementaryBlock('보조 설명', `${supp.definition && c.source === '21_Concept_Content' ? `<p>${esc(supp.definition)}</p>` : ''}${supp.why ? `<p class="why">${esc(supp.why)}</p>` : ''}`);
    }
    return h;
  }

  function learnHTML(n, c) {
    const preds = PRED.get(n.id);
    const nexts = SUCC.get(n.id);
    const ctx = c.prerequisites_context;
    let h = `<h3>Prerequisites <span class="n">${preds.length} · 학습 DAG</span></h3>`
      + (preds.length ? `<ul class="plain clist">${preds.map((p) => edgeLine(p, n.id, 'pre')).join('')}</ul>` : empty(`선수 Concept 없음 — ${n.cluster_name} 학습 블록의 시작점(root-level)`));
    if (ctx && ctx.raw) {
      const blocks = [...ctx.clusters.map((x) => `${x} ${CLUSTERS.get(x).name}`), ...ctx.domains.map((x) => DOMAIN_BY.get(x).name)];
      h += `<p class="exp-note">원본 Prerequisites ${srcTag('21_Concept_Content')}: ${esc(ctx.raw)}${blocks.length ? ` <br>→ 학습 블록(Concept edge 아님): ${esc(blocks.join(', '))}` : ''}</p>`;
    }
    h += `<h3>Next concepts <span class="n">${nexts.length}</span></h3>`
      + (nexts.length ? `<ul class="plain clist">${nexts.map((x) => edgeLine(n.id, x, 'next')).join('')}</ul>` : empty('이 Concept을 선수로 하는 Concept 없음'));
    h += `<h3>Core Rule ${srcTag('21_Concept_Content')}</h3>` + (c.core_rule ? `<p class="core">${esc(c.core_rule)}</p>` : empty('원본에 Core Rule 없음'));
    if (c.syntax) h += `<h3>Syntax / Pattern ${srcTag('21_Concept_Content')}</h3><pre class="ex"><code>${esc(c.syntax)}</code></pre>`;
    const rs = (c.rules || []).map((id) => RT[id]);
    h += `<h3>Rules <span class="n">${rs.length}</span> ${srcTag('22_Rules_And_Traps')}</h3>`
      + (rs.length ? `<ul class="plain rlist">${rs.map((r) => `<li><span class="rtype">${esc(r.type)}</span> ${esc(r.rule)}${r.why ? `<span class="why-edge">${esc(r.why)}</span>` : ''}${r.example ? `<pre class="ex"><code>${esc(r.example)}</code></pre>` : ''}</li>`).join('')}</ul>` : empty('규칙 행 없음'));
    if (c.execution_order) {
      h += '<div class="note"><b>DAG에서 제외한 실행 순서 관계</b><ul class="rules">'
        + c.execution_order.map((x) => `<li><code>${esc(x.edge)}</code> — ${esc(x.note)}</li>`).join('') + '</ul></div>';
    }
    const supp = SUPP.notes[n.id];
    if (supp && supp.core_rule.length) h += supplementaryBlock('보조 규칙', `<ul class="rules">${supp.core_rule.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>`);
    return h;
  }

  function comparisonHTML(cmp, selfId) {
    const side = (x) => (x === selfId ? ' class="me"' : '');
    return `<div class="cmp"><h4>${esc(cmp.a_name)} vs ${esc(cmp.b_name)} <span class="n">${esc(cmp.id)} · ${esc(cmp.axis)}</span></h4><div class="tw"><table>`
      + `<thead><tr><th></th><th${side(cmp.a)}>${conceptBtn(cmp.a)}</th><th${side(cmp.b)}>${conceptBtn(cmp.b)}</th></tr></thead><tbody>`
      + `<tr><td>규칙</td><td${side(cmp.a)}>${esc(cmp.a_rule)}</td><td${side(cmp.b)}>${esc(cmp.b_rule)}</td></tr>`
      + `<tr><td>예</td><td colspan="2">${esc(cmp.example)}</td></tr></tbody></table></div>`
      + `<div class="take">시험 포인트: ${esc(cmp.exam_focus)}</div></div>`;
  }
  function suppCmpHTML(c, selfId) {
    const selfName = NODES.get(selfId).name;
    return `<div class="cmp"><h4>${esc(c.title)}</h4><div class="tw"><table><thead><tr>${c.headers.map((x) => `<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>`
      + c.rows.map((r) => `<tr class="${r[0] === selfName ? 'me' : ''}">${r.map((v) => `<td>${esc(v)}</td>`).join('')}</tr>`).join('')
      + `</tbody></table></div><div class="take">${esc(c.takeaway)}</div></div>`;
  }

  function examHTML(n, c) {
    const traps = (c.traps || []).map((id) => RT[id]);
    const extra = c.exam_trap && !traps.some((t) => t.rule === c.exam_trap) ? [c.exam_trap] : [];
    let h = `<h3>Exam Traps <span class="n">${traps.length + extra.length}</span> ${srcTag('22_Rules_And_Traps · 21 Exam Trap')}</h3>`;
    h += traps.length || extra.length
      ? `<ul class="traps">${traps.map((t) => `<li>${esc(t.rule)}${t.why ? `<span class="why-edge">${esc(t.why)}</span>` : ''}</li>`).join('')}${extra.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>`
      : empty('원본에 시험 함정 행 없음');
    const cmps = (c.comparisons || []).map((id) => CMP.get(id));
    h += `<h3>Comparison Cards <span class="n">${cmps.length}</span> ${srcTag('23_Comparisons')}</h3>`
      + (cmps.length ? cmps.map((x) => comparisonHTML(x, n.id)).join('') : empty('비교 카드 없음'));
    const targets = (c.comparison_targets || []).filter((x) => !cmps.some((k) => k.a === x || k.b === x));
    if (targets.length) h += `<p class="exp-note">Comparison Targets ${srcTag('21_Concept_Content')}: </p><div class="chips">${targets.map((x) => chip(x)).join('')}</div>`;
    const v = VAULT[n.id];
    if (v && v.questions.length) {
      h += `<h3>모의고사 문항 <span class="n">${v.questions.length} · Obsidian Questions/</span></h3><ul class="rules">`
        + v.questions.map((q) => `<li><code>${esc(q.id)}</code> ${esc(q.title.replace(/^[^—]*—\s*/, ''))}</li>`).join('') + '</ul>';
    }
    h += evidenceHTML(n);
    h += `<h3>관련 개념 · 영향 · 함정 <span class="n">DAG edge 아님</span></h3>${relationsHTML(n.id)}`;
    const supp = SUPP.notes[n.id];
    if (supp) {
      const sh = (supp.exam_traps.length ? `<ul class="traps soft">${supp.exam_traps.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : '')
        + supp.comparisons.map((id) => suppCmpHTML(SUPP_CMP.get(id), n.id)).join('');
      h += supplementaryBlock('보조 함정·비교표', sh);
    }
    return h;
  }

  function relationsHTML(id) {
    const list = META.get(id) || [];
    if (!list.length) return empty('없음');
    const groups = new Map();
    for (const r of list) {
      if (!groups.has(r.rel)) groups.set(r.rel, []);
      if (!groups.get(r.rel).some((x) => x.other === r.other)) groups.get(r.rel).push(r);
    }
    let h = '';
    for (const [rel, items] of groups) {
      h += `<div class="rel-group"><div class="rt">${esc(REL_LABEL[rel] || rel)}</div><div class="chips">`
        + items.map((r) => `<button type="button" class="chip ${NODES.get(r.other).visible_by_default ? '' : 'legacy'}" data-goto="${r.other}" title="${esc((r.dir === 'out' ? '→ ' : '← ') + (r.reason || ''))}">${r.dir === 'in' ? '← ' : ''}${nm(r.other)}</button>`).join('')
        + '</div></div>';
    }
    return h;
  }

  function sqlHTML(n, c) {
    const exs = (c.examples || []).map((id) => EX.get(id));
    let h = `<h3>SQL Examples <span class="n">${exs.length}</span> ${srcTag('24_SQL_Examples')}</h3>`;
    if (!exs.length) h += empty('이 Concept의 원본 예제 없음');
    for (const type of ['RESULT', 'SYNTAX']) {
      const group = exs.filter((e) => e.type === type);
      if (!group.length) continue;
      h += `<h4 class="exhead">${type === 'RESULT' ? 'RESULT — 결과 판별' : 'SYNTAX — 문법 형태'}</h4>`;
      for (const e of group) {
        h += `<div class="example"><div class="exmeta"><span class="rtype">${esc(e.type)}</span> ${esc(e.id)}${e.dbms ? ` · ${esc(e.dbms)}` : ''} · ${esc(e.purpose)}</div>`
          + `<pre class="ex"><code>${esc(e.sql)}</code></pre>`
          + (e.expected_result ? `<div class="expected"><b>Expected Result</b> ${esc(e.expected_result)}</div>` : '') + '</div>';
      }
    }
    if (c.syntax && !exs.some((e) => e.sql === c.syntax)) h += `<h4 class="exhead">Syntax / Pattern ${srcTag('21_Concept_Content')}</h4><pre class="ex"><code>${esc(c.syntax)}</code></pre>`;
    const supp = SUPP.notes[n.id];
    if (supp && supp.examples.length) {
      h += supplementaryBlock('보조 예제', supp.examples.map((x) => `<pre class="ex"><code>${esc(x.sql)}</code></pre><p class="exp-note">${esc(x.explain)}</p>`).join(''));
    }
    return h;
  }

  function dbmsHTML(n, c) {
    const notes = (c.dialects || []).map((id) => DIA.get(id));
    const drules = (c.rules || []).map((id) => RT[id]).filter((r) => r.type === 'DIALECT_RULE');
    let h = `<h3>DBMS / Standard Notes <span class="n">${notes.length}</span> ${srcTag('25_Dialect_Notes')}</h3>`;
    h += notes.length
      ? `<div class="cmp"><div class="tw"><table><thead><tr><th>DBMS</th><th>Behavior</th><th>Exam Note</th></tr></thead><tbody>${notes.map((d) => `<tr><td>${esc(d.dbms)}</td><td>${esc(d.behavior)}${d.concept_name !== n.name ? ` <span class="tag">${esc(d.concept_name)}</span>` : ''}</td><td>${esc(d.exam_note)}</td></tr>`).join('')}</tbody></table></div></div>`
      : empty('이 Concept의 원본 DBMS 노트 없음');
    if (drules.length) h += `<h3>Dialect Rules ${srcTag('22_Rules_And_Traps')}</h3><ul class="rules">${drules.map((r) => `<li>${esc(r.rule)}${r.dbms ? ` (${esc(r.dbms)})` : ''}</li>`).join('')}</ul>`;
    if ((c.dialect_targets || []).length) h += `<p class="exp-note">Dialect Notes 대상 ${srcTag('21_Concept_Content')}:</p><div class="chips">${c.dialect_targets.map((x) => chip(x)).join('')}</div>`;
    const dl = (META.get(n.id) || []).filter((r) => r.rel.startsWith('DIALECT'));
    if (dl.length) h += `<p class="exp-note">17_KG_Edges 방언 관계:</p><div class="chips">${dl.map((r) => chip(r.other)).join('')}</div>`;
    const supp = SUPP.notes[n.id];
    if (supp && (supp.dialects.length || supp.dialect_notes.length)) {
      const t = supp.dialects.map((id) => SUPP_DIA.get(id));
      h += supplementaryBlock('보조 ANSI / Oracle / SQL Server 비교표',
        (t.length ? `<div class="cmp"><div class="tw"><table><thead><tr><th>주제</th><th>ANSI</th><th>Oracle</th><th>SQL Server</th></tr></thead><tbody>${t.map((d) => `<tr><td>${esc(d.topic)}</td><td>${esc(d.ansi)}</td><td>${esc(d.oracle)}</td><td>${esc(d.sqlserver)}</td></tr>`).join('')}</tbody></table></div></div>` : '')
        + (supp.dialect_notes.length ? `<ul class="rules">${supp.dialect_notes.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : ''));
    }
    return h;
  }

  const DETAIL_TABS = [['overview', 'Overview'], ['learn', 'Learn'], ['exam', 'Exam'], ['sql', 'SQL'], ['dbms', 'DBMS']];
  function tabCounts(n, c) {
    const traps = (c.traps || []).length + (c.exam_trap && !(c.traps || []).some((t) => RT[t].rule === c.exam_trap) ? 1 : 0);
    return {
      learn: PRED.get(n.id).length + (c.rules || []).length + (c.core_rule ? 1 : 0),
      exam: traps + (c.comparisons || []).length,
      sql: (c.examples || []).length,
      dbms: (c.dialects || []).length,
    };
  }

  function renderDetail() {
    const id = state.selected;
    if (!id) { panelBody.innerHTML = introHTML(); return; }
    const n = NODES.get(id);
    const c = CONTENT[id];
    const st = status(id);
    const miss = unmet(id);
    let h = `<h2>${esc(n.name)}</h2><div class="badges">`
      + `<span class="badge prio-${n.priority}" title="${esc((n.priority_reasons || []).join('\n'))}">Priority ${n.priority}</span>`
      + `<span class="badge ${n.evidence_status === 'current' ? 'cur' : ''}">${EVIDENCE_LABEL[n.evidence_status]}</span>`
      + `<span class="badge">${esc(n.node_type)}</span><span class="badge">현행 ${n.current_rounds}회 · 구범위 ${n.old_rounds}회</span>`
      + (n.mindmap_gap ? `<span class="badge gap" title="13_Current_Mindmap_Gaps">마인드맵 gap</span>` : '')
      + (c.content_depth ? `<span class="badge depth" title="21_Concept_Content Content Depth">${esc(c.content_depth)}</span>` : '')
      + (c.review_flag === '우선검토' ? '<span class="badge review" title="21_Concept_Content Review Flag">우선검토</span>' : '')
      + (!n.visible_by_default ? '<span class="badge prio-Legacy">기본 화면 숨김</span>' : '') + '</div>'
      + `<div class="exp-note">${esc((n.priority_reasons || []).join(' · '))}</div>`;
    if (n.synthetic) h += `<div class="note">원본 시트에 없는 <b>inferred ${n.synthetic_kind === 'integration' ? '통합(Stage 9)' : '구조'} 노드</b> (confidence ${esc(n.confidence)}). 근거: ${esc(n.synthetic_basis)}</div>`;
    h += '<div class="statusbar" role="group" aria-label="학습 상태">'
      + STATUS.map(([k, lbl]) => `<button type="button" data-st="${k}" class="${st === k ? 'on' : ''}">${lbl}</button>`).join('') + '</div>';
    if (miss.length) h += `<div class="note warn">선수 Concept <b>${miss.length}개</b>가 아직 '학습 완료'가 아닙니다: ${miss.map((x) => chip(x)).join(' ')}</div>`;
    else if (PRED.get(id).length) h += '<div class="note ok">선수 Concept을 모두 학습했습니다. 지금 공부하기 좋은 순서입니다.</div>';
    h += '<p><button type="button" class="pbtn solid" data-act="path-to">이 Concept까지 학습 경로</button></p>';
    const counts = tabCounts(n, c);
    h += `<div class="subtabs" role="tablist">${DETAIL_TABS.map(([k, lbl]) => `<button type="button" role="tab" data-dtab="${k}" class="${state.detailTab === k ? 'on' : ''}">${lbl}${counts[k] ? `<span class="cnt">${counts[k]}</span>` : ''}</button>`).join('')}</div>`;
    const body = { overview: overviewHTML, learn: learnHTML, exam: examHTML, sql: sqlHTML, dbms: dbmsHTML }[state.detailTab](n, c);
    panelBody.innerHTML = h + `<div class="subtab-body">${body}</div>`;
  }

  function introHTML() {
    const flow = STAGES.filter((s) => s.stage !== 'L').map((s) => `<b>${esc(s.title)}</b>`).join(' → ');
    const ready = D.nodes.filter((n) => n.visible_by_default && isReady(n.id) && n.priority === 'A').slice(0, 12);
    const sm = D.summary;
    return `<h2>SQLD 개념 구조 · 학습 순서</h2>
      <ul class="rules">
        <li><b>개념 구조</b>: SQLD 지식이 어떻게 구성되어 있는가 (Domain › Cluster › Concept)</li>
        <li><b>학습 순서</b>: 무엇을 먼저 배우고 다음에 무엇을 배우는가 (선수 → 다음)</li>
        <li><b>Concept 상세</b>: 시험에서 이 개념으로 무엇을 알아야 하는가 (Overview · Learn · Exam · SQL · DBMS)</li>
      </ul>
      <h3>기본 학습 경로</h3><p class="flowline">${flow}</p>
      <h3>지금 공부할 수 있는 Priority A</h3><div class="chips">${ready.map((n) => chip(n.id)).join('') || '<span class="empty">없음</span>'}</div>
      <h3>읽는 법</h3><ul class="rules">
        <li>실선: 원본 관계, 가는 점선: 숨겨진 세부 Concept을 거친 관계, 회색 긴 점선: inferred edge</li>
        <li><span class="lock-demo">선수 2</span> 아직 학습 완료하지 않은 선수 Concept 수, <span class="ext-demo">↑2</span> 다른 학습 블록의 선수 수</li>
        <li>비교(RANK vs DENSE_RANK 등)·DBMS 차이·함정은 화살표가 아니라 상세 패널의 카드</li>
        <li>Legacy(52회 이후 현행 증거 없음)는 기본 숨김. 현행 Concept의 선수인 구범위 Concept만 Priority C 보조 노드로 표시</li>
      </ul>
      <h3>데이터 (${esc(D.meta.source_file)})</h3><p class="exp-note">Concept ${sm['Total source concepts']} (현행 ${sm['Current concepts']}, Legacy-only ${sm['Legacy-only concepts']}) · CURATED ${sm['CURATED content']} / TEMPLATE ${sm['TEMPLATE content']} ·
      구조 DAG 노드 ${sm['Concept Structure DAG nodes']} · 학습 DAG 노드 ${sm['Learning DAG nodes']} · 선수 edge ${sm['Explicit learning edges']} + inferred ${sm['Inferred learning edges']}</p>`;
  }

  // ------------------------------------------------------------------ panel: path
  function masterySet(id) {
    const n = NODES.get(id); const out = new Set(); const st = [...SUCC.get(id)];
    while (st.length) {
      const x = st.pop();
      if (out.has(x)) continue;
      const xn = NODES.get(x);
      if (xn.cluster !== n.cluster || !legacyOK(xn)) continue;
      out.add(x); st.push(...SUCC.get(x));
    }
    for (const c of n.structure_children) if (legacyOK(NODES.get(c))) out.add(c);
    return out;
  }
  function pathRow(id, cls = '') {
    const n = NODES.get(id);
    return `<li class="${cls}"><input type="checkbox" data-learn="${id}" ${status(id) === 'learned' ? 'checked' : ''} aria-label="학습 완료">`
      + `<button type="button" class="nm" data-goto="${id}">${esc(n.name)}</button>`
      + `<span class="badge prio-${n.priority}">${n.priority === 'Legacy' ? 'L' : n.priority}</span>`
      + `<span class="stg">S${n.stage} · ${esc(n.cluster)}</span></li>`;
  }
  function renderPath() {
    let h = '';
    const id = state.selected;
    let mini = null;
    if (id) {
      const n = NODES.get(id);
      const sub = L.prerequisiteSubgraph(PRED, id);
      const anc = [...sub.nodes].filter((x) => x !== id).sort(byTopo);
      const mast = [...masterySet(id)].sort(byTopo);
      const todo = anc.filter((x) => status(x) !== 'learned').length;
      const vis = [...sub.nodes].sort(byTopo).map((x) => NODES.get(x));
      mini = L.layeredLayout(vis, (x) => PRED.get(x).filter((p) => sub.nodes.has(p)));
      h += `<h2>목표: ${esc(n.name)}</h2>`
        + `<p class="why">학습 DAG에서 이 Concept의 선수 조상 ${anc.length}개(미완료 ${todo}개)를 갈래 그대로 보여줍니다. 시작점 ${sub.roots.filter((x) => x !== id).length}곳에서 위→아래로 공부하세요.</p>`
        + `<p><button type="button" class="pbtn solid" data-act="path-highlight">캔버스에서 경로 강조</button>`
        + (state.path ? '<button type="button" class="pbtn" data-act="path-clear">강조 해제</button>' : '') + '</p>'
        + `<div class="minidag"><svg class="edges" aria-hidden="true"></svg>${mini.layers.map((row) => `<div class="layer">${row.map((x) => nodeHTML(x, { compact: true })).join('')}</div>`).join('')}</div>`
        + `<details class="stage-path" ${anc.length <= 12 ? 'open' : ''}><summary>체크리스트 (위상 순서) <span class="p">${anc.length - todo}/${anc.length}</span></summary><ol class="path-list">${anc.map((x) => pathRow(x)).join('')}${pathRow(id, 'target')}</ol></details>`;
      if (mast.length) h += `<h3>이 Concept을 마무리하는 하위 학습 <span class="n">${mast.length}</span></h3><ol class="path-list">${mast.map((x) => pathRow(x, 'sub')).join('')}</ol>`;
    } else {
      h += '<h2>학습 경로</h2><p class="why">Concept을 선택하면 학습 DAG에서 그 Concept까지 필요한 선수 조상만 추출해 갈래 그대로 보여줍니다.</p>';
    }
    h += `<h3>기본 학습 경로 (Stage 순)</h3><p class="flowline">${STAGES.filter((s) => s.stage !== 'L').map((s) => `<b>${esc(s.title)}</b>`).join(' → ')}</p>`;
    for (const s of STAGES) {
      if (s.stage === 'L' && !state.includeLegacy) continue;
      const members = D.nodes.filter((n) => String(n.stage) === String(s.stage) && legacyOK(n)).sort((a, b) => a.topo_index - b.topo_index);
      const learned = members.filter((n) => status(n.id) === 'learned').length;
      const core = members.filter((n) => (n.visible_by_default ? n.display_tier : n.legacy_display_tier) === 'core');
      h += `<details class="stage-path"><summary><b>Stage ${s.stage === 'L' ? 'L' : s.stage}</b> ${esc(s.title)}<span class="p">${learned}/${members.length}</span></summary>`
        + `<div class="cl">핵심 ${core.length}개 · 선수관계 순서(위상 정렬)</div><ol class="path-list">${core.map((n) => pathRow(n.id)).join('')}</ol>`
        + (members.length > core.length ? `<details><summary class="cl">세부 포함 전체 ${members.length}개</summary><ol class="path-list">${members.map((n) => pathRow(n.id)).join('')}</ol></details>` : '')
        + '</details>';
    }
    panelBody.innerHTML = h;
    if (mini) {
      const box = panelBody.querySelector('.minidag');
      box._links = mini.links.map((l) => ({ ...l, inferred: !!EDGE.get(l.s + '>' + l.t)?.inferred }));
      requestAnimationFrame(() => drawLinks(box, box._links, { sel: id, path: null }));
    }
  }

  function renderPanel() {
    for (const b of document.querySelectorAll('.tabs [data-tab]')) b.classList.toggle('on', b.dataset.tab === state.tab);
    if (state.tab === 'path') renderPath(); else renderDetail();
  }

  // ------------------------------------------------------------------ actions
  function ensureShown(id) {
    const n = NODES.get(id);
    if (!inFilter(n)) state.filter = { stage: '', domain: '' };
    state.sectionCollapsed.learning.delete(String(n.stage));
    state.sectionCollapsed.structure.delete(n.structure_domain);
    if ((state.clusterMode.learning[n.cluster] || 'core') === 'collapsed') state.clusterMode.learning[n.cluster] = 'core';
    if ((state.clusterMode.structure[n.structure_cluster] || 'core') === 'collapsed') state.clusterMode.structure[n.structure_cluster] = 'core';
  }
  function select(id, { scroll = true } = {}) {
    state.selected = id;
    if (id && state.path && !state.path.set.has(id)) state.path = null;
    if (id) {
      ensureShown(id);
      const n = NODES.get(id);
      // reveal the next step (structure children + same-block successors) and the direct prerequisites
      for (const c of n.structure_children) if (legacyOK(NODES.get(c))) state.revealed.add(c);
      for (const x of SUCC.get(id)) if (NODES.get(x).cluster === n.cluster && legacyOK(NODES.get(x))) state.revealed.add(x);
      for (const p of [...PRED.get(id), ...SPRED.get(id)]) if (legacyOK(NODES.get(p))) { state.revealed.add(p); ensureShown(p); }
      panel.classList.add('open');
    }
    savePrefs();
    render();
    renderPanel();
    if (id && scroll) {
      requestAnimationFrame(() => {
        const el = inner.querySelector(`.node[data-id="${id}"]`);
        if (el) { el.scrollIntoView({ block: 'center', inline: 'nearest', behavior: 'smooth' }); el.classList.add('flash'); }
      });
    }
  }
  function toggleLearned(id) {
    setStatus(id, status(id) === 'learned' ? 'not_started' : 'learned');
    render(); renderPanel();
  }
  function setPathFocus(id) {
    const set = new Set([...L.ancestors(PRED, id), id, ...masterySet(id)]);
    state.path = { target: id, set };
    if (isStructure()) state.view = 'learning';
    for (const x of set) ensureShown(x);
    render(); renderPanel();
  }
  function setView(v) {
    state.view = v;
    savePrefs(); render(); renderPanel();
    if (state.selected) requestAnimationFrame(() => inner.querySelector(`.node[data-id="${state.selected}"]`)?.scrollIntoView({ block: 'center' }));
  }
  function setLegacy(on) { state.includeLegacy = on; savePrefs(); render(); renderPanel(); }

  document.addEventListener('click', (ev) => {
    const t = ev.target;
    const goto = t.closest('[data-goto]');
    if (goto) { select(goto.dataset.goto); closeSearch(); return; }
    const act = t.closest('[data-act]');
    if (act) {
      const a = act.dataset.act;
      const nodeEl = act.closest('.node');
      const clusterEl = act.closest('.cluster');
      const modes = state.clusterMode[state.view];
      if (a === 'toggle-learned' && nodeEl) { ev.stopPropagation(); toggleLearned(nodeEl.dataset.id); return; }
      if (a === 'section-toggle') {
        const k = act.closest('.stage').dataset.section;
        const set = state.sectionCollapsed[state.view];
        if (set.has(k)) set.delete(k); else set.add(k);
        savePrefs(); render(); return;
      }
      if (a === 'cluster-toggle') { const code = clusterEl.dataset.cluster; modes[code] = L.nextClusterMode(clusterMode(code), 'toggle'); savePrefs(); render(); return; }
      if (a === 'cluster-all') { modes[clusterEl.dataset.cluster] = L.nextClusterMode(clusterMode(clusterEl.dataset.cluster), 'expand'); savePrefs(); render(); return; }
      if (a === 'cluster-core') {
        const code = clusterEl.dataset.cluster;
        modes[code] = L.nextClusterMode(clusterMode(code), 'core');
        for (const n of CLUSTER_NODES[state.view].get(code)) state.revealed.delete(n.id);
        savePrefs(); render(); return;
      }
      if (a === 'show-legacy') { setLegacy(true); return; }
      if (a === 'path-to') { state.tab = 'path'; renderPanel(); return; }
      if (a === 'path-highlight' && state.selected) { setPathFocus(state.selected); return; }
      if (a === 'path-clear') { state.path = null; render(); renderPanel(); return; }
    }
    const dtab = t.closest('[data-dtab]');
    if (dtab) { state.detailTab = dtab.dataset.dtab; renderDetail(); return; }
    const nodeEl = t.closest('.node');
    if (nodeEl) { select(nodeEl.dataset.id, { scroll: !!nodeEl.closest('.minidag') }); return; }
    const stBtn = t.closest('.statusbar [data-st]');
    if (stBtn && state.selected) { setStatus(state.selected, stBtn.dataset.st); render(); renderPanel(); return; }
    if (!t.closest('.search')) closeSearch();
  });
  document.addEventListener('change', (ev) => {
    const cb = ev.target.closest('[data-learn]');
    if (cb) { setStatus(cb.dataset.learn, cb.checked ? 'learned' : 'not_started'); render(); renderPanel(); }
  });
  for (const el of [inner, panelBody]) {
    el.addEventListener('keydown', (ev) => {
      const nodeEl = ev.target.closest('.node');
      if (!nodeEl) return;
      if (ev.key === 'Enter') { ev.preventDefault(); select(nodeEl.dataset.id, { scroll: el === panelBody }); }
      if (ev.key === ' ') { ev.preventDefault(); toggleLearned(nodeEl.dataset.id); }
    });
  }

  // top controls
  for (const b of document.querySelectorAll('[data-view]')) b.addEventListener('click', () => setView(b.dataset.view));
  for (const b of document.querySelectorAll('[data-scope]')) b.addEventListener('click', () => setLegacy(b.dataset.scope === 'legacy'));
  const fStage = document.getElementById('f-stage');
  const fDomain = document.getElementById('f-domain');
  fStage.innerHTML = '<option value="">전체 Stage</option>' + STAGES.map((s) => `<option value="${s.stage}">Stage ${s.stage === 'L' ? 'L' : s.stage} · ${esc(s.title)}</option>`).join('');
  fDomain.innerHTML = '<option value="">전체 Domain</option>' + DOMAINS.map((d) => `<option value="${d.code}">${esc(d.name)}</option>`).join('');
  fStage.addEventListener('change', () => { state.filter.stage = fStage.value; if (fStage.value === 'L') state.includeLegacy = true; savePrefs(); render(); });
  fDomain.addEventListener('change', () => { state.filter.domain = fDomain.value; if (fDomain.value === 'D7') state.includeLegacy = true; savePrefs(); render(); });
  const hl = document.getElementById('highlight');
  hl.value = state.highlight;
  hl.addEventListener('change', () => { state.highlight = hl.value; savePrefs(); render(); });
  document.getElementById('btn-core').addEventListener('click', () => {
    state.clusterMode[state.view] = {}; state.revealed.clear(); state.sectionCollapsed[state.view].clear(); savePrefs(); render();
  });
  document.getElementById('btn-all').addEventListener('click', () => {
    for (const c of D.clusters) state.clusterMode[state.view][c.code] = 'all';
    state.sectionCollapsed[state.view].clear(); savePrefs(); render();
  });
  document.getElementById('btn-fold').addEventListener('click', () => {
    const keys = isStructure() ? DOMAINS.map((d) => d.code) : STAGES.map((s) => String(s.stage));
    for (const k of keys) state.sectionCollapsed[state.view].add(k);
    savePrefs(); render();
  });
  document.getElementById('btn-path').addEventListener('click', () => { state.tab = 'path'; panel.classList.add('open'); renderPanel(); });
  for (const b of document.querySelectorAll('.tabs [data-tab]')) b.addEventListener('click', () => { state.tab = b.dataset.tab; renderPanel(); });
  document.getElementById('panel-close').addEventListener('click', () => panel.classList.remove('open'));
  document.getElementById('btn-export').addEventListener('click', () => {
    const blob = new Blob([JSON.stringify({ exported_at: new Date().toISOString(), progress: state.progress }, null, 1)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'sqld-progress.json';
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 1000);
  });
  document.getElementById('file-import').addEventListener('change', async (ev) => {
    const f = ev.target.files[0];
    if (!f) return;
    try {
      const obj = JSON.parse(await f.text());
      const p = obj.progress || obj;
      const valid = {};
      for (const [k, v] of Object.entries(p)) if (NODES.has(k) && STATUS_LABEL[v] && v !== 'not_started') valid[k] = v;
      state.progress = valid;
      saveJSON(PROGRESS_KEY, valid);
      render(); renderPanel();
    } catch (e) { alert('가져오기 실패: ' + e.message); }
    ev.target.value = '';
  });
  document.getElementById('btn-reset').addEventListener('click', () => {
    if (!confirm('모든 학습 상태를 초기화할까요?')) return;
    state.progress = {}; saveJSON(PROGRESS_KEY, {}); render(); renderPanel();
  });
  document.getElementById('btn-theme').addEventListener('click', () => {
    const root = document.documentElement;
    const dark = root.dataset.theme ? root.dataset.theme === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
    root.dataset.theme = dark ? 'light' : 'dark';
    savePrefs(); requestAnimationFrame(drawEdges);
  });

  // ------------------------------------------------------------------ search
  const search = document.getElementById('search');
  const results = document.getElementById('search-results');
  const INDEX = L.searchIndex(D.nodes, (id) => CONTENT[id].definition);
  let active = 0; let current = [];
  function treeHTML(n) {
    if (!n) return '';
    const rows = []; const seen = new Set([n.id]);
    const push = (id, rel) => { if (!seen.has(id)) { seen.add(id); rows.push([id, rel]); } };
    for (const c of n.structure_children) push(c, '하위');
    for (const x of SUCC.get(n.id)) push(x, '다음');
    for (const r of META.get(n.id) || []) if (r.dir === 'out') push(r.other, (REL_LABEL[r.rel] || r.rel).split(' (')[0]);
    if (!rows.length) return '';
    return `<div class="sr-tree"><h4>연결 개념</h4><div class="tree-root">${esc(n.name)}</div><ul>`
      + rows.slice(0, 40).map(([id, rel]) => `<li>${chip(id)}<span class="rel">${esc(rel)}${NODES.get(id).visible_by_default ? '' : ' · Legacy'}</span></li>`).join('')
      + (rows.length > 40 ? `<li class="rel">… 외 ${rows.length - 40}개 (상세 패널)</li>` : '') + '</ul></div>';
  }
  function showResults() {
    current = L.rankSearch(INDEX, search.value);
    active = 0;
    if (!search.value.trim()) { closeSearch(); return; }
    let h = current.length ? '' : '<div class="sr-empty">일치하는 Concept이 없습니다</div>';
    current.forEach((n, i) => {
      const alias = (n.aliases || []).find((a) => L.norm(a).includes(L.norm(search.value)));
      const where = isStructure() ? `${esc(DOMAIN_BY.get(n.structure_domain).name)} › ${esc(CLUSTERS.get(n.structure_cluster).name)}` : `S${n.stage} · ${esc(n.cluster_name)}`;
      h += `<button type="button" role="option" class="sr-item ${i === 0 ? 'active' : ''}" data-goto="${n.id}">`
        + `<span class="badge prio-${n.priority}">${n.priority === 'Legacy' ? 'L' : n.priority}</span><span class="nm">${esc(n.name)}</span>`
        + (alias && L.norm(alias) !== L.norm(n.name) ? `<span class="alias">${esc(alias)}</span>` : '')
        + `<span class="where">${where}${n.visible_by_default ? '' : ' · Legacy'}</span></button>`;
    });
    h += treeHTML(current[0]);
    results.innerHTML = h;
    results.hidden = false;
  }
  function closeSearch() { results.hidden = true; }
  search.addEventListener('input', showResults);
  search.addEventListener('focus', () => { if (search.value.trim()) showResults(); });
  search.addEventListener('keydown', (ev) => {
    const items = results.querySelectorAll('.sr-item');
    if (ev.key === 'ArrowDown' || ev.key === 'ArrowUp') {
      ev.preventDefault();
      if (!items.length) return;
      active = (active + (ev.key === 'ArrowDown' ? 1 : -1) + items.length) % items.length;
      items.forEach((el, i) => el.classList.toggle('active', i === active));
      results.querySelector('.sr-tree')?.remove();
      results.insertAdjacentHTML('beforeend', treeHTML(current[active]));
    } else if (ev.key === 'Enter') {
      ev.preventDefault();
      if (current[active]) { select(current[active].id); closeSearch(); search.blur(); }
    } else if (ev.key === 'Escape') { closeSearch(); search.blur(); }
  });
  document.addEventListener('keydown', (ev) => {
    if (ev.key === '/' && document.activeElement !== search && !/input|textarea|select/i.test(document.activeElement.tagName)) {
      ev.preventDefault(); search.focus();
    } else if (ev.key === 'Escape' && document.activeElement !== search) {
      if (state.path) { state.path = null; render(); renderPanel(); } else if (state.selected) select(null);
    }
  });

  // ------------------------------------------------------------------ boot
  let rt = 0;
  new ResizeObserver(() => { cancelAnimationFrame(rt); rt = requestAnimationFrame(drawEdges); }).observe(inner);
  render();
  renderPanel();
  const hash = decodeURIComponent(location.hash.slice(1));
  if (hash) {
    const hit = D.nodes.find((n) => n.name === hash || n.id === hash);
    if (hit) select(hit.id);
  }
})();
