/* SQLD Learning DAG — viewer.
 * Data: window.SQLD_DATA (generated by scripts/build_learning_graph.py into web/data.js).
 * No external libraries; the layout is a layered DAG per Cluster with SVG edges.
 */
(() => {
  'use strict';

  const D = window.SQLD_DATA;
  const canvas = document.getElementById('canvas');
  const inner = document.getElementById('canvas-inner');
  const panelBody = document.getElementById('panel-body');
  const panel = document.getElementById('panel');
  if (!D) {
    inner.innerHTML = '<p style="padding:24px">web/data.js가 없습니다. <code>python3 scripts/build_learning_graph.py</code>를 먼저 실행하세요.</p>';
    return;
  }

  // ------------------------------------------------------------------ helpers
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const norm = (s) => String(s ?? '').toLowerCase().replace(/[\s·_\-()/]+/g, '');
  const loadJSON = (k, fb) => { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : fb; } catch { return fb; } };
  const saveJSON = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch { /* storage unavailable */ } };

  // ------------------------------------------------------------------ indexes
  const NODES = new Map(D.nodes.map((n) => [n.id, n]));
  const PRED = new Map(); const SUCC = new Map(); const EDGE = new Map();
  for (const n of D.nodes) { PRED.set(n.id, []); SUCC.set(n.id, []); }
  for (const e of D.prerequisite_edges) {
    PRED.get(e.target).push(e.source);
    SUCC.get(e.source).push(e.target);
    EDGE.set(e.source + '>' + e.target, e);
  }
  const byTopo = (a, b) => NODES.get(a).topo_index - NODES.get(b).topo_index;
  for (const l of PRED.values()) l.sort(byTopo);
  for (const l of SUCC.values()) l.sort(byTopo);

  const CLUSTERS = new Map(D.clusters.map((c) => [c.code, c]));
  const STAGES = D.stages.slice().sort((a, b) => a.order - b.order);
  const STAGE_BY = new Map(STAGES.map((s) => [String(s.stage), s]));
  const CLUSTER_NODES = new Map();
  for (const c of D.clusters) CLUSTER_NODES.set(c.code, []);
  for (const n of D.nodes) CLUSTER_NODES.get(n.cluster).push(n);
  for (const l of CLUSTER_NODES.values()) l.sort((a, b) => a.topo_index - b.topo_index);

  const META = new Map();
  for (const r of D.metadata_relations) {
    if (!META.has(r.source)) META.set(r.source, []);
    if (!META.has(r.target)) META.set(r.target, []);
    META.get(r.source).push({ rel: r.relation, other: r.target, dir: 'out', reason: r.reason });
    META.get(r.target).push({ rel: r.relation, other: r.source, dir: 'in', reason: r.reason });
  }
  const CMP = new Map(D.comparisons.map((c) => [c.id, c]));
  const DIA = new Map(D.dialects.map((d) => [d.id, d]));
  const RULES = D.rules;
  const EVID = D.evidence || {};

  const STATUS = [
    ['not_started', '미학습'], ['studying', '학습 중'], ['learned', '학습 완료'], ['review_needed', '복습 필요'],
  ];
  const STATUS_LABEL = Object.fromEntries(STATUS);
  const EVIDENCE_LABEL = {
    current: '현행 출제', legacy_only: '구범위 전용', reference: '참조', structure: '구조 노드(합성)', integration: '통합 노드(합성)',
  };
  const REL_LABEL = {
    CONTRASTS: '시험 비교 (CONTRASTS)', AFFECTS: '영향 / 함정 (AFFECTS)', DIALECT: 'DBMS 방언 (DIALECT)',
    DIALECT_OF: 'DBMS 방언 (DIALECT_OF)', DIALECT_EQUIVALENT: '방언 동치 (DIALECT_EQUIVALENT)', EXCEPTION: '예외 / 함정 (EXCEPTION)',
    IS_A: '분류 (IS_A)', IMPLEMENTS: '구현 (IMPLEMENTS)', USES: '사용 (USES)', ENFORCES: '보장 (ENFORCES)',
    REMOVED_BY: '제거 (REMOVED_BY)', RESOLVED_BY: '해소 (RESOLVED_BY)', INCREASES_NEED_FOR: '필요 증가 (INCREASES_NEED_FOR)',
    ALTERNATIVE_TO: '대안 (ALTERNATIVE_TO)', HUB_LINK: '허브 연결 (20_Hubs_Rules)', RELATED_TO: '관련 개념 (curated)',
    EXECUTION_ORDER: '논리 실행 순서 (DAG 아님)',
  };

  // ------------------------------------------------------------------ state
  const PROGRESS_KEY = 'sqld-learning-dag:progress:v1';
  const PREF_KEY = 'sqld-learning-dag:prefs:v1';
  const prefs = loadJSON(PREF_KEY, {});
  const state = {
    includeLegacy: !!prefs.includeLegacy,
    highlight: prefs.highlight || 'none',
    stageCollapsed: new Set(prefs.stageCollapsed || []),
    clusterMode: prefs.clusterMode || {}, // code -> 'collapsed' | 'core' | 'all'
    revealed: new Set(),
    selected: null,
    path: null, // {target, set:Set, order:[]}
    tab: 'detail',
    progress: loadJSON(PROGRESS_KEY, {}),
  };
  if (prefs.theme) document.documentElement.dataset.theme = prefs.theme;

  const savePrefs = () => saveJSON(PREF_KEY, {
    includeLegacy: state.includeLegacy, highlight: state.highlight,
    stageCollapsed: [...state.stageCollapsed], clusterMode: state.clusterMode,
    theme: document.documentElement.dataset.theme || '',
  });
  const status = (id) => state.progress[id] || 'not_started';
  const setStatus = (id, st) => {
    if (st === 'not_started') delete state.progress[id]; else state.progress[id] = st;
    saveJSON(PROGRESS_KEY, state.progress);
  };
  const unmet = (id) => PRED.get(id).filter((p) => status(p) !== 'learned');
  const isReady = (id) => status(id) !== 'learned' && unmet(id).length === 0;

  // ------------------------------------------------------------------ visibility
  const clusterMode = (code) => state.clusterMode[code] || 'core';
  const legacyOK = (n) => n.visible_by_default || state.includeLegacy;
  const tierOf = (n) => (n.visible_by_default ? n.display_tier : (n.legacy_display_tier || 'detail'));
  const forced = (id) => state.selected === id || state.revealed.has(id) || (state.path && state.path.set.has(id));
  function isVisible(n) {
    if (forced(n.id)) return true;
    if (!legacyOK(n)) return false;
    return clusterMode(n.cluster) === 'all' || tierOf(n) === 'core';
  }
  function stageVisible(s) {
    if (s.stage !== 'L') return true;
    if (state.includeLegacy) return true;
    return D.nodes.some((n) => n.stage === 'L' && forced(n.id));
  }

  // ------------------------------------------------------------------ cluster layout
  // Visible nodes of a cluster are layered by longest path over prerequisite edges inside the
  // cluster. Hidden nodes are bridged (dashed edge) so the order stays correct when collapsed.
  function clusterLayout(code) {
    const vis = CLUSTER_NODES.get(code).filter(isVisible);
    const visSet = new Set(vis.map((n) => n.id));
    const inC = (id) => NODES.get(id).cluster === code;
    const links = new Map();
    for (const n of vis) {
      const seen = new Set();
      const stack = PRED.get(n.id).filter(inC).map((p) => [p, true]);
      while (stack.length) {
        const [p, direct] = stack.pop();
        if (seen.has(p)) continue;
        seen.add(p);
        if (visSet.has(p)) {
          const key = p + '>' + n.id;
          if (!links.has(key) || direct) links.set(key, { s: p, t: n.id, direct });
          continue;
        }
        for (const q of PRED.get(p)) if (inC(q)) stack.push([q, false]);
      }
    }
    // transitive reduction for drawing
    const out = new Map(vis.map((n) => [n.id, []]));
    for (const l of links.values()) out.get(l.s).push(l.t);
    const reach = (from, to, skip) => {
      const st = [from]; const seen = new Set();
      while (st.length) {
        const x = st.pop();
        for (const y of out.get(x)) {
          if (x === from && y === skip) continue;
          if (y === to) return true;
          if (!seen.has(y)) { seen.add(y); st.push(y); }
        }
      }
      return false;
    };
    const drawn = [...links.values()].filter((l) => !reach(l.s, l.t, l.t));
    const layer = new Map();
    for (const n of vis) {
      let L = 0;
      for (const l of links.values()) if (l.t === n.id) L = Math.max(L, (layer.get(l.s) ?? 0) + 1);
      layer.set(n.id, L);
    }
    const layers = [];
    for (const n of vis) {
      const L = layer.get(n.id);
      (layers[L] = layers[L] || []).push(n);
    }
    // barycenter ordering
    const pos = new Map();
    layers.forEach((row, li) => {
      if (li > 0) {
        row.sort((a, b) => {
          const bc = (x) => {
            const ps = drawn.filter((l) => l.t === x.id).map((l) => pos.get(l.s)).filter((v) => v !== undefined);
            return ps.length ? ps.reduce((s, v) => s + v, 0) / ps.length : 999;
          };
          return bc(a) - bc(b) || a.topo_index - b.topo_index;
        });
      }
      row.forEach((n, k) => pos.set(n.id, k / Math.max(1, row.length - 1)));
    });
    return { layers: layers.filter(Boolean), links: drawn, count: vis.length };
  }

  // ------------------------------------------------------------------ render: canvas
  const layouts = new Map();

  function nodeClasses(n) {
    const c = ['node', 'prio-' + n.priority, 'st-' + status(n.id), 'tier-' + tierOf(n)];
    if (n.support) c.push('support');
    if (n.synthetic) c.push('synthetic', n.synthetic_kind);
    if (state.selected === n.id) c.push('selected');
    const sel = state.selected;
    if (sel && sel !== n.id) {
      if (PRED.get(sel).includes(n.id)) c.push('is-prereq');
      else if (SUCC.get(sel).includes(n.id)) c.push('is-next');
    }
    if (state.path && state.path.set.has(n.id) && state.selected !== n.id) c.push('path-member');
    const h = state.highlight;
    if (h === 'unlearned' && status(n.id) !== 'not_started') c.push('dim');
    if (h === 'ready') { if (isReady(n.id)) c.push('ready'); else c.push('dim'); }
    if (h === 'review' && status(n.id) !== 'review_needed') c.push('dim');
    if (state.path && !state.path.set.has(n.id) && h === 'none') c.push('dim');
    return c.join(' ');
  }

  function nodeHTML(n) {
    const st = status(n.id);
    const miss = unmet(n.id).length;
    const ext = PRED.get(n.id).filter((p) => NODES.get(p).cluster !== n.cluster).length;
    const prio = n.priority === 'Legacy' ? 'L' : n.priority;
    const title = [
      n.name, `Priority ${n.priority} · ${EVIDENCE_LABEL[n.evidence_status]}`,
      `현행 ${n.current_rounds}회 / 구범위 ${n.old_rounds}회`, `상태: ${STATUS_LABEL[st]}`,
      miss ? `선수 미완료 ${miss}개` : '선수 Concept 모두 완료',
    ].join('\n');
    return `<div class="${nodeClasses(n)}" data-id="${n.id}" role="button" tabindex="0" title="${esc(title)}">`
      + `<button type="button" class="chk" data-act="toggle-learned" aria-label="학습 완료 체크">${st === 'learned' ? '✓' : ''}</button>`
      + `<span class="nm">${esc(n.name)}</span><span class="pr">${prio}</span>`
      + (miss ? `<span class="lock" title="선수 Concept ${miss}개 미완료">선수 ${miss}</span>` : '')
      + (ext ? `<span class="ext" title="다른 Cluster/Stage의 선수 ${ext}개">↑${ext}</span>` : '')
      + '</div>';
  }

  function clusterHTML(code) {
    const c = CLUSTERS.get(code);
    const mode = clusterMode(code);
    const all = CLUSTER_NODES.get(code);
    const eligible = all.filter(legacyOK);
    const lay = clusterLayout(code);
    layouts.set(code, lay);
    const hiddenDetail = eligible.filter((n) => !isVisible(n)).length;
    const legacyHidden = state.includeLegacy ? 0 : all.filter((n) => !n.visible_by_default && !forced(n.id)).length;
    const learned = eligible.filter((n) => status(n.id) === 'learned').length;
    const wide = lay.count > 8 || lay.layers.some((l) => l.length > 3);
    let moreBtn = '';
    if (mode !== 'collapsed') {
      if (mode === 'all') moreBtn = '<button type="button" class="more" data-act="cluster-core">핵심만</button>';
      else if (hiddenDetail > 0) moreBtn = `<button type="button" class="more" data-act="cluster-all">+${hiddenDetail} 세부</button>`;
    }
    const body = lay.count
      ? lay.layers.map((row) => `<div class="layer">${row.map(nodeHTML).join('')}</div>`).join('')
      : '<div class="empty-cluster">표시할 Concept 없음</div>';
    return `<article class="cluster ${mode === 'collapsed' ? 'is-collapsed' : ''} ${wide && mode !== 'collapsed' ? 'wide' : ''}" data-cluster="${code}">`
      + `<div class="cluster-head"><button type="button" class="toggle" data-act="cluster-toggle" aria-expanded="${mode !== 'collapsed'}">`
      + `<span class="chev">▾</span><span class="code">${code}</span><span class="cname">${esc(c.name)}</span>`
      + `<span class="count">${learned}/${eligible.length}</span></button>${moreBtn}</div>`
      + `<div class="cluster-graph"><svg class="edges" aria-hidden="true"></svg>${body}</div>`
      + (legacyHidden ? `<div class="cluster-foot">Legacy ${legacyHidden}개 숨김 · <button type="button" data-act="show-legacy">Include Legacy</button></div>` : '')
      + '</article>';
  }

  function stageHTML(s) {
    const key = String(s.stage);
    const collapsed = state.stageCollapsed.has(key);
    const members = D.nodes.filter((n) => String(n.stage) === key && legacyOK(n));
    const learned = members.filter((n) => status(n.id) === 'learned').length;
    const pct = members.length ? Math.round((learned / members.length) * 100) : 0;
    const prereq = s.stage === 'L' ? 'Stage 9 이후 (선택)' : (s.prereq_stages.length ? '선수: ' + s.prereq_text : '시작 단계');
    const label = s.stage === 'L' ? 'L' : s.stage;
    return `<section class="stage ${collapsed ? 'collapsed' : ''} ${s.stage === 'L' ? 'legacy-stage' : ''}" data-stage="${key}">`
      + `<button type="button" class="stage-head" data-act="stage-toggle" aria-expanded="${!collapsed}">`
      + `<span class="stage-no">${label}</span><span class="stage-title"><h2>Stage ${label} · ${esc(s.title)}</h2>`
      + `<p>${esc(s.goal)} · <span>${esc(prereq)}</span></p></span>`
      + `<span class="stage-meta">${learned}/${members.length} 완료<span class="mini"><i style="width:${pct}%"></i></span></span>`
      + '<span class="chev">▾</span></button>'
      + `<div class="stage-body">${s.clusters.map(clusterHTML).join('')}</div></section>`;
  }

  const ARROW = '<div class="stage-arrow" aria-hidden="true"><svg width="16" height="22" viewBox="0 0 16 22"><path d="M8 0v18M2 13l6 7 6-7" fill="none" stroke="currentColor" stroke-width="1.6"/></svg></div>';

  function render() {
    const top = canvas.scrollTop;
    layouts.clear();
    const html = STAGES.filter(stageVisible).map(stageHTML).join(ARROW);
    inner.innerHTML = html + '<svg class="overlay" id="overlay" aria-hidden="true"></svg>';
    canvas.scrollTop = top;
    requestAnimationFrame(drawEdges);
    renderProgress();
  }

  // ------------------------------------------------------------------ edges
  function center(el, base) {
    const r = el.getBoundingClientRect();
    return { x: r.left - base.left + r.width / 2, top: r.top - base.top, bottom: r.bottom - base.top, h: r.height };
  }
  function curve(a, b) {
    const y1 = a.bottom; const y2 = b.top;
    const dy = Math.max(14, (y2 - y1) / 2);
    return `M${a.x},${y1} C${a.x},${y1 + dy} ${b.x},${y2 - dy} ${b.x},${y2 - 3}`;
  }
  function drawEdges() {
    for (const card of inner.querySelectorAll('.cluster:not(.is-collapsed)')) {
      const code = card.dataset.cluster;
      const g = card.querySelector('.cluster-graph');
      const svg = g.querySelector('svg.edges');
      const lay = layouts.get(code);
      if (!lay) continue;
      const base = g.getBoundingClientRect();
      const sel = state.selected;
      let out = '';
      for (const l of lay.links) {
        const se = g.querySelector(`.node[data-id="${l.s}"]`);
        const te = g.querySelector(`.node[data-id="${l.t}"]`);
        if (!se || !te) continue;
        const a = center(se, base); const b = center(te, base);
        if (b.top <= a.bottom) continue;
        let cls = 'e' + (l.direct ? '' : ' indirect');
        if (sel && l.t === sel) cls += ' hi-in';
        else if (sel && l.s === sel) cls += ' hi-out';
        else if (state.path && state.path.set.has(l.s) && state.path.set.has(l.t)) cls += ' path';
        else if (state.highlight !== 'none' || state.path) cls += ' dim';
        out += `<path class="${cls}" d="${curve(a, b)}"/>`;
        out += `<circle class="ah ${cls.includes('hi-in') ? 'hi-in' : cls.includes('hi-out') ? 'hi-out' : ''}" cx="${b.x}" cy="${b.top - 2}" r="2.4"/>`;
      }
      svg.innerHTML = out;
    }
    drawOverlay();
  }
  function drawOverlay() {
    const svg = document.getElementById('overlay');
    if (!svg) return;
    svg.setAttribute('width', inner.scrollWidth);
    svg.setAttribute('height', inner.scrollHeight);
    const sel = state.selected;
    if (!sel) { svg.innerHTML = ''; return; }
    const base = inner.getBoundingClientRect();
    const me = inner.querySelector(`.node[data-id="${sel}"]`);
    if (!me) { svg.innerHTML = ''; return; }
    const m = center(me, base);
    const myCluster = NODES.get(sel).cluster;
    let out = '';
    const line = (a, b, cls) => {
      const dy = Math.max(30, Math.abs(b.top - a.bottom) / 2);
      const y1 = a.bottom; const y2 = b.top;
      const d = y2 > y1 ? `M${a.x},${y1} C${a.x},${y1 + dy} ${b.x},${y2 - dy} ${b.x},${y2}`
        : `M${a.x},${a.top} C${a.x - 60},${a.top - dy} ${b.x + 60},${b.bottom + dy} ${b.x},${b.bottom}`;
      out += `<path class="xe ${cls}" d="${d}"/>`;
    };
    for (const p of PRED.get(sel)) {
      if (NODES.get(p).cluster === myCluster) continue;
      const el = inner.querySelector(`.node[data-id="${p}"]`);
      if (el) line(center(el, base), m, 'in');
    }
    for (const s of SUCC.get(sel)) {
      if (NODES.get(s).cluster === myCluster) continue;
      const el = inner.querySelector(`.node[data-id="${s}"]`);
      if (el) line(m, center(el, base), 'out');
    }
    svg.innerHTML = out;
  }

  // ------------------------------------------------------------------ header progress
  function renderProgress() {
    const vis = D.nodes.filter(legacyOK);
    const cur = D.nodes.filter((n) => n.evidence_status === 'current');
    const learned = vis.filter((n) => status(n.id) === 'learned').length;
    const curLearned = cur.filter((n) => status(n.id) === 'learned').length;
    const aNodes = D.nodes.filter((n) => n.priority === 'A');
    const aLearned = aNodes.filter((n) => status(n.id) === 'learned').length;
    const studying = vis.filter((n) => status(n.id) === 'studying').length;
    const review = vis.filter((n) => status(n.id) === 'review_needed').length;
    const ready = vis.filter((n) => isReady(n.id)).length;
    const pct = vis.length ? Math.round((learned / vis.length) * 100) : 0;
    document.getElementById('progress').innerHTML =
      `<span>학습 완료 <b>${learned}</b> / ${vis.length}</span><span class="bar"><i style="width:${pct}%"></i></span>`
      + `<span>현행 Concept <b>${curLearned}</b>/${cur.length}</span>`
      + `<span>Priority A <b>${aLearned}</b>/${aNodes.length}</span>`
      + `<span>학습 중 <b>${studying}</b></span><span>복습 필요 <b>${review}</b></span>`
      + `<span>지금 공부 가능 <b>${ready}</b></span>`
      + `<span>${state.includeLegacy ? 'Legacy 포함' : `Legacy ${D.nodes.filter((n) => !n.visible_by_default).length}개 숨김`}</span>`;
    document.getElementById('sub').textContent =
      `Concept ${D.summary['Total source concepts']} · 현행 ${D.summary['Current concepts']} · prerequisite edge ${D.summary['Explicit prerequisite edges'] + D.summary['Inferred prerequisite edges']} · DAG ${D.summary['Is DAG'] ? '✓' : '✗'}`;
  }

  // ------------------------------------------------------------------ panel: detail
  const nm = (id) => esc(NODES.get(id).name);
  const conceptBtn = (id, extra = '') => `<button type="button" class="cbtn" data-goto="${id}">${nm(id)}</button>${extra}`;
  const stageTag = (n) => `S${n.stage}`;

  function whyGenerated(n) {
    const parts = [];
    if (n.synthetic && n.synthetic_kind === 'integration') {
      const pa = PRED.get(n.id).filter((x) => NODES.get(x).priority === 'A').length;
      parts.push(`여러 Stage에 흩어진 선수 Concept ${PRED.get(n.id).length}개(Priority A ${pa}개)의 DBMS 차이·시험 함정을 한 번에 정리하는 Stage 9 통합 복습 노드.`);
    } else if (n.synthetic) {
      parts.push(`원본에 없는 학습 경유 노드. 다음 Concept ${SUCC.get(n.id).length}개(${SUCC.get(n.id).slice(0, 4).map((x) => NODES.get(x).name).join(', ')}${SUCC.get(n.id).length > 4 ? ' …' : ''})를 이해하기 위한 공통 문맥.`);
    } else if (n.node_type === 'DIALECT') {
      parts.push('DBMS 방언 비교의 기준점. 관련 개념 섹션에서 이 DBMS 고유 문법(DIALECT_OF)을 확인하세요.');
    }
    if (n.evidence_status === 'current') parts.push(`52회 이후 현행 ${n.current_rounds}회 출제 확인(${n.current_round_list.join(', ') || '-'}회).`);
    else if (n.old_rounds) parts.push(`현행 증거 없음 · 구범위 ${n.old_rounds}회 출제(${n.old_round_list.join(', ')}회).`);
    const nextCur = SUCC.get(n.id).filter((x) => NODES.get(x).evidence_status === 'current').length;
    if (nextCur) parts.push(`현행 Concept ${nextCur}개를 이해하기 위한 직접 선수 Concept.`);
    if (n.support) parts.push(`기본 화면에 표시되는 이유: ${n.support_for_count}개 현행/통합 Concept의 선수 또는 상위 개념.`);
    if (n.mindmap_gap) parts.push(`기존 마인드맵에 ${n.mindmap_status === '없음' ? '없던' : '세분화가 필요했던'} 현행 Concept(${n.mindmap_gap_action}).`);
    return parts.join(' ');
  }

  function edgeLine(src, dst, viewpoint) {
    const e = EDGE.get(src + '>' + dst);
    const other = viewpoint === 'pre' ? src : dst;
    const o = NODES.get(other);
    const tag = e.origin === 'explicit'
      ? `<span class="tag exp" title="17_KG_Edges 명시 관계">${esc(e.source_relations.join('+'))}</span>`
      : '<span class="tag" title="curated inferred prerequisite">inferred</span>';
    const extra = o.cluster !== NODES.get(viewpoint === 'pre' ? dst : src).cluster
      ? `<span class="tag">${esc(o.cluster)} · ${stageTag(o)}</span>` : '';
    const leg = o.visible_by_default ? '' : '<span class="tag">Legacy</span>';
    return `<li><span class="sdot st-${status(other)}" title="${STATUS_LABEL[status(other)]}"></span><span>`
      + conceptBtn(other, tag + extra + leg)
      + `<span class="why-edge">${esc(e.reason || (e.source_reasons || []).join(' / '))}</span></span></li>`;
  }

  function cmpHTML(c, selfId) {
    const selfName = NODES.get(selfId).name;
    const rows = c.rows.map((r) => {
      const me = r[0] === selfName || r[0].startsWith(selfName + '(') || r[0].startsWith(selfName + ' ');
      return `<tr class="${me ? 'me' : ''}">${r.map((v) => `<td>${esc(v)}</td>`).join('')}</tr>`;
    }).join('');
    const links = c.concepts.filter((x) => x !== selfId).map((x) => `<button type="button" class="chip" data-goto="${x}">${nm(x)}</button>`).join('');
    return `<div class="cmp"><h4>${esc(c.title)}</h4><div class="tw"><table><thead><tr>${c.headers.map((h) => `<th>${esc(h)}</th>`).join('')}</tr></thead>`
      + `<tbody>${rows}</tbody></table></div><div class="take">${esc(c.takeaway)}</div>`
      + (links ? `<div class="take chips">${links}</div>` : '') + '</div>';
  }

  function dialectHTML(ids, notes) {
    if (!ids.length && !notes.length) return '<p class="empty">DBMS별 차이 없음(또는 미정리)</p>';
    let h = '';
    if (ids.length) {
      h += '<div class="cmp"><div class="tw"><table><thead><tr><th>주제</th><th>ANSI/ISO</th><th>Oracle</th><th>SQL Server</th></tr></thead><tbody>';
      for (const id of ids) {
        const d = DIA.get(id);
        h += `<tr><td>${esc(d.topic)}</td><td>${esc(d.ansi)}</td><td>${esc(d.oracle)}</td><td>${esc(d.sqlserver)}</td></tr>`;
        if (d.note) h += `<tr><td></td><td colspan="3" class="exp-note">${esc(d.note)}</td></tr>`;
      }
      h += '</tbody></table></div></div>';
    }
    if (notes.length) h += `<ul class="rules">${notes.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>`;
    return h;
  }

  function relationsHTML(id) {
    const list = META.get(id) || [];
    if (!list.length) return '<p class="empty">없음</p>';
    const groups = new Map();
    for (const r of list) {
      const k = r.rel;
      if (!groups.has(k)) groups.set(k, []);
      if (!groups.get(k).some((x) => x.other === r.other)) groups.get(k).push(r);
    }
    let h = '';
    for (const [rel, items] of groups) {
      h += `<div class="rel-group"><div class="rt">${esc(REL_LABEL[rel] || rel)}</div><div class="chips">`
        + items.map((r) => `<button type="button" class="chip ${NODES.get(r.other).visible_by_default ? '' : 'legacy'}" data-goto="${r.other}" title="${esc((r.dir === 'out' ? '→ ' : '← ') + (r.reason || ''))}">${r.dir === 'in' ? '← ' : ''}${nm(r.other)}</button>`).join('')
        + '</div></div>';
    }
    return h;
  }

  function evidenceHTML(n) {
    const rows = EVID[n.id] || [];
    const cur = rows.filter((r) => r.round >= 52);
    const old = rows.filter((r) => r.round < 52);
    const table = (rs) => (rs.length ? `<details><summary>회차별 근거 ${rs.length}건</summary><table>${rs.map((r) => `<tr><td>${r.year} · ${r.round}회</td><td>${esc(r.strength)}</td><td>${r.url ? `<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.url.replace(/^https?:\/\//, '').slice(0, 48))}</a>` : ''}${r.memo ? `<div class="exp-note">${esc(r.memo)}</div>` : ''}</td></tr>`).join('')}</table></details>` : '');
    const ce = n.current_evidence;
    const le = n.legacy_evidence;
    let h = '<h3>현행 기출 근거 <span class="n">(52회 이후)</span></h3><div class="evi">';
    if (n.current_round_list.length || ce) {
      h += `<div class="rounds">${(ce ? ce.rounds : n.current_round_list).map((r) => `<span class="rd cur">${r}회</span>`).join('')}</div>`;
      if (ce) h += `<div class="exp-note">증거강도 ${esc(ce.strength)} · ${esc(ce.interpretation)}${ce.source ? ` · <a href="${esc(ce.source)}" target="_blank" rel="noopener">대표 출처</a>` : ''}</div>`;
      h += table(cur);
    } else h += '<p class="empty">52회 이후 현행 출제 증거 없음</p>';
    h += '</div><h3>구범위 기출 근거 <span class="n">(51회 이전)</span></h3><div class="evi">';
    if (n.old_round_list.length) {
      h += `<div class="rounds">${n.old_round_list.map((r) => `<span class="rd">${r}회</span>`).join('')}</div>`;
      if (le) h += `<div class="exp-note">${esc(le.scope)} · ${esc(le.interpretation)}</div>`;
      h += table(old);
    } else h += '<p class="empty">구범위 출제 증거 없음</p>';
    return h + '</div>';
  }

  function renderDetail() {
    const id = state.selected;
    if (!id) {
      panelBody.innerHTML = introHTML();
      return;
    }
    const n = NODES.get(id);
    const r = RULES[id];
    const st = status(id);
    const miss = unmet(id);
    const c = CLUSTERS.get(n.cluster);
    const s = STAGE_BY.get(String(n.stage));
    const parent = n.hierarchy_parent ? NODES.get(n.hierarchy_parent) : null;
    let h = `<div class="crumbs">Stage ${n.stage === 'L' ? 'L' : n.stage} ${esc(s.title)} › ${esc(n.domain_name)} › ${esc(c.code)} ${esc(c.name)}`
      + (parent ? ` › <button type="button" data-goto="${parent.id}">${esc(parent.name)}</button>` : '') + '</div>';
    h += `<h2>${esc(n.name)}</h2><div class="badges">`
      + `<span class="badge prio-${n.priority}" title="${esc((n.priority_reasons || []).join('\n'))}">Priority ${n.priority}</span>`
      + `<span class="badge ${n.evidence_status === 'current' ? 'cur' : ''}">${EVIDENCE_LABEL[n.evidence_status]}</span>`
      + `<span class="badge">${esc(n.node_type)}</span>`
      + `<span class="badge">현행 ${n.current_rounds}회 · 구범위 ${n.old_rounds}회</span>`
      + (n.mindmap_status ? `<span class="badge">마인드맵: ${esc(n.mindmap_status)}</span>` : '')
      + (n.mindmap_gap ? `<span class="badge gap" title="13_Current_Mindmap_Gaps">gap: ${esc(n.mindmap_gap_action)}</span>` : '')
      + (n.support ? '<span class="badge" title="현행 Concept의 선수/상위 개념이라 기본 화면에 표시">보조(선수)</span>' : '')
      + (!n.visible_by_default ? '<span class="badge prio-Legacy">기본 화면 숨김</span>' : '')
      + '</div>';
    h += `<div class="exp-note">${esc((n.priority_reasons || []).join(' · '))}</div>`;
    if (n.synthetic) h += `<div class="note">원본 시트에 없는 <b>${n.synthetic_kind === 'integration' ? '통합(Stage 9)' : '구조'} 노드</b>입니다. 근거: ${esc(n.synthetic_basis)}</div>`;
    if (n.placement_override) {
      const p = n.placement_override;
      h += `<div class="note">배치 조정: 원본 ${esc(p.from_cluster)}(${esc(p.from_cluster_name)}, Stage ${p.from_stage}) → ${esc(p.to_cluster)}(Stage ${p.to_stage}). ${esc(p.reason)}</div>`;
    }

    h += '<div class="statusbar" role="group" aria-label="학습 상태">'
      + STATUS.map(([k, lbl]) => `<button type="button" data-st="${k}" class="${st === k ? 'on' : ''}">${lbl}</button>`).join('') + '</div>';
    if (miss.length) {
      h += `<div class="note warn">선수 Concept <b>${miss.length}개</b>가 아직 '학습 완료'가 아닙니다: ${miss.map((x) => `<button type="button" class="chip" data-goto="${x}">${nm(x)}</button>`).join(' ')}</div>`;
    } else if (PRED.get(id).length) {
      h += '<div class="note ok">선수 Concept을 모두 학습했습니다. 지금 공부하기 좋은 순서입니다.</div>';
    }
    h += `<p><button type="button" class="pbtn solid" data-act="path-to">이 Concept까지 학습 경로</button></p>`;

    h += `<h3>Definition</h3><p class="def">${esc(r.definition) || '<span class="empty">정의 미작성</span>'}</p>`;
    h += `<h3>Why it matters</h3><p class="why">${esc(r.why_it_matters || whyGenerated(n))}</p>`;
    if (r.why_it_matters) h += `<p class="exp-note">${esc(whyGenerated(n))}</p>`;
    for (const hub of r.hubs) h += `<div class="note"><b>${esc(hub.hub)}</b> 허브 (${esc(hub.role)}) — ${esc(hub.study_note)}</div>`;

    const preds = PRED.get(id);
    h += `<h3>Prerequisites <span class="n">${preds.length}</span></h3>`
      + (preds.length ? `<ul class="plain clist">${preds.map((p) => edgeLine(p, id, 'pre')).join('')}</ul>` : `<p class="empty">선수 Concept 없음 — ${esc(c.name)} Cluster의 시작점</p>`);
    const nexts = SUCC.get(id);
    h += `<h3>Next concepts <span class="n">${nexts.length}</span></h3>`
      + (nexts.length ? `<ul class="plain clist">${nexts.map((x) => edgeLine(id, x, 'next')).join('')}</ul>` : '<p class="empty">이 Concept을 선수로 하는 Concept 없음</p>');
    if (n.hierarchy_children.length) {
      h += `<h3>하위 Concept <span class="n">${n.hierarchy_children.length} · 계층(BELONGS_TO), 선수관계 아님</span></h3><div class="chips">`
        + n.hierarchy_children.map((x) => `<button type="button" class="chip ${NODES.get(x).visible_by_default ? '' : 'legacy'}" data-goto="${x}" title="${NODES.get(x).visible_by_default ? '' : 'Legacy — 기본 화면 숨김'}">${nm(x)}${NODES.get(x).visible_by_default ? '' : ' ·L'}</button>`).join('')
        + '</div>';
    }

    h += `<h3>Core rules <span class="n">${r.core_rule.length}</span></h3>`
      + (r.core_rule.length ? `<ul class="rules">${r.core_rule.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : '<p class="empty">정리된 규칙 없음 — 정의와 비교 카드를 참고</p>');
    if (r.execution_order) {
      h += '<div class="note"><b>DAG가 아닌 실행 순서 관계</b><ul class="rules">'
        + r.execution_order.map((x) => `<li><code>${esc(x.edge)}</code> — ${esc(x.note)}</li>`).join('') + '</ul></div>';
    }
    h += `<h3>Exam traps <span class="n">${r.exam_traps.length}</span></h3>`
      + (r.exam_traps.length ? `<ul class="traps">${r.exam_traps.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>` : '<p class="empty">정리된 함정 없음</p>');
    h += `<h3>시험 비교 <span class="n">${r.comparisons.length}</span></h3>`
      + (r.comparisons.length ? r.comparisons.map((cid) => cmpHTML(CMP.get(cid), id)).join('') : '<p class="empty">비교 카드 없음</p>');
    h += `<h3>DBMS differences</h3>${dialectHTML(r.dialects, r.dialect_notes)}`;
    if (r.examples.length) {
      h += '<h3>Examples</h3>' + r.examples.map((x) => `<pre class="ex"><code>${esc(x.sql)}</code></pre><p class="exp-note">${esc(x.explain)}</p>`).join('');
    }
    h += `<h3>관련 개념 · 함정 · 방언 <span class="n">DAG edge 아님</span></h3>${relationsHTML(id)}`;
    h += evidenceHTML(n);
    panelBody.innerHTML = h;
    panelBody.scrollTop = 0;
  }

  function introHTML() {
    const flow = STAGES.filter((s) => s.stage !== 'L').map((s) => `<b>${esc(s.title)}</b>`).join(' → ');
    const ready = D.nodes.filter((n) => n.visible_by_default && isReady(n.id) && n.priority === 'A').slice(0, 12);
    const sm = D.summary;
    return `<h2>SQLD Learning DAG</h2>
      <p class="why">이 화면은 전체 지식 관계가 아니라 <b>"이 Concept을 이해하기 전에 무엇을 알아야 하는가"</b>만 화살표로 그린 학습 순서도입니다.
      위 Stage부터 아래로, 각 Cluster 안에서는 위 줄에서 아래 줄로 공부하세요.</p>
      <h3>기본 학습 경로</h3><p class="flowline">${flow}</p>
      <h3>지금 공부할 수 있는 Priority A</h3><div class="chips">${ready.map((n) => `<button type="button" class="chip" data-goto="${n.id}">${esc(n.name)}</button>`).join('') || '<span class="empty">없음</span>'}</div>
      <h3>읽는 법</h3><ul class="rules">
        <li>실선 화살표: 선수 Concept → 다음 Concept. 점선: 숨겨진 세부 Concept을 거친 선수 관계</li>
        <li><span class="lock-demo">선수 2</span> 아직 학습 완료하지 않은 선수 Concept 수, <span class="ext-demo">↑2</span> 다른 Cluster/Stage에 있는 선수 수</li>
        <li>비교(RANK vs DENSE_RANK 등)·DBMS 차이·함정은 화살표가 아니라 Concept 상세 패널의 카드로 보여줍니다</li>
        <li>Concept 왼쪽 동그라미를 누르면 학습 완료 체크, 상세 패널에서 학습 중/복습 필요 지정</li>
        <li>Legacy(52회 이후 현행 증거 없음)는 기본 숨김. 단 현행 Concept의 선수인 구범위 Concept은 Priority C 보조 노드로 표시</li>
      </ul>
      <h3>데이터</h3><p class="exp-note">Concept ${sm['Total source concepts']} (현행 ${sm['Current concepts']}, Legacy-only ${sm['Legacy-only concepts']}) ·
      DAG 노드 ${sm['Learning DAG nodes']} · 명시 선수 edge ${sm['Explicit prerequisite edges']} · inferred ${sm['Inferred prerequisite edges']} · Is DAG ${sm['Is DAG']}</p>`;
  }

  // ------------------------------------------------------------------ panel: path
  function ancestors(id) {
    const out = new Set(); const st = [...PRED.get(id)];
    while (st.length) { const x = st.pop(); if (out.has(x)) continue; out.add(x); st.push(...PRED.get(x)); }
    return out;
  }
  function masterySet(id) {
    // descendants inside the same cluster: what to study to "finish" the topic
    const n = NODES.get(id); const out = new Set(); const st = [...SUCC.get(id)];
    while (st.length) {
      const x = st.pop();
      if (out.has(x)) continue;
      const xn = NODES.get(x);
      if (xn.cluster !== n.cluster || !legacyOK(xn)) continue;
      out.add(x); st.push(...SUCC.get(x));
    }
    for (const c of n.hierarchy_children) if (legacyOK(NODES.get(c))) out.add(c);
    return out;
  }
  function pathRow(id, cls = '') {
    const n = NODES.get(id);
    return `<li class="${cls}"><input type="checkbox" data-learn="${id}" ${status(id) === 'learned' ? 'checked' : ''} aria-label="학습 완료">`
      + `<button type="button" class="nm" data-goto="${id}">${esc(n.name)}</button>`
      + `<span class="badge prio-${n.priority}">${n.priority === 'Legacy' ? 'L' : n.priority}</span>`
      + `<span class="stg">S${n.stage} · ${esc(n.cluster)}</span></li>`;
  }
  function renderPath() {
    let h = '';
    const id = state.selected;
    if (id) {
      const n = NODES.get(id);
      const anc = [...ancestors(id)].sort(byTopo);
      const mast = [...masterySet(id)].sort(byTopo);
      const todo = anc.filter((x) => status(x) !== 'learned').length;
      h += `<h2>목표: ${esc(n.name)}</h2>`
        + `<p class="why">이 Concept을 이해하는 데 필요한 선수 Concept만 추출한 최단 학습 경로입니다 (DAG 조상 ${anc.length}개, 미완료 ${todo}개). 위에서부터 순서대로 공부하세요.</p>`
        + `<p><button type="button" class="pbtn solid" data-act="path-highlight">캔버스에서 경로 강조</button>`
        + (state.path ? '<button type="button" class="pbtn" data-act="path-clear">강조 해제</button>' : '') + '</p>'
        + `<ol class="path-list">${anc.map((x) => pathRow(x)).join('')}${pathRow(id, 'target')}</ol>`;
      if (mast.length) {
        h += `<h3>이 Concept을 마무리하는 하위 학습 <span class="n">${mast.length}</span></h3>`
          + `<ol class="path-list">${mast.map((x) => pathRow(x, 'sub')).join('')}</ol>`;
      }
    } else {
      h += '<h2>학습 경로</h2><p class="why">Concept을 선택하면 그 Concept까지 필요한 선수 경로만 추출해 보여줍니다.</p>';
    }
    h += '<h3>기본 학습 경로 (Stage 순)</h3>';
    h += `<p class="flowline">${STAGES.filter((s) => s.stage !== 'L').map((s) => `<b>${esc(s.title)}</b>`).join(' → ')}</p>`;
    for (const s of STAGES) {
      if (s.stage === 'L' && !state.includeLegacy) continue;
      const members = D.nodes.filter((n) => String(n.stage) === String(s.stage) && legacyOK(n)).sort((a, b) => a.topo_index - b.topo_index);
      const learned = members.filter((n) => status(n.id) === 'learned').length;
      const core = members.filter((n) => tierOf(n) === 'core');
      h += `<details class="stage-path"><summary><b>Stage ${s.stage === 'L' ? 'L' : s.stage}</b> ${esc(s.title)}<span class="p">${learned}/${members.length}</span></summary>`
        + `<div class="cl">핵심 ${core.length}개 · 선수관계 순서(위상 정렬)</div><ol class="path-list">${core.map((n) => pathRow(n.id)).join('')}</ol>`
        + (members.length > core.length ? `<details><summary class="cl">세부 포함 전체 ${members.length}개</summary><ol class="path-list">${members.map((n) => pathRow(n.id)).join('')}</ol></details>` : '')
        + '</details>';
    }
    panelBody.innerHTML = h;
  }

  function renderPanel() {
    for (const b of document.querySelectorAll('.tabs [data-tab]')) b.classList.toggle('on', b.dataset.tab === state.tab);
    if (state.tab === 'path') renderPath(); else renderDetail();
  }

  // ------------------------------------------------------------------ actions
  function ensureShown(id) {
    const n = NODES.get(id);
    state.stageCollapsed.delete(String(n.stage));
    if (clusterMode(n.cluster) === 'collapsed') state.clusterMode[n.cluster] = 'core';
  }
  function select(id, { scroll = true, tab } = {}) {
    state.selected = id;
    if (tab) state.tab = tab;
    if (id && state.path && !state.path.set.has(id)) state.path = null;
    if (id) {
      ensureShown(id);
      const n = NODES.get(id);
      // reveal sub-concepts of the clicked concept (same cluster) so the next step is visible
      for (const c of n.hierarchy_children) if (legacyOK(NODES.get(c))) state.revealed.add(c);
      for (const x of SUCC.get(id)) if (NODES.get(x).cluster === n.cluster && legacyOK(NODES.get(x))) state.revealed.add(x);
      // and its direct prerequisites, so unmet ones can be seen (highlighted) on the canvas
      for (const p of PRED.get(id)) if (legacyOK(NODES.get(p))) { state.revealed.add(p); ensureShown(p); }
      panel.classList.add('open');
    }
    savePrefs();
    render();
    renderPanel();
    if (id && scroll) {
      requestAnimationFrame(() => {
        const el = inner.querySelector(`.node[data-id="${id}"]`);
        if (el) {
          el.scrollIntoView({ block: 'center', inline: 'nearest', behavior: 'smooth' });
          el.classList.add('flash');
        }
      });
    }
  }
  function toggleLearned(id) {
    setStatus(id, status(id) === 'learned' ? 'not_started' : 'learned');
    render();
    renderPanel();
  }
  function setPathFocus(id) {
    const set = new Set([...ancestors(id), id, ...masterySet(id)]);
    state.path = { target: id, set };
    for (const x of set) ensureShown(x);
    render();
    renderPanel();
  }

  document.addEventListener('click', (ev) => {
    const t = ev.target;
    const goto = t.closest('[data-goto]');
    if (goto) { select(goto.dataset.goto); closeSearch(); return; }
    const act = t.closest('[data-act]');
    if (act) {
      const a = act.dataset.act;
      const nodeEl = act.closest('.node');
      const clusterEl = act.closest('.cluster');
      if (a === 'toggle-learned' && nodeEl) { ev.stopPropagation(); toggleLearned(nodeEl.dataset.id); return; }
      if (a === 'stage-toggle') {
        const k = act.closest('.stage').dataset.stage;
        if (state.stageCollapsed.has(k)) state.stageCollapsed.delete(k); else state.stageCollapsed.add(k);
        savePrefs(); render(); return;
      }
      if (a === 'cluster-toggle') {
        const code = clusterEl.dataset.cluster;
        state.clusterMode[code] = clusterMode(code) === 'collapsed' ? 'core' : 'collapsed';
        savePrefs(); render(); return;
      }
      if (a === 'cluster-all') { state.clusterMode[clusterEl.dataset.cluster] = 'all'; savePrefs(); render(); return; }
      if (a === 'cluster-core') {
        const code = clusterEl.dataset.cluster;
        state.clusterMode[code] = 'core';
        for (const n of CLUSTER_NODES.get(code)) state.revealed.delete(n.id);
        savePrefs(); render(); return;
      }
      if (a === 'show-legacy') { setLegacy(true); return; }
      if (a === 'path-to') { state.tab = 'path'; renderPanel(); return; }
      if (a === 'path-highlight' && state.selected) { setPathFocus(state.selected); return; }
      if (a === 'path-clear') { state.path = null; render(); renderPanel(); return; }
    }
    const nodeEl = t.closest('.node');
    if (nodeEl) { select(nodeEl.dataset.id, { scroll: false }); return; }
    const stBtn = t.closest('.statusbar [data-st]');
    if (stBtn && state.selected) { setStatus(state.selected, stBtn.dataset.st); render(); renderPanel(); return; }
    if (!t.closest('.search')) closeSearch();
  });
  document.addEventListener('change', (ev) => {
    const cb = ev.target.closest('[data-learn]');
    if (cb) { setStatus(cb.dataset.learn, cb.checked ? 'learned' : 'not_started'); render(); renderPanel(); }
  });
  inner.addEventListener('keydown', (ev) => {
    const nodeEl = ev.target.closest('.node');
    if (!nodeEl) return;
    if (ev.key === 'Enter') { ev.preventDefault(); select(nodeEl.dataset.id, { scroll: false }); }
    if (ev.key === ' ') { ev.preventDefault(); toggleLearned(nodeEl.dataset.id); }
  });

  // top controls
  function setLegacy(on) {
    state.includeLegacy = on;
    for (const b of document.querySelectorAll('[data-scope]')) b.classList.toggle('on', (b.dataset.scope === 'legacy') === on);
    savePrefs(); render(); renderPanel();
  }
  for (const b of document.querySelectorAll('[data-scope]')) b.addEventListener('click', () => setLegacy(b.dataset.scope === 'legacy'));
  const hl = document.getElementById('highlight');
  hl.value = state.highlight;
  hl.addEventListener('change', () => { state.highlight = hl.value; savePrefs(); render(); });
  document.getElementById('btn-core').addEventListener('click', () => {
    state.clusterMode = {}; state.revealed.clear(); state.stageCollapsed.clear(); savePrefs(); render();
  });
  document.getElementById('btn-all').addEventListener('click', () => {
    for (const c of D.clusters) state.clusterMode[c.code] = 'all';
    state.stageCollapsed.clear(); savePrefs(); render();
  });
  document.getElementById('btn-fold').addEventListener('click', () => {
    for (const s of STAGES) state.stageCollapsed.add(String(s.stage));
    savePrefs(); render();
  });
  document.getElementById('btn-path').addEventListener('click', () => { state.tab = 'path'; panel.classList.add('open'); renderPanel(); });
  for (const b of document.querySelectorAll('.tabs [data-tab]')) b.addEventListener('click', () => { state.tab = b.dataset.tab; renderPanel(); });
  document.getElementById('panel-close').addEventListener('click', () => panel.classList.remove('open'));
  document.getElementById('btn-export').addEventListener('click', () => {
    const blob = new Blob([JSON.stringify({ exported_at: new Date().toISOString(), progress: state.progress }, null, 1)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'sqld-progress.json';
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 1000);
  });
  document.getElementById('file-import').addEventListener('change', async (ev) => {
    const f = ev.target.files[0];
    if (!f) return;
    try {
      const obj = JSON.parse(await f.text());
      const p = obj.progress || obj;
      const valid = {};
      for (const [k, v] of Object.entries(p)) if (NODES.has(k) && STATUS_LABEL[v] && v !== 'not_started') valid[k] = v;
      state.progress = valid;
      saveJSON(PROGRESS_KEY, valid);
      render(); renderPanel();
    } catch (e) { alert('가져오기 실패: ' + e.message); }
    ev.target.value = '';
  });
  document.getElementById('btn-reset').addEventListener('click', () => {
    if (!confirm('모든 학습 상태를 초기화할까요?')) return;
    state.progress = {}; saveJSON(PROGRESS_KEY, {}); render(); renderPanel();
  });
  document.getElementById('btn-theme').addEventListener('click', () => {
    const root = document.documentElement;
    const dark = root.dataset.theme ? root.dataset.theme === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
    root.dataset.theme = dark ? 'light' : 'dark';
    savePrefs(); requestAnimationFrame(drawEdges);
  });

  // ------------------------------------------------------------------ search
  const search = document.getElementById('search');
  const results = document.getElementById('search-results');
  const INDEX = D.nodes.map((n) => ({ n, name: norm(n.name), aliases: (n.aliases || []).map(norm), def: norm(RULES[n.id].definition) }));
  let active = 0; let current = [];
  function rank(q) {
    const nq = norm(q);
    if (!nq) return [];
    const out = [];
    for (const it of INDEX) {
      let s = -1;
      if (it.name === nq) s = 100;
      else if (it.aliases.includes(nq)) s = 90;
      else if (it.name.startsWith(nq)) s = 80 - Math.min(20, it.name.length - nq.length);
      else if (it.name.includes(nq)) s = 60 - Math.min(20, it.name.length - nq.length);
      else if (it.aliases.some((a) => a.includes(nq))) s = 45;
      else if (nq.length >= 2 && it.def.includes(nq)) s = 20;
      if (s >= 0) {
        if (it.n.visible_by_default) s += 3;
        if (it.n.priority === 'A') s += 2;
        out.push([s, it.n]);
      }
    }
    return out.sort((a, b) => b[0] - a[0] || a[1].topo_index - b[1].topo_index).slice(0, 14).map((x) => x[1]);
  }
  function treeHTML(n) {
    const rows = [];
    const seen = new Set([n.id]);
    const push = (id, rel) => { if (!seen.has(id)) { seen.add(id); rows.push([id, rel]); } };
    for (const c of n.hierarchy_children) push(c, '하위');
    for (const x of SUCC.get(n.id)) push(x, '다음');
    for (const r of META.get(n.id) || []) if (r.dir === 'out') push(r.other, (REL_LABEL[r.rel] || r.rel).split(' (')[0]);
    if (!rows.length) return '';
    return `<div class="sr-tree"><h4>연결 개념</h4><div class="tree-root">${esc(n.name)}</div><ul>`
      + rows.slice(0, 40).map(([id, rel]) => `<li><button type="button" class="chip ${NODES.get(id).visible_by_default ? '' : 'legacy'}" data-goto="${id}">${nm(id)}</button><span class="rel">${esc(rel)}${NODES.get(id).visible_by_default ? '' : ' · Legacy'}</span></li>`).join('')
      + (rows.length > 40 ? `<li class="rel">… 외 ${rows.length - 40}개 (상세 패널)</li>` : '') + '</ul></div>';
  }
  function showResults() {
    current = rank(search.value);
    active = 0;
    if (!search.value.trim()) { closeSearch(); return; }
    let h = current.length ? '' : '<div class="sr-empty">일치하는 Concept이 없습니다</div>';
    current.forEach((n, i) => {
      const alias = (n.aliases || []).find((a) => norm(a).includes(norm(search.value)));
      h += `<button type="button" role="option" class="sr-item ${i === 0 ? 'active' : ''}" data-goto="${n.id}">`
        + `<span class="badge prio-${n.priority}">${n.priority === 'Legacy' ? 'L' : n.priority}</span><span class="nm">${esc(n.name)}</span>`
        + (alias && norm(alias) !== norm(n.name) ? `<span class="alias">${esc(alias)}</span>` : '')
        + `<span class="where">S${n.stage} · ${esc(CLUSTERS.get(n.cluster).name)}${n.visible_by_default ? '' : ' · Legacy'}</span></button>`;
    });
    if (current[0]) h += treeHTML(current[0]);
    results.innerHTML = h;
    results.hidden = false;
  }
  function closeSearch() { results.hidden = true; }
  search.addEventListener('input', showResults);
  search.addEventListener('focus', () => { if (search.value.trim()) showResults(); });
  search.addEventListener('keydown', (ev) => {
    const items = results.querySelectorAll('.sr-item');
    if (ev.key === 'ArrowDown' || ev.key === 'ArrowUp') {
      ev.preventDefault();
      if (!items.length) return;
      active = (active + (ev.key === 'ArrowDown' ? 1 : -1) + items.length) % items.length;
      items.forEach((el, i) => el.classList.toggle('active', i === active));
      results.querySelector('.sr-tree')?.replaceWith(document.createRange().createContextualFragment(treeHTML(current[active])));
    } else if (ev.key === 'Enter') {
      ev.preventDefault();
      if (current[active]) { select(current[active].id); closeSearch(); search.blur(); }
    } else if (ev.key === 'Escape') { closeSearch(); search.blur(); }
  });
  document.addEventListener('keydown', (ev) => {
    if (ev.key === '/' && document.activeElement !== search && !/input|textarea|select/i.test(document.activeElement.tagName)) {
      ev.preventDefault(); search.focus();
    } else if (ev.key === 'Escape' && document.activeElement !== search) {
      if (state.path) { state.path = null; render(); renderPanel(); } else if (state.selected) { select(null); }
    }
  });

  // ------------------------------------------------------------------ boot
  if (state.includeLegacy) for (const b of document.querySelectorAll('[data-scope]')) b.classList.toggle('on', b.dataset.scope === 'legacy');
  let rt = 0;
  new ResizeObserver(() => { cancelAnimationFrame(rt); rt = requestAnimationFrame(drawEdges); }).observe(inner);
  render();
  renderPanel();
  const hash = decodeURIComponent(location.hash.slice(1));
  if (hash) {
    const hit = D.nodes.find((n) => n.name === hash || n.id === hash);
    if (hit) select(hit.id);
  }
})();
