"""Exam comparison cards.

These replace CONTRASTS-style edges. A card is shown in the detail panel of every concept listed in
`concepts`; it never creates a DAG edge.
"""

COMPARISONS = [
    {
        "id": "cmp_rank",
        "title": "RANK vs DENSE_RANK vs ROW_NUMBER",
        "concepts": ["RANK", "DENSE_RANK", "ROW_NUMBER", "순위 함수"],
        "headers": ["함수", "sal 300, 200, 200, 100", "동순위", "다음 순위"],
        "rows": [
            ["RANK", "1, 2, 2, 4", "같은 순위", "건너뜀"],
            ["DENSE_RANK", "1, 2, 2, 3", "같은 순위", "연속"],
            ["ROW_NUMBER", "1, 2, 3, 4", "고유 번호", "연속(동순위 순서는 비결정적)"],
        ],
        "takeaway": "동순위가 있을 때만 세 함수의 결과가 달라진다. 결과 숫자열을 보고 함수를 고르는 문제가 대표 유형.",
    },
    {
        "id": "cmp_delete_truncate_drop",
        "title": "DELETE vs TRUNCATE vs DROP",
        "concepts": ["DELETE", "TRUNCATE", "DROP"],
        "headers": ["구분", "DELETE", "TRUNCATE", "DROP"],
        "rows": [
            ["분류", "DML", "DDL", "DDL"],
            ["삭제 대상", "행(WHERE 가능)", "모든 행", "테이블 구조 + 데이터"],
            ["ROLLBACK", "가능", "Oracle 불가(자동 커밋) / SQL Server 명시적 트랜잭션 내 가능", "Oracle 불가 / SQL Server 명시적 트랜잭션 내 가능"],
            ["저장 공간", "유지", "초기화(반환)", "반환"],
            ["테이블 구조", "유지", "유지", "삭제"],
            ["삭제 트리거", "동작", "동작 안 함", "동작 안 함"],
        ],
        "takeaway": "'데이터만 전부 지우고 구조는 남기며 빠르다' = TRUNCATE. '되돌릴 수 있다' = DELETE.",
    },
    {
        "id": "cmp_where_having",
        "title": "WHERE vs HAVING",
        "concepts": ["WHERE", "HAVING", "WHERE 집계함수 사용 불가", "HAVING without GROUP BY"],
        "headers": ["구분", "WHERE", "HAVING"],
        "rows": [
            ["필터 대상", "개별 행", "그룹(GROUP BY 결과)"],
            ["평가 시점", "GROUP BY 이전", "GROUP BY 이후, SELECT 이전"],
            ["집계 함수", "사용 불가", "사용 가능"],
            ["GROUP BY 없이", "사용 가능", "가능(전체가 한 그룹)"],
        ],
        "takeaway": "집계 조건은 HAVING, 행 조건은 WHERE. 행 조건을 WHERE에 두면 그룹화 대상이 줄어 효율적이다.",
    },
    {
        "id": "cmp_union",
        "title": "UNION vs UNION ALL",
        "concepts": ["UNION", "UNION ALL", "집합 연산자"],
        "headers": ["구분", "UNION", "UNION ALL"],
        "rows": [
            ["중복 행", "제거", "유지"],
            ["정렬/중복 제거 작업", "필요(비용 큼)", "없음(빠름)"],
            ["결과 행 수 (A 3행, B 3행, 공통 1행)", "5", "6"],
        ],
        "takeaway": "결과 행 수 계산 문제가 단골. 결과의 정렬 순서는 둘 다 보장되지 않는다(ORDER BY 사용).",
    },
    {
        "id": "cmp_inner_outer",
        "title": "INNER JOIN vs OUTER JOIN",
        "concepts": ["INNER JOIN", "OUTER JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "FULL OUTER JOIN"],
        "headers": ["구분", "INNER", "LEFT OUTER", "RIGHT OUTER", "FULL OUTER"],
        "rows": [
            ["결과", "매칭 행만", "왼쪽 전부 + 매칭", "오른쪽 전부 + 매칭", "양쪽 전부"],
            ["비매칭 행", "제외", "오른쪽 컬럼 NULL", "왼쪽 컬럼 NULL", "반대쪽 NULL"],
            ["Oracle 전통 문법", "WHERE a.k = b.k", "a.k = b.k(+)", "a.k(+) = b.k", "표현 불가"],
        ],
        "takeaway": "OUTER JOIN에서 비보존 쪽 조건을 WHERE에 두면 INNER JOIN과 같아진다.",
    },
    {
        "id": "cmp_on_where_outer",
        "title": "OUTER JOIN에서 ON 조건 vs WHERE 조건",
        "concepts": ["ON vs WHERE", "OUTER JOIN 조건 위치", "OUTER JOIN 필터 위치 종합", "ON"],
        "headers": ["조건 위치", "적용 시점", "보존 테이블 행", "결과"],
        "rows": [
            ["ON (비보존 쪽 조건)", "조인 전/조인 중", "모두 유지", "조건 불만족 시 반대쪽 NULL"],
            ["WHERE (비보존 쪽 조건)", "조인 후", "NULL 채운 행 제거", "사실상 INNER JOIN"],
            ["WHERE (보존 쪽 조건)", "조인 후", "조건에 맞는 보존 행만", "의도한 필터"],
        ],
        "takeaway": "INNER JOIN에서는 ON/WHERE 결과가 같지만 OUTER JOIN에서는 다르다.",
    },
    {
        "id": "cmp_count",
        "title": "COUNT(*) vs COUNT(col) vs COUNT(DISTINCT col)",
        "concepts": ["COUNT(*)", "COUNT(열)", "COUNT(DISTINCT)", "COUNT", "NULL 집계"],
        "headers": ["식", "comm = 300, NULL, 300, NULL", "NULL 처리"],
        "rows": [
            ["COUNT(*)", "4", "NULL 행도 셈"],
            ["COUNT(comm)", "2", "NULL 제외"],
            ["COUNT(DISTINCT comm)", "1", "NULL 제외 + 중복 제거"],
        ],
        "takeaway": "0행이면 모두 0(NULL 아님). AVG(comm)의 분모는 COUNT(comm)이다.",
    },
    {
        "id": "cmp_pk_unique",
        "title": "PK vs UNIQUE",
        "concepts": ["PK", "UNIQUE", "제약조건", "개체 무결성"],
        "headers": ["구분", "PK", "UNIQUE"],
        "rows": [
            ["중복", "불가", "불가"],
            ["NULL", "불가", "허용 (Oracle 여러 개 / SQL Server 1개)"],
            ["테이블당 개수", "1개", "여러 개"],
            ["FK가 참조 가능", "가능", "가능"],
            ["CTAS 복사", "안 됨", "안 됨"],
        ],
        "takeaway": "PK = UNIQUE + NOT NULL. 차이는 NULL 허용과 개수.",
    },
    {
        "id": "cmp_identifying",
        "title": "식별 관계 vs 비식별 관계",
        "concepts": ["식별 관계", "비식별 관계", "주식별자 상속", "동일 생명주기"],
        "headers": ["구분", "식별 관계", "비식별 관계"],
        "rows": [
            ["부모 PK 위치", "자식 PK의 일부", "자식의 일반 속성(FK)"],
            ["연결 강도", "강함", "약함"],
            ["생명주기", "부모와 같음", "자식이 독립적"],
            ["IE 표기", "실선", "점선"],
            ["부모 없는 자식", "불가", "가능(FK NULL)"],
            ["단점", "자식의 PK 컬럼 수 증가, SQL 복잡", "부모 정보 조회 시 조인 증가"],
        ],
        "takeaway": "부모와 생명주기를 같이하고 부모 없이는 존재할 수 없으면 식별 관계.",
    },
    {
        "id": "cmp_minus_except",
        "title": "MINUS vs EXCEPT",
        "concepts": ["MINUS", "EXCEPT", "차집합 MINUS/EXCEPT 차이"],
        "headers": ["구분", "MINUS", "EXCEPT"],
        "rows": [
            ["DBMS", "Oracle (21c부터 EXCEPT도 지원)", "SQL Server, ANSI 표준"],
            ["의미", "A에만 있는 행(중복 제거)", "A에만 있는 행(중복 제거)"],
            ["교환 법칙", "성립 안 함(A-B ≠ B-A)", "성립 안 함"],
        ],
        "takeaway": "이름만 다르고 의미는 같다. Oracle 문제에 EXCEPT, SQL Server 문제에 MINUS가 나오면 문법 오류 함정.",
    },
    {
        "id": "cmp_topn",
        "title": "ROWNUM vs TOP vs FETCH FIRST (vs LIMIT)",
        "concepts": ["ROWNUM", "TOP", "FETCH FIRST", "LIMIT", "WITH TIES", "Top-N", "Top-N 문법 차이"],
        "headers": ["문법", "DBMS", "적용 시점", "동순위 포함", "예"],
        "rows": [
            ["ROWNUM", "Oracle", "ORDER BY 이전(WHERE 단계)", "불가", "SELECT * FROM (… ORDER BY sal DESC) WHERE ROWNUM <= 3"],
            ["TOP(n)", "SQL Server", "ORDER BY 이후", "WITH TIES", "SELECT TOP(3) WITH TIES * FROM emp ORDER BY sal DESC"],
            ["FETCH FIRST", "ANSI, Oracle 12c+, (SQL Server OFFSET-FETCH)", "ORDER BY 이후", "WITH TIES", "… ORDER BY sal DESC FETCH FIRST 3 ROWS ONLY"],
            ["LIMIT", "MySQL, PostgreSQL", "ORDER BY 이후", "불가", "… ORDER BY sal DESC LIMIT 3"],
        ],
        "takeaway": "ROWNUM만 정렬 전에 번호가 붙는다 → 인라인 뷰로 먼저 정렬해야 한다.",
    },
    {
        "id": "cmp_nvl_coalesce",
        "title": "NVL vs NVL2 vs COALESCE vs NULLIF (vs ISNULL)",
        "concepts": ["NVL", "NVL2", "COALESCE", "NULLIF", "NULL 처리 DBMS 차이"],
        "headers": ["함수", "형태", "반환", "DBMS"],
        "rows": [
            ["NVL", "NVL(a, b)", "a가 NULL이면 b, 아니면 a", "Oracle"],
            ["ISNULL", "ISNULL(a, b)", "NVL과 같음", "SQL Server"],
            ["NVL2", "NVL2(a, b, c)", "a NOT NULL → b, NULL → c", "Oracle"],
            ["COALESCE", "COALESCE(a, b, c, …)", "처음으로 NULL이 아닌 값", "ANSI (공통)"],
            ["NULLIF", "NULLIF(a, b)", "a = b → NULL, 아니면 a", "ANSI (공통)"],
        ],
        "takeaway": "인자 2개짜리 NVL과 n개짜리 COALESCE. NULLIF는 NULL을 '만드는' 함수.",
    },
    {
        "id": "cmp_null_sort",
        "title": "Oracle NULL 정렬 vs SQL Server NULL 정렬",
        "concepts": ["Oracle NULL 정렬", "SQL Server NULL 정렬", "NULL 정렬", "NULLS FIRST", "NULLS LAST", "NULL 정렬 DBMS 차이"],
        "headers": ["DBMS", "NULL 취급", "ASC", "DESC", "위치 지정 문법"],
        "rows": [
            ["Oracle", "가장 큰 값", "NULL 마지막", "NULL 처음", "NULLS FIRST / NULLS LAST"],
            ["SQL Server", "가장 작은 값", "NULL 처음", "NULL 마지막", "없음(CASE로 우회)"],
        ],
        "takeaway": "같은 ORDER BY sal DESC라도 Oracle은 NULL이 맨 위, SQL Server는 맨 아래.",
    },
    {
        "id": "cmp_group_ext",
        "title": "ROLLUP vs CUBE vs GROUPING SETS",
        "concepts": ["ROLLUP", "CUBE", "GROUPING SETS", "그룹함수 확장", "GROUPING", "전체 총계 ()"],
        "headers": ["구문 (a, b)", "생성되는 그룹", "그룹 수", "인자 순서 영향"],
        "rows": [
            ["ROLLUP(a, b)", "(a,b), (a), ()", "n+1", "있음"],
            ["CUBE(a, b)", "(a,b), (a), (b), ()", "2^n", "없음"],
            ["GROUPING SETS(a, b)", "(a), (b)", "나열한 수", "없음"],
            ["GROUPING SETS(a, b, ())", "(a), (b), ()", "나열한 수", "없음"],
        ],
        "takeaway": "소계 행의 NULL은 GROUPING(col) = 1로 실제 NULL과 구분한다.",
    },
    {
        "id": "cmp_rows_range",
        "title": "ROWS vs RANGE 프레임",
        "concepts": ["ROWS", "RANGE", "ROWS/RANGE 프레임", "RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW", "OVER 절"],
        "headers": ["구분", "ROWS", "RANGE"],
        "rows": [
            ["기준", "물리적 행 개수", "ORDER BY 값의 범위"],
            ["동일 정렬 값", "각 행을 따로", "같은 값 행을 함께 포함"],
            ["SUM(sal) OVER(ORDER BY sal …) — sal 100, 200, 200", "100, 300, 500", "100, 500, 500"],
            ["기본 프레임", "-", "ORDER BY 있고 프레임 생략 시 RANGE UNBOUNDED PRECEDING ~ CURRENT ROW"],
        ],
        "takeaway": "누적합에서 동일 값이 있으면 ROWS와 RANGE 결과가 다르다.",
    },
    {
        "id": "cmp_lag_lead",
        "title": "LAG vs LEAD vs FIRST_VALUE vs LAST_VALUE",
        "concepts": ["LAG", "LEAD", "FIRST_VALUE", "LAST_VALUE", "행 순서 함수"],
        "headers": ["함수", "가져오는 값", "주의"],
        "rows": [
            ["LAG(col, n, d)", "n행 이전", "첫 행은 d(기본 NULL)"],
            ["LEAD(col, n, d)", "n행 이후", "마지막 행은 d(기본 NULL)"],
            ["FIRST_VALUE(col)", "프레임 첫 행", "기본 프레임에서도 파티션 첫 값"],
            ["LAST_VALUE(col)", "프레임 마지막 행", "기본 프레임이면 현재 행 값 → UNBOUNDED FOLLOWING 필요"],
        ],
        "takeaway": "LAST_VALUE는 프레임을 지정하지 않으면 기대와 다른 값이 나오는 대표 함정.",
    },
    {
        "id": "cmp_subquery_types",
        "title": "단일행 vs 다중행 vs 스칼라 vs 상관 서브쿼리",
        "concepts": ["단일행 서브쿼리", "다중행 서브쿼리", "스칼라 서브쿼리", "상관 서브쿼리", "인라인 뷰", "서브쿼리"],
        "headers": ["유형", "위치/특징", "연산자", "결과가 0행 / 2행 이상"],
        "rows": [
            ["단일행", "WHERE, 1행 이하", "=, <>, <, >", "UNKNOWN(0행) / 오류"],
            ["다중행", "WHERE, 여러 행", "IN, ANY, ALL, EXISTS", "연산자별 / 정상"],
            ["스칼라", "SELECT 등, 1행 1열", "값처럼 사용", "NULL / 오류"],
            ["상관", "메인 컬럼 참조", "주로 EXISTS", "메인 행마다 평가"],
            ["인라인 뷰", "FROM 절", "테이블처럼", "ORDER BY 사용 가능"],
        ],
        "takeaway": "'단일행 연산자 + 다중행 결과 = 오류'가 가장 자주 나오는 판단 포인트.",
    },
    {
        "id": "cmp_in_exists",
        "title": "NOT IN vs NOT EXISTS (NULL 함정)",
        "concepts": ["NOT IN", "NOT EXISTS", "IN + NULL", "NULL 함정 종합", "EXISTS"],
        "headers": ["서브쿼리 결과에 NULL 포함 시", "결과"],
        "rows": [
            ["col NOT IN (SELECT x …)", "0행 (모든 비교가 UNKNOWN/FALSE)"],
            ["NOT EXISTS (SELECT 1 … WHERE x = col)", "정상 동작"],
            ["col IN (SELECT x …)", "정상 (NULL 항목만 무시)"],
        ],
        "takeaway": "NOT IN 서브쿼리에는 WHERE x IS NOT NULL을 넣거나 NOT EXISTS를 쓴다.",
    },
    {
        "id": "cmp_any_all",
        "title": "ANY vs ALL",
        "concepts": ["ANY", "ALL"],
        "headers": ["식", "의미", "서브쿼리 0행일 때"],
        "rows": [
            ["> ANY (…)", "최솟값보다 크다", "FALSE"],
            ["< ANY (…)", "최댓값보다 작다", "FALSE"],
            ["= ANY (…)", "IN과 같음", "FALSE"],
            ["> ALL (…)", "최댓값보다 크다", "TRUE"],
            ["< ALL (…)", "최솟값보다 작다", "TRUE"],
        ],
        "takeaway": "ALL은 0행이면 참(공허한 참), ANY는 거짓.",
    },
    {
        "id": "cmp_join_syntax",
        "title": "ON vs USING vs NATURAL JOIN",
        "concepts": ["ON", "USING", "NATURAL JOIN", "INNER JOIN"],
        "headers": ["구분", "ON", "USING", "NATURAL JOIN"],
        "rows": [
            ["조인 컬럼 지정", "임의 조건", "같은 이름 컬럼 명시", "모든 같은 이름 컬럼 자동"],
            ["컬럼명이 달라도", "가능", "불가", "불가"],
            ["조인 컬럼에 별칭 접두사", "필요", "불가(Oracle)", "불가"],
            ["결과의 조인 컬럼", "양쪽 모두", "한 번", "한 번"],
        ],
        "takeaway": "USING/NATURAL JOIN의 조인 컬럼에 e.deptno처럼 별칭을 붙이면 오류(Oracle).",
    },
    {
        "id": "cmp_insert_all_first",
        "title": "INSERT ALL vs INSERT FIRST",
        "concepts": ["INSERT ALL", "INSERT FIRST"],
        "headers": ["구분", "INSERT ALL", "INSERT FIRST"],
        "rows": [
            ["조건 평가", "모든 WHEN 평가", "위에서부터 평가"],
            ["실행되는 INTO", "만족하는 모든 WHEN", "처음 만족하는 WHEN 하나"],
            ["한 행이 여러 테이블에", "가능", "불가(ELSE 포함 하나)"],
        ],
        "takeaway": "CASE처럼 '첫 일치'는 FIRST, '모든 일치'는 ALL.",
    },
    {
        "id": "cmp_tcl",
        "title": "COMMIT vs ROLLBACK vs SAVEPOINT",
        "concepts": ["COMMIT", "ROLLBACK", "SAVEPOINT", "ROLLBACK TO SAVEPOINT", "TCL"],
        "headers": ["명령", "효과", "트랜잭션"],
        "rows": [
            ["COMMIT", "변경 영구 반영, 잠금 해제", "종료"],
            ["ROLLBACK", "마지막 COMMIT 이후 전부 취소", "종료"],
            ["SAVEPOINT s", "저장점 표시", "계속"],
            ["ROLLBACK TO s", "s 이후 변경만 취소", "계속"],
        ],
        "takeaway": "ROLLBACK TO 후에는 반드시 COMMIT/ROLLBACK으로 트랜잭션을 끝내야 한다.",
    },
    {
        "id": "cmp_sql_kinds",
        "title": "DML vs DDL vs DCL vs TCL",
        "concepts": ["DML", "DDL", "DCL", "TCL"],
        "headers": ["분류", "명령", "Oracle ROLLBACK"],
        "rows": [
            ["DML", "SELECT*, INSERT, UPDATE, DELETE, MERGE", "가능(COMMIT 전)"],
            ["DDL", "CREATE, ALTER, DROP, TRUNCATE, RENAME", "불가(자동 커밋)"],
            ["DCL", "GRANT, REVOKE", "불가(자동 커밋)"],
            ["TCL", "COMMIT, ROLLBACK, SAVEPOINT", "-"],
        ],
        "takeaway": "* SELECT를 DQL로 따로 분류하기도 한다. TRUNCATE는 DML이 아니라 DDL.",
    },
    {
        "id": "cmp_normal_forms",
        "title": "1NF vs 2NF vs 3NF vs BCNF",
        "concepts": ["1NF", "2NF", "3NF", "BCNF", "부분 함수 종속", "이행 함수 종속", "정규화"],
        "headers": ["정규형", "제거 대상", "판별 질문"],
        "rows": [
            ["1NF", "반복 그룹·다중값", "모든 값이 원자값인가?"],
            ["2NF", "부분 함수 종속", "복합 PK의 일부만으로 결정되는 속성이 있는가?"],
            ["3NF", "이행 함수 종속", "일반 속성이 다른 일반 속성을 결정하는가?"],
            ["BCNF", "후보키가 아닌 결정자", "모든 결정자가 후보키인가?"],
        ],
        "takeaway": "PK가 단일 컬럼이면 부분 함수 종속은 생길 수 없다.",
    },
    {
        "id": "cmp_normalize_denormalize",
        "title": "정규화 vs 반정규화",
        "concepts": ["정규화", "반정규화"],
        "headers": ["구분", "정규화", "반정규화"],
        "rows": [
            ["목적", "중복·이상현상 제거, 무결성", "조회 성능, 단순화"],
            ["방법", "분해", "중복·통합·분리"],
            ["부작용", "조인 증가(조회 성능 저하 가능)", "무결성 저하, 입력·수정 비용 증가"],
        ],
        "takeaway": "반정규화는 다른 성능 수단(인덱스·뷰·클러스터링)을 먼저 검토한 뒤 적용한다.",
    },
    {
        "id": "cmp_schema",
        "title": "외부 vs 개념 vs 내부 스키마",
        "concepts": ["외부 스키마", "개념 스키마", "내부 스키마", "3단계 스키마", "데이터 독립성"],
        "headers": ["스키마", "관점", "개수", "독립성"],
        "rows": [
            ["외부", "사용자/응용 뷰", "여러 개", "외부↔개념: 논리적 독립성"],
            ["개념", "전체 통합 구조", "1개", "-"],
            ["내부", "물리 저장", "1개", "개념↔내부: 물리적 독립성"],
        ],
        "takeaway": "모든 사용자 관점을 통합한 것은 '개념 스키마'.",
    },
    {
        "id": "cmp_entity_time",
        "title": "기본 vs 중심 vs 행위 엔터티",
        "concepts": ["기본 엔터티", "중심 엔터티", "행위 엔터티", "엔터티 발생시점 분류"],
        "headers": ["구분", "발생", "예"],
        "rows": [
            ["기본(키)", "독립적으로 생성, 자신의 주식별자", "고객, 상품, 사원, 부서"],
            ["중심", "기본 엔터티로부터 발생, 업무 중심", "주문, 계약, 청구"],
            ["행위", "2개 이상 부모, 자주 변경·증가", "주문상세, 변경이력"],
        ],
        "takeaway": "'이력/상세'는 거의 항상 행위 엔터티.",
    },
    {
        "id": "cmp_attr_kind",
        "title": "기본 vs 설계 vs 파생 속성",
        "concepts": ["기본 속성", "설계 속성", "파생 속성", "속성 분류"],
        "headers": ["구분", "정의", "예"],
        "rows": [
            ["기본", "업무에서 바로 도출", "제품명, 단가"],
            ["설계", "설계 시 규칙화·유일성 위해 추가", "제품코드, 일련번호"],
            ["파생", "다른 속성으로 계산", "총액, 잔액"],
        ],
        "takeaway": "파생 속성은 정합성 부담 때문에 최소화.",
    },
    {
        "id": "cmp_round_trunc",
        "title": "ROUND vs TRUNC vs CEIL vs FLOOR",
        "concepts": ["ROUND", "TRUNC", "CEIL", "FLOOR"],
        "headers": ["함수", "-1.5", "1.5", "123.456 (자릿수)"],
        "rows": [
            ["ROUND", "-2", "2", "ROUND(123.456, 1) = 123.5"],
            ["TRUNC", "-1", "1", "TRUNC(123.456, 1) = 123.4"],
            ["CEIL", "-1", "2", "자릿수 인자 없음"],
            ["FLOOR", "-2", "1", "자릿수 인자 없음"],
        ],
        "takeaway": "음수에서 CEIL은 0 쪽, FLOOR는 음의 무한대 쪽.",
    },
    {
        "id": "cmp_trim",
        "title": "LTRIM vs RTRIM vs TRIM",
        "concepts": ["LTRIM", "RTRIM", "TRIM"],
        "headers": ["함수", "제거 위치", "제거 대상 지정"],
        "rows": [
            ["LTRIM(s, set)", "왼쪽", "문자 집합(여러 문자)"],
            ["RTRIM(s, set)", "오른쪽", "문자 집합(여러 문자)"],
            ["TRIM([LEADING|TRAILING|BOTH] c FROM s)", "기본 양쪽", "문자 1개(Oracle)"],
        ],
        "takeaway": "LTRIM('xxyAxy', 'xy') = 'Axy' — 집합에 속한 문자가 나오는 동안 계속 제거.",
    },
    {
        "id": "cmp_case_decode",
        "title": "CASE vs DECODE",
        "concepts": ["CASE", "DECODE"],
        "headers": ["구분", "CASE", "DECODE"],
        "rows": [
            ["표준", "ANSI (Oracle, SQL Server)", "Oracle 전용"],
            ["비교", "범위·조건식 가능", "등가 비교만"],
            ["NULL = NULL", "일치하지 않음(Simple CASE)", "일치로 봄"],
            ["기본값 생략", "NULL", "NULL"],
        ],
        "takeaway": "범위 조건(>=)은 DECODE로 직접 못 쓴다.",
    },
    {
        "id": "cmp_hier_direction",
        "title": "순방향 vs 역방향 계층 전개",
        "concepts": ["순방향 계층 전개", "역방향 계층 전개", "PRIOR", "CONNECT BY"],
        "headers": ["구분", "CONNECT BY", "방향", "예"],
        "rows": [
            ["순방향", "PRIOR 자식키(PK) = 부모키(FK)", "부모 → 자식 (Top-Down)", "CONNECT BY PRIOR empno = mgr"],
            ["역방향", "PRIOR 부모키(FK) = 자식키(PK)", "자식 → 부모 (Bottom-Up)", "CONNECT BY PRIOR mgr = empno"],
        ],
        "takeaway": "PRIOR가 붙은 쪽이 '이미 방문한(직전) 행'이다.",
    },
    {
        "id": "cmp_hier_filter",
        "title": "계층형 질의: WHERE vs CONNECT BY 조건",
        "concepts": ["WHERE 후 계층 필터", "계층형 질의 WHERE 후필터", "CONNECT BY", "START WITH"],
        "headers": ["조건 위치", "적용 시점", "제외된 노드의 자식"],
        "rows": [
            ["START WITH", "루트 선택", "-"],
            ["CONNECT BY", "전개 중", "함께 제외(가지치기)"],
            ["WHERE", "전개 후", "남음(행만 제거)"],
        ],
        "takeaway": "부서 전체 가지를 자르려면 CONNECT BY, 특정 행만 숨기려면 WHERE.",
    },
    {
        "id": "cmp_grant_admin",
        "title": "WITH GRANT OPTION vs WITH ADMIN OPTION",
        "concepts": ["GRANT OPTION", "권한 연쇄 회수", "객체 권한", "시스템 권한", "REVOKE"],
        "headers": ["옵션", "대상 권한", "재부여", "회수 시 연쇄"],
        "rows": [
            ["WITH GRANT OPTION", "객체 권한", "가능", "연쇄 회수됨"],
            ["WITH ADMIN OPTION", "시스템 권한·ROLE", "가능", "연쇄 회수 안 됨"],
        ],
        "takeaway": "A→B→C로 재부여 후 A가 B의 객체 권한을 회수하면 C의 권한도 사라진다.",
    },
    {
        "id": "cmp_char_varchar",
        "title": "CHAR vs VARCHAR",
        "concepts": ["CHAR", "VARCHAR", "CHAR 후행 공백", "문자 비교"],
        "headers": ["구분", "CHAR(n)", "VARCHAR(n)"],
        "rows": [
            ["길이", "고정(공백 채움)", "가변"],
            ["'AB' 저장 시 LENGTH (n=5)", "5", "2"],
            ["비교 방식", "공백 패딩 비교", "비패딩 비교"],
        ],
        "takeaway": "CHAR끼리는 'A' = 'A  '가 참, VARCHAR가 섞이면 거짓.",
    },
    {
        "id": "cmp_identifier_kind",
        "title": "식별자 분류",
        "concepts": ["주식별자", "보조 식별자", "내부 식별자", "외부 식별자", "단일 식별자", "복합 식별자", "본질 식별자", "인조 식별자"],
        "headers": ["기준", "분류"],
        "rows": [
            ["대표성", "주식별자 / 보조 식별자"],
            ["스스로 생성 여부", "내부 식별자 / 외부 식별자"],
            ["속성 수", "단일 식별자 / 복합 식별자"],
            ["대체 여부", "본질 식별자 / 인조 식별자"],
        ],
        "takeaway": "기준과 분류 이름을 짝짓는 문제가 단골.",
    },
    {
        "id": "cmp_view_table",
        "title": "VIEW vs 테이블 vs 인라인 뷰",
        "concepts": ["VIEW", "인라인 뷰", "WITH 절"],
        "headers": ["구분", "저장", "재사용", "정의 위치"],
        "rows": [
            ["테이블", "데이터 저장", "가능", "DDL"],
            ["VIEW", "SELECT 정의만 저장", "가능(객체)", "CREATE VIEW"],
            ["인라인 뷰", "저장 안 함", "해당 문장 1회", "FROM 절"],
            ["WITH 절(CTE)", "저장 안 함", "해당 문장 안 여러 번", "문장 앞 WITH"],
        ],
        "takeaway": "VIEW는 데이터를 저장하지 않는 가상 테이블.",
    },
]
