"""Content for Stage 4–6 (관계 결합 / 집계 / 고급 조회)."""

DEFS = {
    # JN1 JOIN
    "JOIN": "두 개 이상의 테이블을 조인 조건으로 연결해 하나의 결과 집합을 만드는 연산.",
    "CARTESIAN PRODUCT": "조인 조건이 없을 때 두 테이블 행의 모든 조합(M×N행)이 만들어지는 결과.",
    "CROSS JOIN": "카티션 곱을 명시적으로 수행하는 ANSI 조인. ON 절을 쓰지 않는다.",
    "EQUI JOIN": "등호(=) 조건으로 두 테이블을 연결하는 조인.",
    "NON-EQUI JOIN": "= 이외의 조건(BETWEEN, >, < 등)으로 연결하는 조인(예: 급여 등급 테이블).",
    "INNER JOIN": "조인 조건을 만족하는 행만 반환하는 조인(JOIN의 기본값).",
    "N-1 조인 조건": "N개 테이블을 빠짐없이 연결하려면 최소 N-1개의 조인 조건이 필요하다는 규칙.",
    "모호한 컬럼": "조인한 여러 테이블에 같은 이름의 컬럼이 있을 때 테이블명/별칭 없이 쓰면 발생하는 오류(column ambiguously defined).",
    "셀프 조인": "같은 테이블을 서로 다른 별칭으로 두 번 사용해 자기 자신과 조인하는 것(예: 사원-관리자).",
    "조인 중복 증폭": "1:M 조인 후 1쪽 값을 집계하면 그 값이 M번 반복되어 SUM 등이 부풀려지는 현상.",
    "복합 FK 조인": "여러 컬럼으로 된 PK/FK를 조인할 때 모든 컬럼을 조인 조건에 걸어야 하는 규칙(일부만 걸면 중복 발생).",
    "ON": "ANSI JOIN에서 조인 조건을 명시하는 절. 컬럼 이름이 달라도 쓸 수 있고 임의 조건을 넣을 수 있다.",
    "USING": "같은 이름 컬럼으로 등가 조인하는 ANSI 문법. USING 컬럼에는 테이블 별칭을 붙일 수 없다(Oracle).",
    "NATURAL JOIN": "두 테이블의 모든 동일 이름 컬럼으로 자동 등가 조인. 해당 컬럼에 별칭 접두사를 쓸 수 없고 ON/USING과 함께 쓸 수 없다.",
    "OUTER JOIN": "조인 조건에 맞지 않는 행도 보존 테이블 기준으로 남기고, 반대쪽 컬럼은 NULL로 채우는 조인.",
    "보존 테이블": "OUTER JOIN에서 모든 행이 결과에 남는 쪽 테이블(LEFT의 왼쪽, RIGHT의 오른쪽, FULL은 양쪽).",
    "LEFT OUTER JOIN": "왼쪽 테이블의 모든 행을 보존하고 오른쪽에 매칭이 없으면 NULL로 채운다.",
    "RIGHT OUTER JOIN": "오른쪽 테이블의 모든 행을 보존하고 왼쪽에 매칭이 없으면 NULL로 채운다.",
    "FULL OUTER JOIN": "양쪽 테이블의 모든 행을 보존(LEFT 결과 ∪ RIGHT 결과, 중복 제거).",
    "Oracle (+) OUTER JOIN": "Oracle 전통 문법. 데이터가 없어 NULL로 채워질 쪽 컬럼에 (+)를 붙인다. A.id = B.id(+)는 A LEFT OUTER JOIN B.",
    "연속 OUTER JOIN": "OUTER JOIN 결과에 이어서 다른 테이블을 조인하는 것. 뒤에 INNER JOIN을 걸면 보존된 행이 사라질 수 있다.",
    "OUTER JOIN 조건 위치": "비보존 테이블 조건을 ON에 두면 조인 전 필터(보존 행 유지), WHERE에 두면 조인 후 필터(보존 행 제거 → 사실상 INNER JOIN)가 된다.",
    "ON vs WHERE": "ON은 조인 조건(OUTER JOIN 보존 행을 없애지 않음), WHERE는 조인 결과 전체에 대한 후필터라는 차이.",
    # SQ6 서브쿼리
    "서브쿼리": "SQL 문장 안에 포함된 SELECT 문. 위치(WHERE/FROM/SELECT)와 결과 행 수, 외부 참조 여부로 분류한다.",
    "단일행 서브쿼리": "결과가 1행 이하인 서브쿼리. 단일행 비교 연산자(=, <, > 등)와 함께 쓰며 2행 이상 반환되면 오류.",
    "다중행 서브쿼리": "결과가 여러 행인 서브쿼리. IN, ANY, ALL, EXISTS 같은 다중행 연산자와 함께 쓴다.",
    "스칼라 서브쿼리": "SELECT 절 등에서 1행 1열 값을 반환하는 서브쿼리. 결과가 없으면 NULL, 2행 이상이면 오류.",
    "상관 서브쿼리": "메인쿼리의 컬럼을 참조하는 서브쿼리. 메인쿼리 행마다 반복 평가된다.",
    "인라인 뷰": "FROM 절에 쓰인 서브쿼리. 임시 테이블처럼 쓰이며 내부에 ORDER BY를 쓸 수 있다.",
    "ANY": "서브쿼리 결과 중 하나라도 조건을 만족하면 TRUE. > ANY는 '최솟값보다 크다'.",
    "ALL": "서브쿼리 결과 모두에 대해 조건을 만족해야 TRUE. > ALL은 '최댓값보다 크다'.",
    "EXISTS": "서브쿼리 결과가 1행이라도 있으면 TRUE. 값이 아니라 존재 여부만 판단한다.",
    "NOT EXISTS": "서브쿼리 결과가 하나도 없으면 TRUE. 결과에 NULL이 있어도 NOT IN과 달리 정상 동작한다.",
    "서브쿼리 ORDER BY 제한": "WHERE 절 서브쿼리 안에는 ORDER BY를 쓸 수 없다(인라인 뷰는 가능). SQL Server는 TOP 없이 서브쿼리/뷰에 ORDER BY 불가.",
    "WITH 절": "메인 쿼리 앞에 이름 붙은 서브쿼리 블록을 정의하는 구문(Subquery Factoring). 여러 번 참조할 수 있다.",
    "CTE": "Common Table Expression. WITH 절로 정의한 이름 있는 임시 결과 집합.",
    "재귀 CTE": "앵커 멤버 UNION ALL 재귀 멤버(자기 자신 참조)로 계층 데이터를 전개하는 CTE. SQL Server의 계층 조회 방법(Oracle도 지원).",
    # SQ7 집합 연산자
    "집합 연산자": "여러 SELECT 결과를 UNION / UNION ALL / INTERSECT / MINUS(EXCEPT)로 결합하는 연산자.",
    "UNION": "합집합. 결과에서 중복 행을 제거한다.",
    "UNION ALL": "합집합. 중복을 제거하지 않고 모두 반환한다(정렬·중복 제거 비용 없음).",
    "INTERSECT": "교집합. 양쪽에 모두 있는 행(중복 제거).",
    "MINUS": "Oracle의 차집합. 첫 결과에서 두 번째 결과에 있는 행을 뺀다(중복 제거).",
    "EXCEPT": "ANSI/SQL Server의 차집합(Oracle MINUS와 같은 의미).",
    "집합 연산자 컬럼 호환성": "각 SELECT의 컬럼 수가 같고 대응 컬럼의 자료형이 호환되어야 한다. 결과 컬럼명은 첫 SELECT 기준.",
    "집합 연산자 ORDER BY": "ORDER BY는 마지막 SELECT 뒤에 한 번만 쓰며, 첫 SELECT의 컬럼명·별칭 또는 위치 번호로 지정한다.",
    "집합 연산자 우선순위": "Oracle은 모든 집합 연산자의 우선순위가 같아 위에서 아래로 수행하고, SQL Server(ANSI)는 INTERSECT를 먼저 수행한다.",
    # AG1 집계
    "집계 함수": "여러 행을 하나의 값으로 요약하는 함수(COUNT, SUM, AVG, MIN, MAX). COUNT(*)를 제외하면 NULL을 무시한다.",
    "COUNT": "행 수를 센다. COUNT(*)는 전체 행, COUNT(열)은 NULL이 아닌 행, COUNT(DISTINCT 열)은 NULL 제외 고유값 수.",
    "COUNT(*)": "결과 행 전체의 수(NULL 포함). 행이 없으면 0.",
    "COUNT(열)": "해당 열이 NULL이 아닌 행의 수.",
    "COUNT(DISTINCT)": "NULL을 제외하고 중복을 제거한 고유값의 개수.",
    "SUM": "NULL을 제외한 값의 합계. 대상이 없으면 NULL.",
    "AVG": "NULL을 제외한 값의 평균(= SUM(열) / COUNT(열)). NULL을 0으로 보려면 AVG(NVL(열, 0)).",
    "MIN": "NULL을 제외한 최솟값. 문자·날짜에도 사용 가능.",
    "MAX": "NULL을 제외한 최댓값. 문자·날짜에도 사용 가능.",
    "NULL 집계": "집계 함수는 NULL을 제외하고 계산하며, 대상 값이 모두 NULL이면 결과도 NULL(COUNT는 0).",
    "공집합 집계": "대상 행이 0개일 때 GROUP BY 없는 집계는 1행(COUNT=0, SUM/AVG/MIN/MAX=NULL)을, GROUP BY가 있으면 0행을 반환한다.",
    "SUM(열1+열2) vs SUM(열1)+SUM(열2)": "행 단위 열1+열2가 NULL이면 그 행이 통째로 빠지므로 두 식의 결과가 다를 수 있다.",
    "GROUP BY": "지정한 컬럼 값이 같은 행끼리 그룹으로 묶어 그룹당 한 행으로 집계하는 절.",
    "GROUP BY 확장": "GROUP BY에 ROLLUP, CUBE, GROUPING SETS를 써서 소계·총계를 함께 만드는 문법(그룹함수 확장과 같은 범주).",
    "그룹함수 확장": "ROLLUP, CUBE, GROUPING SETS와 GROUPING 함수로 여러 그룹 수준의 집계를 한 번에 만드는 기능.",
    "GROUP BY 후 ORDER BY 제약": "GROUP BY가 있으면 ORDER BY에는 GROUP BY 표현식, 집계 함수, 상수만 쓸 수 있다.",
    "HAVING": "GROUP BY로 만든 그룹에 조건을 거는 그룹 필터. 집계 함수를 사용할 수 있다.",
    "HAVING without GROUP BY": "GROUP BY 없이 HAVING을 쓰면 테이블 전체가 하나의 그룹으로 취급된다.",
    "WHERE 집계함수 사용 불가": "WHERE는 그룹화 이전에 행 단위로 평가되므로 집계 함수를 쓸 수 없다(HAVING을 사용).",
    "그룹 내 비율 함수": "윈도우 함수 중 비율·분포를 계산하는 함수 묶음 — RATIO_TO_REPORT, PERCENT_RANK, CUME_DIST, NTILE.",
    # AG2
    "ROLLUP": "ROLLUP(a, b)는 (a,b) → (a) → () 순으로 계층적 소계와 총계를 만든다. 인자 순서가 결과에 영향을 준다(n개 → n+1 수준).",
    "CUBE": "CUBE(a, b)는 (a,b), (a), (b), () 모든 조합의 소계를 만든다(2^n 수준). 인자 순서와 무관.",
    "GROUPING SETS": "GROUPING SETS(a, b)는 나열한 그룹별 집계만 따로 만든다((a), (b)). 총계는 ()를 넣어야 하고 순서와 무관.",
    "GROUPING": "GROUPING(col)은 그 행이 col에 대해 소계/총계로 집계된 행이면 1, 일반 행이면 0을 반환.",
    "전체 총계 ()": "GROUPING SETS 안의 빈 괄호 ()는 전체 총계 그룹을 뜻한다.",
    # AG3 윈도우
    "윈도우 함수": "행 수를 줄이지 않고 OVER 절로 정의한 윈도우(행 집합) 안에서 순위·집계·행 이동 값을 계산하는 함수(분석 함수).",
    "OVER 절": "OVER([PARTITION BY …] [ORDER BY …] [ROWS|RANGE 프레임]) — 윈도우 함수의 계산 범위를 정의하는 절.",
    "PARTITION BY": "윈도우를 그룹으로 나누는 절. GROUP BY와 달리 행을 축약하지 않는다.",
    "순위 함수": "그룹 내 순위 함수 — RANK, DENSE_RANK, ROW_NUMBER. OVER(ORDER BY …)가 필요하다.",
    "RANK": "동순위에는 같은 순위를 주고 그다음 순위를 건너뛴다(1, 2, 2, 4).",
    "DENSE_RANK": "동순위에는 같은 순위를 주고 다음 순위를 건너뛰지 않는다(1, 2, 2, 3).",
    "ROW_NUMBER": "동순위와 상관없이 고유한 연속 번호를 준다(1, 2, 3, 4).",
    "행 순서 함수": "그룹 내 행 순서 함수 — FIRST_VALUE, LAST_VALUE, LAG, LEAD.",
    "LAG": "LAG(열, n, 기본값) — 현재 행 기준 n행 이전 행의 값(기본 n=1, 없으면 기본값/NULL).",
    "LEAD": "LEAD(열, n, 기본값) — 현재 행 기준 n행 이후 행의 값.",
    "FIRST_VALUE": "윈도우 프레임의 첫 행 값.",
    "LAST_VALUE": "윈도우 프레임의 마지막 행 값. 기본 프레임에서는 현재 행(또는 동순위 마지막) 값이 나온다.",
    "RATIO_TO_REPORT": "RATIO_TO_REPORT(열) OVER(...) — 파티션 합계 대비 현재 값의 비율(Oracle).",
    "PERCENT_RANK": "(RANK - 1) / (파티션 행 수 - 1). 첫 행 0, 마지막 행 1.",
    "CUME_DIST": "정렬 기준으로 현재 값 이하인 행 수 / 파티션 전체 행 수(누적 분포, 0 초과 1 이하).",
    "NTILE": "NTILE(n) — 파티션을 n개 그룹으로 나눠 그룹 번호를 부여. 나누어떨어지지 않으면 앞 그룹부터 1개씩 더 배정.",
    "MAX() OVER(PARTITION BY)": "그룹 내 최댓값을 각 행 옆에 붙이는 윈도우 집계(그룹 내 집계 함수). 행 수는 그대로다.",
    "ROWS/RANGE 프레임": "윈도우 안에서 계산에 포함할 범위. ROWS는 물리적 행 수, RANGE는 ORDER BY 값의 논리적 범위.",
    "ROWS": "물리적 행 개수 기준 프레임.",
    "RANGE": "ORDER BY 값 기준 프레임. 같은 정렬 값(동료 행)은 함께 포함된다.",
    "CURRENT ROW": "프레임 경계로 현재 행(RANGE에서는 현재 행과 같은 값을 가진 행들까지).",
    "UNBOUNDED PRECEDING": "프레임 시작을 파티션의 첫 행으로 지정.",
    "UNBOUNDED FOLLOWING": "프레임 끝을 파티션의 마지막 행으로 지정.",
    "PRECEDING/FOLLOWING": "n PRECEDING은 현재 기준 n행(또는 값) 이전, n FOLLOWING은 이후를 프레임 경계로 지정.",
    "ROWS PRECEDING/FOLLOWING": "ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING처럼 현재 행의 앞뒤 n행을 프레임으로 지정.",
    "RANGE BETWEEN": "RANGE BETWEEN 시작 AND 끝 형태로 정렬 값 범위를 프레임으로 지정.",
    "RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW": "윈도우에 ORDER BY가 있고 프레임을 생략했을 때의 기본 프레임. 같은 값 행들이 함께 누적된다.",
    "윈도우 RANGE 프레임": "RANGE BETWEEN 100 PRECEDING AND 100 FOLLOWING처럼 정렬 키 값의 범위로 정한 프레임.",
    "GROUP BY 후 윈도우 함수": "윈도우 함수는 GROUP BY 결과(그룹 행) 위에서 계산되므로 집계 결과로 순위를 매길 수 있다(RANK() OVER(ORDER BY SUM(sal))).",
    # AG4 Top-N
    "Top-N": "정렬 후 상위 N개 행만 조회하는 쿼리 패턴.",
    "ROWNUM": "Oracle 의사 컬럼. 결과 행에 1부터 순번을 부여하며 ORDER BY보다 먼저 부여된다.",
    "TOP": "SQL Server의 Top-N 문법. SELECT TOP(n) [PERCENT] [WITH TIES] …",
    "FETCH FIRST": "ANSI 표준 Top-N(Oracle 12c+). ORDER BY … FETCH FIRST n ROWS ONLY | WITH TIES. SQL Server는 OFFSET … FETCH NEXT.",
    "LIMIT": "MySQL/PostgreSQL의 Top-N 문법. Oracle·SQL Server는 지원하지 않는다.",
    "WITH TIES": "마지막 순위와 같은 정렬 값을 가진 행까지 함께 반환하는 옵션(ORDER BY 필수).",
    # AG5
    "PIVOT·UNPIVOT": "행을 열로(PIVOT), 열을 행으로(UNPIVOT) 재구성하는 문법.",
    "PIVOT": "PIVOT(집계함수 FOR 열 IN (값 목록)) — 행 값을 열로 펼친다. PIVOT에 쓰이지 않은 나머지 컬럼은 암묵적으로 GROUP BY 된다.",
    "UNPIVOT": "여러 열을 (이름, 값) 행으로 바꾼다. 기본적으로 값이 NULL인 행은 제외된다(INCLUDE NULLS로 포함).",
    # HQ1 계층형
    "계층형 질의": "자기참조 구조 데이터를 트리 형태로 조회하는 질의(Oracle: START WITH … CONNECT BY).",
    "START WITH": "계층 전개의 루트(시작) 행을 지정하는 조건.",
    "CONNECT BY": "부모-자식 연결 조건. PRIOR로 부모(직전) 행의 컬럼을 표시한다.",
    "PRIOR": "직전(부모) 행의 컬럼 값을 가리키는 연산자. 어느 쪽 컬럼에 붙느냐로 전개 방향이 결정된다.",
    "순방향 계층 전개": "부모 → 자식(Top-Down) 전개. CONNECT BY PRIOR 자식키(PK) = 부모키(FK), 예: CONNECT BY PRIOR EMPNO = MGR.",
    "역방향 계층 전개": "자식 → 부모(Bottom-Up) 전개. CONNECT BY PRIOR 부모키(FK) = 자식키(PK), 예: CONNECT BY PRIOR MGR = EMPNO.",
    "LEVEL": "계층 깊이를 나타내는 의사 컬럼. 루트 = 1.",
    "ORDER SIBLINGS BY": "계층 구조를 유지하면서 같은 부모를 가진 형제끼리 정렬.",
    "NOCYCLE": "데이터에 순환이 있어도 오류 없이 전개하고 순환 지점에서 멈추게 하는 옵션(CONNECT BY NOCYCLE).",
    "CONNECT_BY_ISCYCLE": "현재 행의 자식이 동시에 조상이면(순환) 1, 아니면 0. NOCYCLE과 함께만 사용 가능.",
    "CONNECT_BY_ISLEAF": "현재 행이 리프(자식 없음)이면 1, 아니면 0.",
    "CONNECT_BY_ROOT": "현재 행이 속한 계층의 루트 행 컬럼 값을 반환하는 연산자.",
    "SYS_CONNECT_BY_PATH": "SYS_CONNECT_BY_PATH(열, 구분자) — 루트부터 현재 행까지의 경로를 문자열로 반환.",
    "WHERE 후 계층 필터": "계층형 질의의 WHERE는 계층 전개(START WITH/CONNECT BY)가 끝난 뒤 개별 행을 필터링한다.",
    "계층형 질의 WHERE 후필터": "WHERE로 제외된 행의 자식은 결과에 남는다(가지치기가 아님). 가지 전체를 자르려면 CONNECT BY 조건에 넣는다.",
    "계층 전개 NULL 종료": "부모 키가 NULL이거나 더 이상 연결될 행이 없으면 전개가 끝난다(루트 판별에 MGR IS NULL 사용).",
}

RULES = {
    "JOIN": dict(
        why="정규화로 분리된 테이블을 다시 결합하는 핵심 연산. INNER/OUTER/CROSS/NATURAL과 조건 위치 문제로 이어진다.",
        rules=["조인 조건이 없으면 카티션 곱", "N개 테이블 → 최소 N-1개 조인 조건", "같은 이름 컬럼은 테이블명/별칭으로 구분"],
    ),
    "CROSS JOIN": dict(rules=["M행 × N행 = M×N행", "ON 절 사용 불가"], traps=["조인 조건을 빠뜨린 일반 조인도 카티션 곱이 된다."]),
    "NATURAL JOIN": dict(
        rules=["모든 동일 이름 컬럼으로 등가 조인", "공통 컬럼은 결과에 한 번만 나옴"],
        traps=["NATURAL JOIN의 공통 컬럼에 테이블 별칭 접두사(e.deptno)를 붙이면 오류(Oracle).",
               "NATURAL JOIN과 ON/USING을 함께 쓸 수 없다.", "공통 컬럼이 여러 개면 모두 조건이 된다."],
    ),
    "USING": dict(
        rules=["USING(col) = 같은 이름 컬럼 등가 조인"],
        traps=["USING에 쓴 컬럼은 SELECT에서 별칭 접두사를 붙일 수 없다(Oracle)."],
    ),
    "OUTER JOIN": dict(
        why="보존 테이블, NULL 채움, 조건 위치(ON vs WHERE)가 한 묶음으로 현행 회차에 반복 출제된다.",
        rules=["LEFT: 왼쪽 보존, RIGHT: 오른쪽 보존, FULL: 양쪽 보존", "매칭되지 않은 쪽 컬럼은 NULL",
               "비보존 테이블 조건은 ON에 두어야 보존 행이 유지된다"],
        traps=["LEFT JOIN 후 WHERE 오른쪽.col = 값 → 사실상 INNER JOIN.", "COUNT(*)는 NULL 채운 행도 세고 COUNT(오른쪽.col)은 세지 않는다."],
        dialect=["Oracle (+)는 NULL로 채워질 쪽에 붙인다. FULL OUTER JOIN은 (+)로 표현할 수 없다."],
        examples=[{"sql": "SELECT d.deptno, e.ename\n  FROM dept d LEFT OUTER JOIN emp e\n    ON d.deptno = e.deptno;", "explain": "사원이 없는 부서(예: 40)도 ename = NULL로 나온다"}],
    ),
    "LEFT OUTER JOIN": dict(rules=["A LEFT JOIN B = A의 모든 행 + 매칭되는 B"], traps=["A LEFT JOIN B = B RIGHT JOIN A."]),
    "FULL OUTER JOIN": dict(rules=["LEFT ∪ RIGHT (중복 제거)"], traps=["Oracle (+)로는 양쪽에 동시에 붙일 수 없어 FULL OUTER JOIN을 표현 못 함."]),
    "Oracle (+) OUTER JOIN": dict(
        rules=["NULL이 채워질(데이터가 부족한) 쪽 컬럼에 (+)", "WHERE a.id = b.id(+) → a 보존(LEFT)"],
        traps=["(+)를 양쪽에 붙일 수 없다.", "비보존 테이블의 다른 조건에도 (+)를 붙여야 ON 조건처럼 동작한다(붙이지 않으면 후필터)."],
    ),
    "OUTER JOIN 조건 위치": dict(
        rules=["비보존 쪽 필터를 ON에 두면 조인 전 적용 → 보존 행 유지", "WHERE에 두면 조인 후 적용 → NULL 채운 행이 걸러짐"],
        examples=[{"sql": "-- (1) ON에 조건\nSELECT d.deptno, e.ename FROM dept d\n  LEFT JOIN emp e ON d.deptno = e.deptno AND e.job = 'CLERK';\n-- (2) WHERE에 조건\nSELECT d.deptno, e.ename FROM dept d\n  LEFT JOIN emp e ON d.deptno = e.deptno\n WHERE e.job = 'CLERK';",
                   "explain": "(1)은 모든 부서가 나오고 CLERK가 없는 부서는 NULL, (2)는 CLERK가 있는 부서만 나온다"}],
    ),
    "ON vs WHERE": dict(
        rules=["INNER JOIN에서는 ON과 WHERE 조건 결과가 같다", "OUTER JOIN에서는 결과가 달라진다"],
        traps=["'INNER JOIN에서도 ON과 WHERE의 결과가 다르다'는 틀린 설명."],
    ),
    "셀프 조인": dict(
        rules=["같은 테이블에 서로 다른 별칭 두 개", "자기참조 FK(MGR → EMPNO)로 연결"],
        examples=[{"sql": "SELECT e.ename AS 사원, m.ename AS 관리자\n  FROM emp e LEFT JOIN emp m\n    ON e.mgr = m.empno;", "explain": "관리자가 없는 사원(KING)도 남기려면 OUTER JOIN"}],
    ),
    "조인 중복 증폭": dict(
        rules=["1:M 조인 후 1쪽 컬럼 SUM은 M배가 된다", "집계 후 조인하거나 DISTINCT·서브쿼리로 회피"],
        traps=["부서 예산을 사원과 조인한 뒤 SUM하면 부서 사원 수만큼 부풀려진다."],
    ),
    "서브쿼리": dict(
        why="결과 행 수와 연산자의 짝(단일행↔=, 다중행↔IN/ANY/ALL/EXISTS)이 핵심. 현행 4회 출제.",
        rules=["WHERE: 단일행/다중행/다중컬럼 서브쿼리", "FROM: 인라인 뷰", "SELECT: 스칼라 서브쿼리",
               "메인쿼리 컬럼을 참조하면 상관 서브쿼리"],
        traps=["단일행 연산자(=)에 여러 행을 반환하는 서브쿼리 → 오류.", "WHERE 절 서브쿼리 안에는 ORDER BY 불가."],
    ),
    "단일행 서브쿼리": dict(traps=["결과가 0행이면 비교 결과는 UNKNOWN → 메인쿼리 0행(오류 아님)."]),
    "다중행 서브쿼리": dict(rules=["IN, ANY, ALL, EXISTS와 함께 사용"]),
    "스칼라 서브쿼리": dict(
        rules=["1행 1열만 반환", "결과가 없으면 NULL", "2행 이상이면 오류"],
        traps=["스칼라 서브쿼리는 OUTER JOIN처럼 동작한다(매칭이 없어도 메인 행은 남고 값은 NULL)."],
    ),
    "상관 서브쿼리": dict(
        rules=["메인쿼리 컬럼을 참조", "메인쿼리 행마다 서브쿼리 평가"],
        examples=[{"sql": "SELECT ename, sal FROM emp e\n WHERE sal > (SELECT AVG(sal) FROM emp WHERE deptno = e.deptno);", "explain": "자기 부서 평균보다 급여가 높은 사원"}],
    ),
    "ANY": dict(rules=["> ANY = 최솟값보다 큼", "< ANY = 최댓값보다 작음", "= ANY = IN"]),
    "ALL": dict(rules=["> ALL = 최댓값보다 큼", "< ALL = 최솟값보다 작음"],
                traps=["서브쿼리 결과가 0행이면 > ALL은 TRUE(모든 행 반환), > ANY는 FALSE(0행)."]),
    "EXISTS": dict(
        rules=["결과 존재 여부만 판단(SELECT 목록 내용은 무관)", "주로 상관 서브쿼리와 함께"],
        traps=["EXISTS (SELECT NULL FROM …)도 행이 있으면 TRUE."],
    ),
    "NOT EXISTS": dict(
        rules=["서브쿼리 결과가 없을 때 TRUE", "NULL이 섞여도 의도대로 동작"],
        traps=["NOT IN과 NOT EXISTS는 서브쿼리에 NULL이 있을 때 결과가 다르다."],
    ),
    "인라인 뷰": dict(rules=["FROM 절 서브쿼리", "ORDER BY 사용 가능 → ROWNUM Top-N 패턴에 필수"]),
    "WITH 절": dict(
        rules=["WITH 이름 AS (SELECT …) SELECT … FROM 이름", "여러 개 정의 시 쉼표로 구분", "메인 쿼리에서 여러 번 참조 가능"],
    ),
    "재귀 CTE": dict(
        rules=["WITH cte AS (앵커 SELECT UNION ALL 재귀 SELECT … JOIN cte …)", "재귀 멤버가 0행이면 종료", "SQL Server는 기본 최대 재귀 100(MAXRECURSION)"],
        dialect=["SQL Server는 CONNECT BY가 없어 계층 조회에 재귀 CTE를 쓴다.", "Oracle 11gR2+도 재귀 WITH를 지원하지만 시험에서는 CONNECT BY가 중심."],
    ),
    "집합 연산자": dict(
        why="UNION/UNION ALL 결과 행 수, 차집합 방언, ORDER BY 위치, 컬럼 호환성이 현행에서 반복 출제된다.",
        rules=["컬럼 수·자료형 호환 필요", "결과 컬럼명은 첫 SELECT 기준", "ORDER BY는 맨 마지막에 한 번"],
        traps=["UNION은 중복 제거, UNION ALL은 중복 유지 — 결과 행 수 계산 문제 단골.",
               "각 SELECT마다 ORDER BY를 붙이면 오류(마지막만 허용)."],
    ),
    "UNION": dict(rules=["중복 제거된 합집합"], traps=["UNION 결과가 정렬되어 보이는 것은 보장된 동작이 아니다 — 정렬은 ORDER BY로."]),
    "UNION ALL": dict(rules=["중복 포함 합집합", "가장 빠름(정렬·중복 제거 없음)"]),
    "INTERSECT": dict(rules=["양쪽 공통 행, 중복 제거"]),
    "MINUS": dict(rules=["A MINUS B = A에만 있는 행(중복 제거)", "순서를 바꾸면 결과가 다르다"], dialect=["Oracle: MINUS (21c부터 EXCEPT도 지원) / SQL Server·ANSI: EXCEPT"]),
    "EXCEPT": dict(dialect=["SQL Server·ANSI 표준 차집합. Oracle의 MINUS와 같은 의미."]),
    "집합 연산자 ORDER BY": dict(
        rules=["마지막 SELECT 뒤에 한 번만", "첫 SELECT의 컬럼명/별칭 또는 위치 번호 사용"],
        traps=["두 번째 SELECT에서 만든 별칭으로 ORDER BY 하면 오류."],
    ),
    "집합 연산자 우선순위": dict(
        rules=["Oracle: 모두 같은 우선순위, 위→아래 순서로 수행", "SQL Server/ANSI: INTERSECT가 먼저"],
        traps=["괄호 없이 섞어 쓰면 DBMS에 따라 결과가 다를 수 있다."],
    ),
    "집합 연산자 컬럼 호환성": dict(traps=["컬럼 수가 다르면 오류.", "결과 컬럼 이름은 첫 번째 SELECT의 이름/별칭을 따른다."]),
    "집계 함수": dict(
        why="COUNT/SUM/AVG의 NULL 처리와 공집합 반환값은 현행 함정 문제의 단골이다.",
        rules=["COUNT(*)를 제외한 집계 함수는 NULL을 무시", "GROUP BY 없이 쓰면 전체가 한 그룹", "WHERE에는 쓸 수 없고 HAVING·SELECT·ORDER BY에 사용"],
        traps=["SELECT 목록에 집계 함수와 GROUP BY에 없는 일반 컬럼을 함께 쓰면 오류."],
    ),
    "COUNT": dict(rules=["COUNT(*): NULL 포함 전체 행", "COUNT(열): NULL 제외", "COUNT(DISTINCT 열): NULL 제외 고유값"]),
    "COUNT(*)": dict(traps=["대상 행이 없으면 COUNT(*) = 0 (NULL 아님)."]),
    "COUNT(열)": dict(traps=["COUNT(comm)은 comm이 NULL인 행을 세지 않는다."]),
    "AVG": dict(
        rules=["AVG(col) = SUM(col) / COUNT(col)"],
        traps=["NULL을 0으로 간주한 평균 = AVG(NVL(col, 0)) = SUM(col) / COUNT(*) — AVG(col)과 다르다."],
        examples=[{"sql": "-- comm: 300, 500, NULL, NULL\nSELECT AVG(comm), AVG(NVL(comm,0)) FROM t;", "explain": "400 vs 200"}],
    ),
    "SUM": dict(traps=["행이 없으면 SUM = NULL. 0으로 받으려면 NVL(SUM(col), 0)."]),
    "공집합 집계": dict(
        rules=["GROUP BY 없음 + 0행 → 1행(COUNT 0, 나머지 NULL)", "GROUP BY 있음 + 0행 → 0행"],
        traps=["SELECT MAX(sal) FROM emp WHERE 1=2 는 NULL 한 행을 반환한다."],
    ),
    "SUM(열1+열2) vs SUM(열1)+SUM(열2)": dict(
        examples=[{"sql": "-- (a, b): (10, NULL), (20, 5)\nSUM(a + b)      → 25   -- 첫 행은 a+b가 NULL이라 제외\nSUM(a) + SUM(b) → 35   -- 30 + 5", "explain": "NULL의 위치에 따라 결과가 다르다"}],
    ),
    "GROUP BY": dict(
        why="집계·HAVING·ROLLUP·윈도우·PIVOT으로 이어지는 핵심 절.",
        rules=["SELECT의 비집계 컬럼은 모두 GROUP BY에 있어야 함", "GROUP BY 컬럼의 NULL은 하나의 그룹", "SELECT 별칭은 GROUP BY에 쓸 수 없음(Oracle)"],
        traps=["GROUP BY에 있는 컬럼을 SELECT에 꼭 넣을 필요는 없다(반대는 필수)."],
    ),
    "HAVING": dict(
        rules=["그룹에 대한 조건", "집계 함수 사용 가능", "논리적으로 GROUP BY 다음, SELECT 이전"],
        traps=["HAVING에 GROUP BY에 없는 일반 컬럼 조건을 쓰면 오류(집계 함수 또는 GROUP BY 컬럼만)."],
    ),
    "HAVING without GROUP BY": dict(
        rules=["전체 테이블이 하나의 그룹"],
        traps=["HAVING 조건이 거짓이면 결과는 0행(집계 1행도 나오지 않음)."],
    ),
    "WHERE 집계함수 사용 불가": dict(traps=["WHERE SUM(sal) > 1000 → 오류. HAVING SUM(sal) > 1000으로."]),
    "ROLLUP": dict(
        why="ROLLUP/CUBE/GROUPING SETS 결과 행 수 계산은 현행 6~7회 출제된 고빈도 문제다.",
        rules=["ROLLUP(a, b) → (a,b), (a), () 3수준", "인자 순서가 바뀌면 결과가 바뀐다", "소계 행의 집계되지 않은 컬럼은 NULL"],
        traps=["ROLLUP(a, b)에는 (b) 단독 소계가 없다.", "소계 행의 NULL과 실제 NULL 데이터는 GROUPING()으로 구분."],
    ),
    "CUBE": dict(rules=["CUBE(a, b) → (a,b), (a), (b), () 4수준", "인자 순서와 무관"],
                 traps=["CUBE는 ROLLUP보다 많은 소계를 만든다(2^n)."]),
    "GROUPING SETS": dict(
        rules=["GROUPING SETS(a, b) → (a), (b) 개별 집계만", "총계가 필요하면 () 추가", "인자 순서와 무관"],
        traps=["GROUPING SETS((a, b)) 와 GROUPING SETS(a, b)는 다르다."],
    ),
    "GROUPING": dict(rules=["소계/총계로 집계된 컬럼이면 1, 아니면 0"],
                     examples=[{"sql": "SELECT CASE GROUPING(job) WHEN 1 THEN 'ALL JOBS' ELSE job END AS job, SUM(sal)\n  FROM emp GROUP BY ROLLUP(job);", "explain": "총계 행에 'ALL JOBS' 표시"}]),
    "윈도우 함수": dict(
        why="순위 함수 비교, 프레임 기본값, LAG/LEAD, 결과 행 수 유지가 현행 7회 출제된 고빈도 영역.",
        rules=["행 수를 줄이지 않는다(집계 함수와의 차이)", "OVER 절이 반드시 필요", "논리적으로 SELECT 단계에서 계산 → WHERE에서 직접 사용 불가"],
        traps=["윈도우 함수 결과로 필터하려면 인라인 뷰로 감싸야 한다(WHERE RANK() … 불가).",
               "ORDER BY만 있고 프레임이 없으면 기본 프레임은 RANGE UNBOUNDED PRECEDING ~ CURRENT ROW (누적)."],
    ),
    "OVER 절": dict(
        rules=["OVER([PARTITION BY] [ORDER BY] [프레임])", "PARTITION BY 생략 → 전체가 하나의 파티션",
               "ORDER BY 생략 → 프레임은 파티션 전체", "ORDER BY 있고 프레임 생략 → RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"],
        traps=["SUM(sal) OVER(ORDER BY sal)은 누적합이고, 같은 sal 값은 같은 누적합을 가진다(RANGE)."],
    ),
    "PARTITION BY": dict(rules=["파티션별로 계산이 초기화", "행은 축약되지 않음"]),
    "순위 함수": dict(
        why="RANK·DENSE_RANK·ROW_NUMBER의 결과 비교는 현행에서 매우 자주 나오는 계산 문제다.",
        rules=["OVER(ORDER BY …) 필수", "PARTITION BY로 그룹별 순위"],
        traps=["ORDER BY 값이 같을 때 ROW_NUMBER의 순서는 보장되지 않는다(비결정적)."],
    ),
    "RANK": dict(rules=["동순위 동일, 다음 순위 건너뜀"],
                 traps=["동점이 2개면 다음 순위는 +2 (1, 2, 2, 4) — '3'이 나오지 않는다.", "OVER 절에 ORDER BY가 없으면 순위 함수는 오류."],
                 examples=[{"sql": "SELECT sal, RANK() OVER(ORDER BY sal DESC) FROM emp;", "explain": "sal 300, 200, 200, 100 → 1, 2, 2, 4"}]),
    "DENSE_RANK": dict(rules=["동순위 동일, 다음 순위 연속"], traps=["DENSE_RANK의 최댓값 = 서로 다른 정렬 값의 개수."], examples=[{"sql": "sal 300, 200, 200, 100", "explain": "→ 1, 2, 2, 3"}]),
    "ROW_NUMBER": dict(rules=["항상 고유 번호"], traps=["동점 행 사이의 번호 순서는 보장되지 않는다(정렬 키를 추가해야 결정적).", "ROWNUM(Oracle 의사 컬럼)과 ROW_NUMBER()(윈도우 함수)는 다르다."], examples=[{"sql": "sal 300, 200, 200, 100", "explain": "→ 1, 2, 3, 4"}]),
    "LAG": dict(rules=["LAG(열, n=1, 기본값=NULL)", "첫 행의 LAG는 기본값(없으면 NULL)"]),
    "LEAD": dict(rules=["LEAD(열, n=1, 기본값=NULL)", "마지막 행의 LEAD는 기본값(없으면 NULL)"]),
    "LAST_VALUE": dict(
        rules=["프레임의 마지막 행 값"],
        traps=["OVER(ORDER BY …)만 쓰면 프레임이 CURRENT ROW까지라 '현재 행' 값이 나온다. 파티션 마지막 값을 원하면 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING."],
    ),
    "ROWS/RANGE 프레임": dict(
        why="ROWS와 RANGE의 차이(동일 값 처리)와 기본 프레임은 현행 3회 이상 출제.",
        rules=["ROWS: 물리적 행 개수", "RANGE: 정렬 값 범위(동일 값 행은 함께 포함)", "기본(ORDER BY 있음): RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"],
        traps=["ROWS BETWEEN 1 PRECEDING AND CURRENT ROW는 '직전 1행 + 현재 행' 2행.", "RANGE는 ORDER BY 키가 하나여야 값 범위(n PRECEDING)를 쓸 수 있다."],
    ),
    "NTILE": dict(examples=[{"sql": "NTILE(3) OVER(ORDER BY sal) — 행 10개", "explain": "그룹 크기 4, 3, 3 (앞 그룹부터 1개씩 더)"}]),
    "PERCENT_RANK": dict(rules=["(RANK - 1) / (N - 1)"]),
    "CUME_DIST": dict(rules=["(현재 값 이하 행 수) / N", "동일 값은 같은 결과"]),
    "Top-N": dict(
        why="ROWNUM의 부여 시점, TOP/FETCH FIRST WITH TIES, DBMS별 문법 차이가 현행에서 반복 출제된다.",
        rules=["정렬 후 자르기", "Oracle 전통 방식: 인라인 뷰에서 ORDER BY 후 바깥에서 ROWNUM <= N"],
    ),
    "ROWNUM": dict(
        rules=["WHERE 단계에서 결과 행에 1부터 부여", "ORDER BY보다 먼저 부여됨"],
        traps=["SELECT … WHERE ROWNUM <= 3 ORDER BY sal DESC 는 '아무 3행을 고른 뒤 정렬' — 상위 3명이 아니다.",
               "WHERE ROWNUM = 1은 동작하지만 ROWNUM = 2, ROWNUM > 1은 항상 0행."],
        examples=[{"sql": "SELECT * FROM (\n  SELECT ename, sal FROM emp ORDER BY sal DESC\n) WHERE ROWNUM <= 3;", "explain": "정렬을 인라인 뷰에서 먼저 해야 상위 3명"}],
    ),
    "TOP": dict(rules=["SELECT TOP(n) … ORDER BY …", "TOP(n) PERCENT, WITH TIES 지원"], traps=["WITH TIES는 ORDER BY가 있어야 한다."]),
    "FETCH FIRST": dict(rules=["ORDER BY … FETCH FIRST n ROWS ONLY", "OFFSET m ROWS FETCH NEXT n ROWS ONLY", "WITH TIES 지원(ONLY 대신)"]),
    "WITH TIES": dict(rules=["N번째와 같은 정렬 값의 행을 모두 포함"], traps=["결과 행 수가 N보다 많을 수 있다."]),
    "PIVOT": dict(
        rules=["SELECT * FROM t PIVOT (SUM(sal) FOR job IN ('CLERK' AS c, 'MANAGER' AS m))", "IN 목록 값이 새 열", "PIVOT에 안 쓰인 나머지 컬럼 기준으로 암묵적 GROUP BY"],
        traps=["원본 테이블의 불필요한 컬럼까지 그룹 키가 되므로 인라인 뷰로 필요한 컬럼만 넘겨야 한다."],
    ),
    "UNPIVOT": dict(
        rules=["열 → 행", "기본 EXCLUDE NULLS: NULL 값 행 제외", "INCLUDE NULLS로 NULL 행 포함"],
        traps=["UNPIVOT 결과 행 수는 NULL 값 개수만큼 줄어든다."],
    ),
    "계층형 질의": dict(
        why="PRIOR 방향, LEVEL, WHERE 후필터, 의사 컬럼(CONNECT_BY_*)이 현행 6회 출제된 고빈도 단원.",
        rules=["START WITH: 루트 지정", "CONNECT BY PRIOR 자식 = 부모 → 순방향(Top-Down)", "CONNECT BY PRIOR 부모 = 자식 → 역방향(Bottom-Up)",
               "수행 순서: START WITH → CONNECT BY 전개 → WHERE 필터 → (ORDER SIBLINGS BY)"],
        traps=["WHERE 조건은 전개 후 행 단위로만 적용 — 제외된 노드의 자식은 남는다.",
               "START WITH를 생략하면 모든 행이 루트가 되어 각각 전개된다.",
               "일반 ORDER BY를 쓰면 계층 순서가 깨진다 → ORDER SIBLINGS BY."],
        dialect=["SQL Server는 CONNECT BY가 없고 재귀 CTE를 사용."],
        examples=[{"sql": "SELECT LEVEL, LPAD(' ', 2*(LEVEL-1)) || ename AS tree\n  FROM emp\n START WITH mgr IS NULL\nCONNECT BY PRIOR empno = mgr\n ORDER SIBLINGS BY ename;",
                   "explain": "KING(루트, LEVEL 1)부터 부하 직원 방향으로 순방향 전개"}],
    ),
    "PRIOR": dict(
        rules=["PRIOR가 붙은 컬럼 = 부모(직전) 행의 값", "PRIOR 자식키 = 부모키 → 순방향", "PRIOR 부모키 = 자식키 → 역방향"],
        traps=["CONNECT BY PRIOR empno = mgr와 CONNECT BY mgr = PRIOR empno는 같은 의미(PRIOR 위치 기준으로 판단)."],
    ),
    "순방향 계층 전개": dict(examples=[{"sql": "START WITH mgr IS NULL\nCONNECT BY PRIOR empno = mgr", "explain": "관리자 → 부하 (Top-Down)"}]),
    "역방향 계층 전개": dict(examples=[{"sql": "START WITH ename = 'SMITH'\nCONNECT BY PRIOR mgr = empno", "explain": "SMITH → 상사 → … → KING (Bottom-Up)"}]),
    "LEVEL": dict(rules=["루트 1, 한 단계 내려갈 때마다 +1"], traps=["역방향 전개에서도 시작 행이 LEVEL 1이다."]),
    "ORDER SIBLINGS BY": dict(rules=["계층 구조 유지 + 형제끼리 정렬"]),
    "NOCYCLE": dict(rules=["순환 데이터에서 ORA-01436(CONNECT BY loop) 오류 방지"]),
    "CONNECT_BY_ISCYCLE": dict(traps=["NOCYCLE 없이 사용하면 오류."]),
    "CONNECT_BY_ISLEAF": dict(rules=["자식 없음 = 1"]),
    "SYS_CONNECT_BY_PATH": dict(examples=[{"sql": "SYS_CONNECT_BY_PATH(ename, '/')", "explain": "/KING/JONES/SCOTT"}]),
    "계층형 질의 WHERE 후필터": dict(
        rules=["WHERE: 전개 후 해당 행만 제거(자식 유지)", "CONNECT BY 조건: 해당 노드와 그 하위 전체 제거(가지치기)"],
        traps=["'WHERE 조건에 걸린 노드의 하위 노드도 함께 제외된다'는 틀린 설명."],
    ),
}

RULES.update({
    "CARTESIAN PRODUCT": dict(rules=["조인 조건 누락 → M×N행"], traps=["3개 테이블 조인에 조건이 1개뿐이면 일부가 카티션 곱이 된다(N-1 규칙)."]),
    "INNER JOIN": dict(rules=["매칭 행만 반환", "JOIN = INNER JOIN", "INNER JOIN에서는 ON 조건과 WHERE 조건의 결과가 같다"]),
    "ON": dict(rules=["조인 조건 명시", "컬럼명이 달라도 사용 가능", "OUTER JOIN에서 비보존 쪽 필터는 ON에"],
               traps=["ON에 쓴 조건과 WHERE에 쓴 조건은 OUTER JOIN에서 결과가 다르다."]),
    "RIGHT OUTER JOIN": dict(rules=["오른쪽 테이블 전부 보존", "A RIGHT JOIN B = B LEFT JOIN A"]),
    "MAX": dict(rules=["NULL 제외 최댓값", "문자·날짜에도 사용"], traps=["문자형 MAX는 사전순: MAX('9', '10') = '9'.", "0행이면 NULL."]),
    "NULL 집계": dict(rules=["SUM/AVG/MIN/MAX/COUNT(열)은 NULL 제외", "값이 전부 NULL이면 SUM·AVG·MIN·MAX = NULL, COUNT(열) = 0"],
                   traps=["AVG(comm)과 SUM(comm)/COUNT(*)는 다르다."]),
    "CONNECT BY": dict(rules=["CONNECT BY [NOCYCLE] PRIOR 컬럼 = 컬럼", "PRIOR가 붙은 쪽이 부모(직전) 행", "CONNECT BY 조건으로 걸러진 노드는 하위까지 전개되지 않음(가지치기)"],
                       traps=["CONNECT BY에 PRIOR가 없으면 의미 있는 계층이 만들어지지 않는다."]),
    "START WITH": dict(rules=["루트 행 조건", "여러 행이 만족하면 각각 루트가 되어 전개"],
                       traps=["START WITH를 생략하면 모든 행이 루트가 된다."]),
    "순방향 계층 전개": dict(rules=["PRIOR 자식키 = 부모키", "루트(최상위)부터 리프 방향"]),
    "역방향 계층 전개": dict(rules=["PRIOR 부모키 = 자식키", "리프(특정 행)부터 루트 방향"]),
})
