"""Content for Stage 7–9 (데이터·객체 관리 / 트랜잭션·권한 / 방언·함정 통합) and Legacy (D7)."""

DEFS = {
    # MG1 DML
    "DML": "Data Manipulation Language. INSERT, UPDATE, DELETE, MERGE(분류에 따라 SELECT 포함). COMMIT 전까지 ROLLBACK할 수 있다.",
    "INSERT": "테이블에 행을 추가하는 문장. INSERT INTO t (열…) VALUES (…) 또는 INSERT INTO t SELECT ….",
    "INSERT ALL": "Oracle 다중 테이블 INSERT. 서브쿼리 각 행에 대해 조건을 만족하는 모든 WHEN 절(또는 무조건 모든 INTO)을 실행한다.",
    "INSERT FIRST": "Oracle 조건부 다중 INSERT. 각 행마다 처음으로 조건을 만족하는 WHEN 절 하나만 실행한다.",
    "UPDATE": "기존 행의 컬럼 값을 수정하는 문장. WHERE를 생략하면 모든 행이 수정된다.",
    "DELETE": "행을 삭제하는 DML. WHERE를 생략하면 모든 행이 삭제되지만 테이블 구조는 남고 ROLLBACK할 수 있다.",
    "MERGE": "대상 테이블과 소스를 ON 조건으로 비교해 일치하면 UPDATE(/DELETE), 없으면 INSERT하는 문장.",
    "MERGE MATCHED": "MERGE의 WHEN MATCHED THEN UPDATE SET … 절(일치하는 대상 행 수정).",
    "MERGE NOT MATCHED": "MERGE의 WHEN NOT MATCHED THEN INSERT … 절(대상에 없는 소스 행 입력).",
    "MERGE DELETE": "Oracle MERGE의 WHEN MATCHED THEN UPDATE … DELETE WHERE 조건 — UPDATE된 행 중 조건을 만족하는 행을 삭제.",
    "UPSERT": "있으면 UPDATE, 없으면 INSERT하는 동작. SQL에서는 MERGE로 구현한다.",
    "트리거": "테이블에 DML이 발생할 때 자동 실행되는 저장 프로그램. 제약조건으로 표현하기 어려운 무결성 유지에 사용.",
    # MG2 DDL
    "DDL": "Data Definition Language. CREATE, ALTER, DROP, TRUNCATE, RENAME 등 객체 구조를 정의·변경한다.",
    "CREATE TABLE": "테이블을 생성하는 DDL. 컬럼명·자료형·DEFAULT·제약조건을 정의한다.",
    "ALTER": "기존 객체의 구조를 변경하는 DDL.",
    "ALTER TABLE": "테이블의 컬럼·제약조건을 추가·변경·삭제하는 DDL.",
    "ALTER TABLE ADD": "ALTER TABLE t ADD (열 자료형) — 컬럼 또는 제약조건 추가.",
    "ADD COLUMN": "테이블에 새 컬럼을 추가하는 것. 추가된 컬럼은 맨 뒤에 붙고 기존 행에는 NULL(또는 DEFAULT)이 들어간다.",
    "ADD CONSTRAINT": "ALTER TABLE t ADD CONSTRAINT 이름 제약 — 제약조건 추가.",
    "ALTER COLUMN": "SQL Server의 컬럼 변경 문법: ALTER TABLE t ALTER COLUMN 열 자료형.",
    "ALTER/MODIFY": "컬럼 변경 문법 차이 — Oracle은 MODIFY, SQL Server는 ALTER COLUMN.",
    "MODIFY": "Oracle의 컬럼 변경 문법: ALTER TABLE t MODIFY (열 자료형 [DEFAULT …] [NOT NULL]).",
    "DROP COLUMN": "ALTER TABLE t DROP COLUMN 열 — 컬럼 삭제.",
    "DROP CONSTRAINT": "ALTER TABLE t DROP CONSTRAINT 이름 — 제약조건 삭제.",
    "RENAME COLUMN": "컬럼 이름 변경. Oracle: ALTER TABLE t RENAME COLUMN a TO b / SQL Server: sp_rename.",
    "자료형 변경": "ALTER TABLE로 컬럼 자료형·길이를 바꾸는 것. 데이터가 있으면 길이 축소·타입 변경에 제약이 있다.",
    "DROP": "객체(테이블 등)를 구조와 데이터까지 완전히 삭제하는 DDL.",
    "DROP 의존성": "다른 객체가 참조하는 테이블을 DROP할 때의 영향 — FK가 참조하면 오류, 관련 VIEW는 무효화된다.",
    "TRUNCATE": "테이블의 모든 행을 삭제하고 저장 공간을 초기화하는 DDL(구조는 유지). WHERE 불가, Oracle에서는 ROLLBACK 불가.",
    "RENAME": "객체 이름 변경. Oracle: RENAME old TO new / SQL Server: sp_rename.",
    "CREATE INDEX": "인덱스를 생성하는 DDL: CREATE [UNIQUE] INDEX 이름 ON 테이블(열…).",
    "DROP INDEX": "인덱스를 삭제하는 DDL.",
    "객체명 규칙": "테이블·컬럼명은 문자로 시작, 문자·숫자·_·$·# 사용, 길이 제한(Oracle 30바이트, 12.2+ 128), 예약어 불가, 같은 소유자 내 중복 불가.",
    "DEFAULT": "INSERT 시 값을 지정하지 않으면 들어가는 컬럼 기본값.",
    "DEFAULT 변경": "ALTER TABLE로 DEFAULT 값을 바꾸는 것. 이미 입력된 행에는 영향이 없고 이후 INSERT부터 적용된다.",
    "IDENTITY": "SQL Server의 자동 증가 컬럼 속성 IDENTITY(시작, 증가). Oracle 12c+는 GENERATED AS IDENTITY.",
    "CTAS": "CREATE TABLE … AS SELECT. SELECT 결과로 테이블을 만든다. 컬럼 구조와 데이터는 복사되지만 제약조건은 NOT NULL만 복사된다.",
    "Oracle/SQL Server DDL 차이": "컬럼 변경(MODIFY vs ALTER COLUMN), 이름 변경(RENAME vs sp_rename), DDL의 트랜잭션 처리 등 두 DBMS의 DDL 문법·동작 차이.",
    # MG3 제약조건
    "제약조건": "데이터 무결성을 보장하기 위해 컬럼·테이블에 거는 규칙 — PK, FK, UNIQUE, NOT NULL, CHECK.",
    "CHECK": "입력 값이 지정한 조건을 만족하도록 제한하는 제약조건. 조건 결과가 UNKNOWN(NULL)이면 통과한다.",
    "UNIQUE": "컬럼 값의 중복을 금지하는 제약조건. NULL은 허용된다(Oracle은 여러 NULL, SQL Server는 NULL 하나).",
    "UNIQUE 키워드": "UNIQUE 제약을 지정하는 키워드. (Oracle에서는 SELECT UNIQUE가 DISTINCT와 같은 의미로도 쓰인다.)",
    "데이터 무결성 유지": "제약조건·트리거·애플리케이션 로직 등으로 데이터의 정확성·일관성을 유지하는 것.",
    "CASCADE": "부모 변경·삭제나 객체 삭제 시 참조하는 대상까지 함께 처리하는 옵션의 통칭.",
    "CASCADE CONSTRAINTS": "Oracle DROP TABLE t CASCADE CONSTRAINTS — t를 참조하는 FK 제약조건을 함께 삭제하고 테이블을 DROP한다.",
    "DROP CASCADE": "참조 제약/종속 객체까지 함께 삭제하는 DROP 옵션(예: DROP TABLE … CASCADE CONSTRAINTS, DROP USER … CASCADE).",
    "PK 제약 비상속": "CTAS로 만든 테이블에는 원본의 PK(및 FK·UNIQUE·CHECK) 제약조건이 복사되지 않는다(NOT NULL만 복사).",
    # MG4 VIEW
    "VIEW": "하나 이상의 테이블로부터 정의된 가상 테이블. SELECT 정의만 저장하고 데이터는 저장하지 않는다.",
    "VIEW 의존성": "VIEW는 기반 테이블에 의존하므로 기반 테이블이 삭제·변경되면 무효(사용 불가)가 된다.",
    # MG5 Transaction
    "Transaction": "하나의 논리적 작업 단위를 이루는 연산들의 집합. 모두 반영되거나 모두 취소된다.",
    "ACID": "트랜잭션의 4가지 특성 — 원자성(Atomicity), 일관성(Consistency), 고립성(Isolation), 지속성(Durability).",
    "원자성": "트랜잭션의 연산은 모두 수행되거나 전혀 수행되지 않아야 한다(All or Nothing).",
    "일관성": "트랜잭션 수행 전후에 데이터베이스가 무결성 제약을 만족하는 일관된 상태여야 한다.",
    "격리성": "실행 중인 트랜잭션의 중간 결과를 다른 트랜잭션이 볼 수 없어야 한다(고립성).",
    "지속성": "COMMIT된 결과는 장애가 나도 영구히 보존되어야 한다(영속성).",
    "TCL": "Transaction Control Language — COMMIT, ROLLBACK, SAVEPOINT.",
    "COMMIT": "트랜잭션의 변경을 영구 반영하고 트랜잭션을 종료한다.",
    "ROLLBACK": "마지막 COMMIT 이후의 변경을 모두 취소한다.",
    "SAVEPOINT": "트랜잭션 안에 저장점을 두어 그 지점까지만 부분 ROLLBACK할 수 있게 한다.",
    "ROLLBACK TO SAVEPOINT": "지정한 저장점 이후의 변경만 취소한다(트랜잭션은 계속 진행 중).",
    "AUTO COMMIT": "각 SQL 문이 실행 즉시 자동으로 COMMIT되는 모드. SQL Server의 기본 동작.",
    "Oracle DDL 자동 커밋": "Oracle은 DDL 실행 전후로 자동 COMMIT하므로 이전 DML까지 확정되고 ROLLBACK할 수 없다.",
    "SQL Server 트랜잭션": "SQL Server는 기본 AUTO COMMIT이고 BEGIN TRAN으로 명시적 트랜잭션을 시작하며, 그 안의 DDL도 ROLLBACK할 수 있다.",
    # MG6 DCL
    "DCL": "Data Control Language — GRANT(권한 부여), REVOKE(권한 회수).",
    "GRANT": "GRANT 권한 ON 객체 TO 사용자 [WITH GRANT OPTION] — 권한 부여.",
    "REVOKE": "REVOKE 권한 ON 객체 FROM 사용자 — 권한 회수.",
    "GRANT OPTION": "WITH GRANT OPTION — 받은 객체 권한을 다른 사용자에게 다시 부여할 수 있게 하는 옵션.",
    "권한 연쇄 회수": "WITH GRANT OPTION으로 재부여된 객체 권한은 원 부여자의 권한이 회수되면 연쇄적으로 회수된다(WITH ADMIN OPTION 시스템 권한은 연쇄 회수되지 않음).",
    "REVOKE RESTRICT": "ANSI 회수 옵션. 회수 대상 권한으로 재부여한 권한이 있으면 REVOKE를 거부한다(CASCADE는 함께 회수).",
    "ROLE": "여러 권한을 묶은 객체. CREATE ROLE → 권한을 ROLE에 GRANT → ROLE을 사용자에게 GRANT.",
    "TO": "GRANT 문에서 권한을 받을 사용자·롤을 지정하는 키워드(REVOKE는 FROM).",
    "객체 권한": "특정 객체(테이블 등)에 대한 SELECT, INSERT, UPDATE, DELETE, REFERENCES 등의 권한.",
    "UPDATE 권한": "객체 권한의 하나. 특정 컬럼에만 부여할 수도 있다(GRANT UPDATE(sal) ON emp TO u).",
    "시스템 권한": "CREATE TABLE, CREATE SESSION처럼 DB 전체 작업에 대한 권한. WITH ADMIN OPTION으로 재부여를 허용한다.",
    # XC1 방언 참조 노드
    "ANSI/ISO SQL": "표준 SQL. COALESCE, CASE, NULLIF, ANSI JOIN, FETCH FIRST, EXCEPT 등 DBMS 공통 문법의 기준.",
    "Oracle SQL": "Oracle 고유 문법 — NVL/NVL2, DECODE, ROWNUM, MINUS, (+) OUTER JOIN, CONNECT BY, ''=NULL, DDL 자동 커밋.",
    "SQL Server": "SQL Server(T-SQL) — ISNULL, TOP, EXCEPT, LEN, + 문자열 결합, GETDATE, IDENTITY, LIKE [], 기본 AUTO COMMIT.",
    # Synthetic integration
    "NULL 처리 DBMS 차이": "같은 NULL이라도 DBMS마다 다른 부분 — 빈 문자열 처리, NULL 치환 함수(NVL/ISNULL/COALESCE), UNIQUE 컬럼의 NULL 허용 개수.",
    "NULL 정렬 DBMS 차이": "ORDER BY에서 Oracle은 NULL을 가장 큰 값, SQL Server는 가장 작은 값으로 취급하는 차이와 NULLS FIRST/LAST 지원 여부.",
    "Top-N 문법 차이": "상위 N행 조회 문법의 DBMS 차이 — Oracle ROWNUM/FETCH FIRST, SQL Server TOP/OFFSET-FETCH, ANSI FETCH FIRST.",
    "차집합 MINUS/EXCEPT 차이": "차집합 연산자 이름 차이 — Oracle MINUS(21c부터 EXCEPT도 지원), SQL Server·ANSI EXCEPT.",
    "DDL 커밋 동작 차이": "DDL·TRUNCATE를 실행했을 때 COMMIT/ROLLBACK 가능 여부의 DBMS 차이(Oracle 자동 커밋 vs SQL Server 명시적 트랜잭션 내 ROLLBACK 가능).",
    "문자열 함수 DBMS 차이": "같은 문자열 처리의 함수명·동작 차이 — LENGTH/LEN, SUBSTR/SUBSTRING, ||·CONCAT/+, INSTR/CHARINDEX.",
    "별칭 가시성 종합": "SQL 논리 실행 순서 때문에 별칭·집계가 어느 절에서 보이는지 정리한 종합 규칙.",
    "NULL 함정 종합": "NOT IN, IN 목록 NULL, COUNT(열), 산술 연산, 공집합 집계, DISTINCT/GROUP BY의 NULL 처리 등 NULL 관련 시험 함정 총정리.",
    "OUTER JOIN 필터 위치 종합": "OUTER JOIN에서 조건을 ON/WHERE/(+) 어디에 두느냐에 따라 보존 행이 달라지는 규칙 총정리.",
    # D7 Legacy
    "인덱스": "테이블 데이터를 빠르게 찾기 위한 정렬된 접근 구조(키 값 + 행 위치 ROWID).",
    "B-Tree 인덱스": "루트-브랜치-리프 블록으로 구성된 균형 트리 인덱스. 가장 일반적인 인덱스 구조.",
    "CLUSTERED INDEX": "SQL Server에서 테이블 데이터를 인덱스 키 순서로 물리 정렬해 저장하는 인덱스(테이블당 1개).",
    "FK 인덱스": "FK 컬럼에 만드는 인덱스. 조인 성능과 부모 삭제 시 잠금 문제를 완화한다.",
    "Full Table Scan": "테이블의 모든 블록을 처음부터 끝까지 읽는 접근 방식.",
    "IOT": "Index-Organized Table. 테이블 데이터를 PK 인덱스 구조 안에 함께 저장하는 Oracle 테이블.",
    "Index Scan": "인덱스를 통해 필요한 행만 찾아 읽는 접근 방식(Range/Unique/Full/Skip Scan 등).",
    "UNIQUE INDEX SCAN": "유일 인덱스에 = 조건을 주어 단 한 건을 찾는 인덱스 스캔.",
    "파티셔닝": "큰 테이블을 기준값에 따라 여러 파티션으로 나눠 저장하는 기법.",
    "RANGE 파티션": "값의 범위(예: 날짜 구간)로 나누는 파티셔닝.",
    "LIST 파티션": "값 목록(예: 지역 코드)으로 나누는 파티셔닝.",
    "HASH 파티션": "해시 함수 결과로 고르게 분산하는 파티셔닝.",
    "개별 타입": "슈퍼/서브타입 변환 방식 중 슈퍼타입과 각 서브타입을 개별 테이블로 만드는 방식(One-to-One).",
    "슈퍼/서브타입 변환": "논리 모델의 슈퍼/서브타입을 물리 테이블로 바꾸는 방식 — One-to-One(개별), Plus(서브타입별), Single(통합).",
    "규칙 기반 옵티마이저": "RBO. 미리 정한 액세스 경로 우선순위 규칙으로 실행계획을 선택하는 옵티마이저.",
    "비용 기반 옵티마이저": "CBO. 통계 정보로 비용을 추정해 가장 낮은 비용의 실행계획을 선택하는 옵티마이저.",
    "실행계획": "SQL을 수행하기 위해 옵티마이저가 선택한 처리 절차(접근 경로, 조인 순서·방식).",
    "실행계획 읽기 순서": "들여쓰기가 깊은 것부터, 같은 깊이에서는 위에서 아래로 읽는다.",
    "컬럼 분할": "자주 쓰지 않는 컬럼을 별도 테이블로 나누는 반정규화 기법.",
    "테이블 병합": "1:1·1:M 관계 테이블을 하나로 합치는 반정규화 기법.",
    "통계 테이블 추가": "집계 결과를 미리 저장하는 통계 테이블을 추가하는 반정규화 기법.",
    "분산 데이터베이스": "물리적으로 분산된 여러 DB를 하나의 논리 DB처럼 사용하는 시스템.",
    "분할 투명성": "사용자가 테이블이 여러 조각으로 분할 저장된 사실을 몰라도 되는 성질.",
    "위치 투명성": "사용자가 데이터의 물리적 위치를 몰라도 되는 성질.",
    "중복 투명성": "같은 데이터가 여러 사이트에 복제되어 있어도 사용자는 하나처럼 쓰는 성질.",
    "지역사상 투명성": "지역 DBMS와 물리 DB 사이의 사상(매핑)이 보장되어 지역 시스템 이름과 무관하게 접근하는 성질.",
    "PL/SQL": "Oracle의 절차적 SQL 확장 언어(변수, 조건문, 반복문, 예외 처리).",
    "PL/SQL 블록": "DECLARE(선언부) - BEGIN(실행부) - EXCEPTION(예외 처리부) - END 구조.",
    "PL/SQL 변수 범위": "블록 안에서 선언한 변수는 그 블록과 내부 블록에서만 유효하다.",
    "CURSOR": "SQL 결과 집합을 한 행씩 처리하기 위한 작업 영역 포인터.",
    "CURSOR OPEN": "커서의 SELECT를 실행해 결과 집합을 준비하는 단계.",
    "CURSOR FETCH": "커서 결과 집합에서 한 행씩 변수로 가져오는 단계.",
    "CURSOR CLOSE": "커서를 닫아 자원을 해제하는 단계.",
    "조인 수행 원리": "물리적 조인 방식 — Nested Loop, Sort Merge, Hash Join.",
    "NESTED LOOP JOIN": "선행 테이블의 각 행마다 후행 테이블을 반복 탐색하는 조인. 인덱스가 중요하며 소량·OLTP에 유리.",
    "Sort Merge Join": "두 집합을 조인 키로 정렬한 뒤 병합하는 조인. 비등가 조인에도 사용 가능.",
    "HASH JOIN": "작은 쪽으로 해시 테이블을 만들고(Build) 큰 쪽으로 탐색(Probe)하는 조인. 등가 조인만 가능, 대용량에 유리.",
    "Hash Join Build/Probe": "HASH JOIN의 두 단계 — Build(작은 입력으로 해시 테이블 생성), Probe(큰 입력으로 탐색).",
    "성능 데이터 모델링": "성능을 고려해 정규화/반정규화, 테이블 분할, 컬럼 순서, 이력 모델 등을 설계하는 것.",
    "Row Chaining": "한 행이 너무 길어 하나의 블록에 담기지 못해 여러 블록에 나뉘어 저장되는 현상.",
    "Row Migration": "UPDATE로 행이 커져 원래 블록에 들어가지 못하고 다른 블록으로 옮겨지며 원위치에는 주소만 남는 현상.",
}

RULES = {
    "DML": dict(
        why="DML/DDL/DCL/TCL 분류와 COMMIT·ROLLBACK 가능 여부는 2과목 기본 문제다.",
        rules=["INSERT/UPDATE/DELETE/MERGE", "COMMIT 전까지 ROLLBACK 가능", "Oracle은 DML 후 명시적 COMMIT 필요(도구 설정에 따라 다름)"],
    ),
    "INSERT FIRST": dict(
        rules=["각 행마다 첫 번째로 만족하는 WHEN 하나만 실행"],
        traps=["INSERT ALL은 만족하는 모든 WHEN을 실행 → 같은 행이 여러 테이블에 들어갈 수 있다."],
        examples=[{"sql": "INSERT FIRST\n  WHEN sal >= 3000 THEN INTO high_emp VALUES (empno, sal)\n  WHEN sal >= 1000 THEN INTO mid_emp  VALUES (empno, sal)\n  ELSE INTO low_emp VALUES (empno, sal)\nSELECT empno, sal FROM emp;", "explain": "sal=5000인 행은 high_emp에만 들어간다(INSERT ALL이면 mid_emp에도)"}],
    ),
    "MERGE": dict(
        rules=["MERGE INTO 대상 USING 소스 ON (조건)", "WHEN MATCHED THEN UPDATE … [DELETE WHERE …]", "WHEN NOT MATCHED THEN INSERT …"],
        traps=["ON 절에 쓴 컬럼은 UPDATE SET에서 수정할 수 없다(Oracle).", "MERGE DELETE는 UPDATE된 행 중에서만 삭제한다."],
    ),
    "UPDATE": dict(traps=["WHERE 없는 UPDATE는 모든 행을 수정한다.", "UPDATE t SET col = NULL은 가능(NOT NULL 제약이 없으면)."]),
    "DELETE": dict(rules=["DML — ROLLBACK 가능", "WHERE 생략 시 전체 행 삭제, 구조 유지", "삭제 트리거 동작"]),
    "DDL": dict(
        why="DDL 종류와 Oracle 자동 커밋, TRUNCATE/DROP/DELETE 비교가 반복 출제된다.",
        rules=["CREATE / ALTER / DROP / TRUNCATE / RENAME", "Oracle: DDL 실행 시 자동 COMMIT"],
        traps=["Oracle에서 DML 후 DDL을 실행하면 앞의 DML까지 COMMIT되어 ROLLBACK할 수 없다."],
    ),
    "TRUNCATE": dict(
        rules=["모든 행 삭제 + 저장 공간 초기화", "구조·인덱스·제약은 유지", "WHERE 사용 불가"],
        traps=["Oracle TRUNCATE는 DDL이라 ROLLBACK 불가.", "SQL Server는 명시적 트랜잭션 안의 TRUNCATE를 ROLLBACK할 수 있다."],
    ),
    "DROP": dict(rules=["구조+데이터 삭제"], traps=["다른 테이블의 FK가 참조 중이면 DROP 실패 → CASCADE CONSTRAINTS(Oracle)."]),
    "CTAS": dict(
        why="CTAS로 복사되는 것과 복사되지 않는 것(제약조건)이 현행 2회 이상 출제.",
        rules=["CREATE TABLE 새테이블 AS SELECT …", "컬럼·자료형·데이터 복사", "제약조건은 NOT NULL만 복사"],
        traps=["PK·FK·UNIQUE·CHECK·DEFAULT·인덱스는 복사되지 않는다.", "구조만 복사하려면 WHERE 1 = 2.",
               "SQL Server는 CTAS 대신 SELECT … INTO 새테이블 FROM …."],
    ),
    "PK 제약 비상속": dict(rules=["CTAS 결과 테이블에는 PK가 없다 → ALTER TABLE ADD CONSTRAINT로 추가"]),
    "ALTER TABLE": dict(
        rules=["ADD: 컬럼·제약 추가", "MODIFY(Oracle) / ALTER COLUMN(SQL Server): 컬럼 변경", "DROP COLUMN, RENAME COLUMN, DROP CONSTRAINT"],
        traps=["Oracle에서 여러 컬럼을 MODIFY할 때는 괄호로 묶는다: MODIFY (c1 …, c2 …).",
               "데이터가 있는 컬럼의 길이를 기존 데이터보다 작게 줄일 수 없다."],
    ),
    "DEFAULT 변경": dict(traps=["DEFAULT를 바꿔도 기존 행 값은 바뀌지 않는다."]),
    "객체명 규칙": dict(
        rules=["문자로 시작", "A-Z, a-z, 0-9, _, $, # 사용", "예약어 불가", "같은 소유자 안에서 중복 불가"],
        traps=["숫자로 시작하는 테이블명(예: 1EMP)은 큰따옴표 없이 만들 수 없다.", "하이픈(-)은 사용할 수 없다."],
    ),
    "IDENTITY": dict(dialect=["SQL Server: col INT IDENTITY(1,1)", "Oracle 12c+: col NUMBER GENERATED ALWAYS AS IDENTITY, 이전 버전은 SEQUENCE"]),
    "제약조건": dict(
        why="제약조건 종류별 NULL·중복 허용 여부와 CTAS 상속, CHECK의 NULL 통과가 출제된다.",
        rules=["PK: UNIQUE + NOT NULL, 1개", "UNIQUE: 중복 불가, NULL 허용", "NOT NULL: NULL 불가", "CHECK: 조건 만족", "FK: 부모 PK/UNIQUE 참조"],
    ),
    "UNIQUE": dict(
        rules=["중복 금지, NULL 허용", "테이블에 여러 개 가능"],
        traps=["PK와 달리 NULL을 허용한다."],
        dialect=["Oracle: UNIQUE 컬럼에 NULL 여러 개 가능 / SQL Server: UNIQUE 제약 컬럼에 NULL은 하나만"],
    ),
    "CHECK": dict(
        rules=["조건이 FALSE면 거부, TRUE·UNKNOWN이면 허용"],
        traps=["CHECK (sal > 0)인 컬럼에도 NULL은 들어간다 — 막으려면 NOT NULL 추가."],
    ),
    "NOT NULL": dict(rules=["컬럼 레벨에서만 정의(Oracle)", "CTAS에서 유일하게 복사되는 제약"]),
    "CASCADE CONSTRAINTS": dict(rules=["DROP TABLE 부모 CASCADE CONSTRAINTS → 자식의 FK 제약 삭제 후 부모 DROP"],
                                traps=["자식 테이블의 데이터는 삭제되지 않는다(FK 제약만 제거)."]),
    "VIEW": dict(
        why="VIEW의 장점(보안·독립성·편의성)과 의존성, VIEW를 통한 DML 가능 여부가 출제된다.",
        rules=["SELECT 정의만 저장, 데이터 없음", "장점: 독립성, 편리성, 보안성", "Oracle은 ALTER VIEW로 정의를 바꿀 수 없음 → CREATE OR REPLACE VIEW"],
        traps=["VIEW도 조건에 따라 INSERT/UPDATE/DELETE가 가능하다(집계·DISTINCT·GROUP BY 등이 있으면 불가).",
               "기반 테이블을 DROP하면 VIEW 정의는 남지만 무효 상태가 된다."],
    ),
    "Transaction": dict(
        why="ACID, COMMIT/ROLLBACK/SAVEPOINT 결과 추적, DBMS별 자동 커밋 차이가 2과목 단골 문제다.",
        rules=["시작: 첫 DML(Oracle 암묵적) / BEGIN TRAN(SQL Server 명시적)", "종료: COMMIT 또는 ROLLBACK", "DDL·정상 종료 시 Oracle은 자동 COMMIT"],
    ),
    "ACID": dict(
        rules=["원자성: All or Nothing", "일관성: 전후 무결성 유지", "고립성: 중간 결과 비공개", "지속성: COMMIT 결과 영구 보존"],
        traps=["'일관성'과 '고립성' 설명을 바꿔 놓은 선지에 주의."],
    ),
    "COMMIT": dict(rules=["변경 영구 반영, 트랜잭션 종료", "COMMIT 후에는 ROLLBACK 불가", "SAVEPOINT는 COMMIT 시 모두 해제"]),
    "ROLLBACK": dict(rules=["마지막 COMMIT 이후 변경 모두 취소", "잠금 해제"]),
    "SAVEPOINT": dict(
        rules=["SAVEPOINT 이름 → ROLLBACK TO 이름", "ROLLBACK TO 이후에도 트랜잭션은 계속"],
        traps=["같은 이름의 SAVEPOINT를 다시 만들면 앞의 것은 사라진다(Oracle).", "ROLLBACK(이름 없이)은 SAVEPOINT와 상관없이 전체 취소."],
        dialect=["Oracle: SAVEPOINT sp1; ROLLBACK TO sp1;", "SQL Server: SAVE TRANSACTION sp1; ROLLBACK TRANSACTION sp1;"],
        examples=[{"sql": "INSERT … (A);\nSAVEPOINT s1;\nINSERT … (B);\nROLLBACK TO s1;\nCOMMIT;", "explain": "A만 반영"}],
    ),
    "Oracle DDL 자동 커밋": dict(
        rules=["DDL 실행 전 COMMIT, 실행 후 COMMIT"],
        traps=["INSERT 후 CREATE TABLE을 실행하고 ROLLBACK해도 INSERT는 취소되지 않는다."],
    ),
    "AUTO COMMIT": dict(dialect=["SQL Server 기본: AUTO COMMIT", "Oracle(SQL*Plus 등): 기본 수동 COMMIT, SET AUTOCOMMIT ON으로 변경"]),
    "DCL": dict(
        why="GRANT/REVOKE 문법, WITH GRANT OPTION 연쇄 회수, ROLE 사용은 현행 3회 출제.",
        rules=["GRANT 권한 ON 객체 TO 사용자", "REVOKE 권한 ON 객체 FROM 사용자"],
        traps=["REVOKE는 TO가 아니라 FROM."],
    ),
    "GRANT": dict(
        rules=["GRANT SELECT, INSERT ON emp TO scott [WITH GRANT OPTION]", "GRANT CREATE SESSION TO scott [WITH ADMIN OPTION]", "PUBLIC에게 부여 가능"],
    ),
    "REVOKE": dict(traps=["WITH GRANT OPTION으로 재부여한 객체 권한은 연쇄 회수된다."]),
    "권한 연쇄 회수": dict(
        rules=["WITH GRANT OPTION(객체 권한): A→B→C 부여 후 A가 B의 권한 회수 시 C 권한도 회수", "WITH ADMIN OPTION(시스템 권한): 연쇄 회수되지 않음"],
    ),
    "ROLE": dict(rules=["CREATE ROLE r; GRANT 권한 TO r; GRANT r TO 사용자", "권한 관리 단순화"]),
    "NULL 처리 DBMS 차이": dict(
        why="DBMS 방언 문제 중 NULL 관련 차이는 함수명·빈 문자열·UNIQUE 처리에서 반복된다.",
        rules=["NULL 치환: Oracle NVL / SQL Server ISNULL / 공통 COALESCE", "빈 문자열: Oracle ''=NULL / SQL Server ''≠NULL",
               "UNIQUE 컬럼 NULL: Oracle 여러 개 / SQL Server 1개"],
    ),
    "NULL 정렬 DBMS 차이": dict(rules=["Oracle ASC: NULL 마지막, DESC: NULL 처음", "SQL Server ASC: NULL 처음, DESC: NULL 마지막", "NULLS FIRST/LAST: Oracle만"]),
    "Top-N 문법 차이": dict(
        rules=["Oracle: 인라인 뷰 + ROWNUM, 12c+ FETCH FIRST", "SQL Server: TOP(n) [WITH TIES], OFFSET-FETCH", "ANSI: FETCH FIRST n ROWS ONLY/WITH TIES"],
        traps=["ROWNUM은 ORDER BY 전에 부여된다.", "TOP/FETCH FIRST의 WITH TIES는 ORDER BY가 필요하다."],
    ),
    "차집합 MINUS/EXCEPT 차이": dict(rules=["Oracle MINUS, SQL Server EXCEPT — 의미는 같다(중복 제거된 차집합)"]),
    "DDL 커밋 동작 차이": dict(
        rules=["Oracle: DDL 전후 자동 COMMIT → DDL·TRUNCATE ROLLBACK 불가", "SQL Server: 명시적 트랜잭션(BEGIN TRAN) 안의 DDL·TRUNCATE ROLLBACK 가능, 기본은 AUTO COMMIT"],
    ),
    "문자열 함수 DBMS 차이": dict(rules=["길이: LENGTH / LEN", "부분 문자열: SUBSTR / SUBSTRING", "결합: || 또는 CONCAT / + 또는 CONCAT", "위치: INSTR / CHARINDEX"]),
    "별칭 가시성 종합": dict(
        rules=["FROM→WHERE→GROUP BY→HAVING→SELECT→ORDER BY", "SELECT 별칭: ORDER BY에서만 사용 가능",
               "집계 함수: WHERE 불가, HAVING·SELECT·ORDER BY 가능", "집합 연산 ORDER BY: 첫 SELECT의 이름/별칭 기준"],
    ),
    "NULL 함정 종합": dict(
        rules=["NULL 비교 = UNKNOWN, WHERE는 TRUE만", "NOT IN 목록에 NULL → 0행", "COUNT(열)·AVG·SUM은 NULL 제외",
               "NULL 산술 = NULL", "0행 집계: COUNT 0, 나머지 NULL", "DISTINCT·GROUP BY는 NULL을 하나로 묶음"],
    ),
    "OUTER JOIN 필터 위치 종합": dict(
        rules=["비보존 쪽 조건: ON(보존 행 유지) vs WHERE(보존 행 제거)", "Oracle (+): 비보존 쪽 모든 조건에 (+)를 붙여야 ON처럼 동작",
               "OUTER JOIN 뒤 INNER JOIN이 오면 보존 행이 사라질 수 있음", "FULL OUTER JOIN = LEFT ∪ RIGHT"],
    ),
    "인덱스": dict(rules=["검색 성능 향상, DML 성능은 저하될 수 있음"], traps=["인덱스 컬럼을 가공하거나 암시적 형변환이 일어나면 인덱스를 못 탈 수 있다."]),
    "NESTED LOOP JOIN": dict(rules=["선행 테이블 결과가 적을수록 유리", "랜덤 액세스 위주"]),
    "HASH JOIN": dict(rules=["등가 조인만", "작은 테이블로 Build"]),
    "Sort Merge Join": dict(rules=["정렬 부하", "비등가 조인 가능"]),
}

RULES.update({
    "DEFAULT": dict(rules=["INSERT 시 컬럼 생략 또는 DEFAULT 키워드 사용 시 적용", "명시적으로 NULL을 넣으면 DEFAULT가 아니라 NULL이 들어감"],
                    traps=["INSERT INTO t(col) VALUES (NULL)은 DEFAULT 값을 쓰지 않는다."]),
    "원자성": dict(rules=["All or Nothing", "COMMIT/ROLLBACK으로 보장"], traps=["'일부 연산만 반영될 수 있다'는 원자성 위반."]),
    "GRANT OPTION": dict(rules=["GRANT … TO u WITH GRANT OPTION", "u가 다른 사용자에게 같은 객체 권한을 재부여 가능"],
                         traps=["WITH GRANT OPTION으로 재부여된 권한은 원 권한이 REVOKE되면 연쇄 회수된다."]),
})
