"""Content for Stage 2–3 (SQL 실행 모델 / 표현식·함수)."""

DEFS = {
    # SQ0
    "SQL의 특징": "관계형 데이터베이스를 다루는 표준 언어로, 선언적·비절차적·집합적 특징을 가진다.",
    "SQL 비절차성": "처리 절차(How)를 기술하지 않고 원하는 결과만 기술하는 성질.",
    "SQL 선언적 언어": "무엇(What)을 원하는지만 선언하면 실행 방법은 DBMS(옵티마이저)가 결정한다는 성질.",
    "SQL 집합적 언어": "한 행씩이 아니라 행의 집합 단위로 데이터를 처리하는 성질.",
    "SQL 논리 실행 순서": "SELECT 문의 논리적 평가 순서: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. 작성 순서와 다르다.",
    # SQ1
    "SELECT": "테이블에서 데이터를 조회하는 문장. SELECT 열 FROM 테이블 [WHERE] [GROUP BY] [HAVING] [ORDER BY].",
    "ALIAS": "컬럼 또는 테이블에 붙이는 별칭. 컬럼 별칭은 AS(생략 가능) 뒤에 쓴다.",
    "테이블 별칭": "FROM 절 테이블에 붙이는 별칭. Oracle에서는 테이블 별칭 앞에 AS를 쓸 수 없다.",
    "컬럼 별칭 대소문자": "큰따옴표 없는 별칭은 대문자로 처리(Oracle)되며, 공백·특수문자·대소문자를 유지하려면 큰따옴표가 필요하다.",
    "DISTINCT": "SELECT 결과에서 중복 행을 제거하는 키워드. 지정한 모든 컬럼의 조합 기준으로 판단한다.",
    "공집합": "조건을 만족하는 행이 하나도 없는 결과(0행). 이때 집계·스칼라 서브쿼리가 무엇을 반환하는지가 시험 함정이다.",
    "문자 비교": "CHAR끼리는 짧은 쪽에 공백을 채워 비교(공백 패딩 비교), VARCHAR가 섞이면 공백까지 그대로 비교(비패딩 비교)한다.",
    "SELECT INTO": "SQL Server에서 SELECT 결과로 새 테이블을 만드는 문법(Oracle CTAS에 대응). PL/SQL에서는 조회 값을 변수에 담는 구문.",
    # SQ2
    "자료형": "컬럼이 저장할 수 있는 값의 종류(문자형, 숫자형, 날짜형 등).",
    "CHAR": "고정 길이 문자형. 지정 길이보다 짧은 값은 뒤를 공백으로 채운다.",
    "CHAR 후행 공백": "CHAR(n)에 짧은 값을 넣으면 뒤에 공백이 채워져 길이가 n이 되고, 비교 시 공백 패딩 규칙이 적용된다.",
    "VARCHAR": "가변 길이 문자형(Oracle은 VARCHAR2). 입력한 길이만큼만 저장한다.",
    "NUMERIC": "숫자형. Oracle NUMBER(p,s), SQL Server NUMERIC/DECIMAL(p,s). p=전체 자릿수, s=소수 자릿수.",
    "DATE": "날짜형. Oracle DATE는 연·월·일과 시·분·초까지 저장한다.",
    "암시적 형변환": "DBMS가 자동으로 자료형을 변환하는 것. Oracle은 문자와 숫자를 비교할 때 문자를 숫자로 변환한다.",
    "명시적 형변환": "변환 함수(TO_CHAR, TO_NUMBER, TO_DATE, CAST, CONVERT)로 사용자가 직접 자료형을 바꾸는 것.",
    "문자 리터럴 따옴표 이스케이프": "문자열 안의 작은따옴표는 두 번('') 써서 표현한다(예: 'It''s').",
    # SQ3
    "NULL": "값이 없거나 알 수 없는 상태. 0이나 공백 문자와 다르며, 비교·연산·집계에서 특수하게 동작한다.",
    "NULL 비교": "NULL을 =, <>, > 등으로 비교하면 결과는 TRUE/FALSE가 아니라 UNKNOWN이다.",
    "UNKNOWN": "3값 논리(TRUE/FALSE/UNKNOWN)의 세 번째 값. WHERE·HAVING·ON은 TRUE인 행만 통과시킨다.",
    "IS NULL": "값이 NULL인지 판별하는 연산자. NULL 판별에는 = NULL이 아니라 IS NULL을 써야 한다.",
    "IS NOT NULL": "값이 NULL이 아닌지 판별하는 연산자.",
    "NULL 산술 연산": "NULL이 포함된 사칙연산의 결과는 NULL이다(예: 100 + NULL = NULL).",
    "빈 문자열과 NULL(Oracle)": "Oracle은 ''(길이 0 문자열)을 NULL로 저장·처리한다. SQL Server는 ''과 NULL을 구분한다.",
    "DISTINCT NULL": "DISTINCT는 여러 NULL을 같은 값으로 보아 하나만 남긴다.",
    "GROUP BY NULL": "GROUP BY는 NULL 값들을 하나의 그룹으로 묶는다.",
    "IN + NULL": "col IN (1, NULL)은 col = 1 OR col = NULL이므로 NULL 항목은 어떤 행과도 일치하지 않는다.",
    "NULL 정렬": "ORDER BY에서 NULL이 어디에 오는지는 DBMS마다 다르다(Oracle: 가장 큰 값, SQL Server: 가장 작은 값).",
    "NULLS FIRST": "Oracle ORDER BY 옵션. NULL을 정렬 결과의 맨 앞에 둔다(SQL Server 미지원).",
    "NULLS LAST": "Oracle ORDER BY 옵션. NULL을 정렬 결과의 맨 뒤에 둔다(SQL Server 미지원).",
    "Oracle NULL 정렬": "Oracle은 NULL을 가장 큰 값으로 취급 → ASC에서 마지막, DESC에서 처음.",
    "SQL Server NULL 정렬": "SQL Server는 NULL을 가장 작은 값으로 취급 → ASC에서 처음, DESC에서 마지막.",
    "NOT NULL": "컬럼에 NULL 입력을 금지하는 제약조건(IS NOT NULL 조건식과 구분).",
    # SQ4
    "WHERE": "FROM에서 읽은 행 중 조건식이 TRUE인 행만 남기는 행 필터 절.",
    "AND": "두 조건이 모두 TRUE일 때 TRUE. FALSE AND UNKNOWN = FALSE, TRUE AND UNKNOWN = UNKNOWN.",
    "OR": "두 조건 중 하나라도 TRUE면 TRUE. TRUE OR UNKNOWN = TRUE, FALSE OR UNKNOWN = UNKNOWN.",
    "NOT": "조건의 논리값을 반전. NOT UNKNOWN = UNKNOWN.",
    "AND/OR 우선순위": "논리 연산자 우선순위는 NOT > AND > OR. 괄호가 없으면 AND가 OR보다 먼저 평가된다.",
    "연산자 우선순위": "산술 → 연결(||) → 비교 → IS NULL·LIKE·IN → BETWEEN → NOT → AND → OR 순으로 평가된다(괄호 우선).",
    "BETWEEN": "BETWEEN a AND b는 a 이상 b 이하(>= a AND <= b)를 뜻한다.",
    "BETWEEN 경계 포함": "BETWEEN은 양쪽 경계값을 모두 포함하며, a > b로 쓰면 결과가 없다.",
    "IN·NOT IN": "값이 목록과 일치(IN) 또는 불일치(NOT IN)하는지 판단하는 조건 묶음.",
    "IN": "값이 목록 중 하나와 같으면 TRUE. 여러 OR 등호 조건의 축약형.",
    "NOT IN": "값이 목록의 어떤 값과도 같지 않으면 TRUE. 목록에 NULL이 있으면 결과가 항상 FALSE/UNKNOWN이 되어 0행이 된다.",
    "행값 IN": "(col1, col2) IN ((1,'A'),(2,'B'))처럼 여러 컬럼을 묶어 비교. Oracle은 지원, SQL Server는 미지원.",
    "LIKE": "와일드카드 패턴으로 문자열을 비교하는 연산자.",
    "와일드카드": "LIKE의 패턴 문자. %는 0개 이상의 임의 문자, _는 정확히 1개의 임의 문자.",
    "LIKE ESCAPE": "% 또는 _ 문자 자체를 찾을 때 ESCAPE로 이스케이프 문자를 지정한다(예: LIKE '%#_%' ESCAPE '#').",
    "LIKE 컬럼 패턴": "LIKE 오른쪽에 상수가 아니라 컬럼·식(예: name LIKE prefix || '%')을 쓰는 형태.",
    "SQL Server LIKE []": "SQL Server LIKE는 [abc], [a-z], [^a] 같은 문자 집합 패턴을 지원한다.",
    "날짜 범위 조회": "DATE 컬럼에 기간 조건을 거는 것. 시·분·초가 포함되어 있어 경계 처리가 핵심이다.",
    "날짜 경계": "BETWEEN '2024-01-01' AND '2024-01-31'은 31일 00:00:00까지만 포함해 31일의 나머지 시각을 누락하는 함정.",
    "날짜 반개방 구간": "dt >= 시작일 AND dt < 종료일+1 형태로 끝 경계를 열어 두는 안전한 날짜 조건.",
    "SELECT 별칭 WHERE 사용 불가": "WHERE는 SELECT보다 먼저 평가되므로 SELECT 절의 컬럼 별칭을 WHERE에서 사용할 수 없다.",
    # SQ5
    "ORDER BY": "결과 행을 정렬하는 절. 기본은 ASC이며 논리적으로 가장 마지막에 수행된다.",
    "ASC": "오름차순 정렬(기본값).",
    "DESC": "내림차순 정렬.",
    "다중 열 ORDER BY": "첫 정렬 키가 같은 행끼리 다음 키로 정렬. 컬럼마다 ASC/DESC를 따로 지정한다.",
    "ORDER BY 순서번호": "SELECT 목록의 위치 번호로 정렬(ORDER BY 2).",
    "ORDER BY 별칭": "ORDER BY는 SELECT 이후에 평가되므로 SELECT 절의 컬럼 별칭을 사용할 수 있다.",
    "ORDER BY CASE": "ORDER BY 절에 CASE 식을 써서 사용자 정의 순서로 정렬하는 기법.",
    # FN1 문자
    "단일행 함수": "각 행마다 하나의 결과를 반환하는 함수(문자·숫자·날짜·변환·NULL 관련). SELECT·WHERE·ORDER BY에서 사용한다.",
    "문자형 함수": "문자열을 입력받아 처리하는 단일행 함수(LOWER, SUBSTR, LENGTH, TRIM 등).",
    "숫자형 함수": "숫자를 입력받아 처리하는 단일행 함수(ROUND, TRUNC, CEIL, FLOOR, MOD 등).",
    "LOWER": "문자열을 소문자로 변환.",
    "UPPER": "문자열을 대문자로 변환.",
    "ASCII": "문자의 ASCII 코드 값을 반환. 반대 변환은 CHR(Oracle) / CHAR(SQL Server).",
    "CONCAT": "두 문자열을 결합. Oracle CONCAT은 인자 2개만 받으며 || 연산자와 같다. SQL Server는 + 연산자도 사용.",
    "SUBSTR": "SUBSTR(문자열, 시작위치[, 길이]) — 부분 문자열 추출. 위치는 1부터. SQL Server는 SUBSTRING.",
    "SUBSTR 음수 위치": "Oracle SUBSTR의 시작 위치가 음수면 문자열 끝에서부터 센다(SUBSTR('ABCDE', -2) = 'DE').",
    "LENGTH": "문자열의 문자 수를 반환(Oracle). SQL Server는 LEN.",
    "LEN": "SQL Server의 문자열 길이 함수. 후행 공백은 세지 않는다.",
    "LENGTHB": "문자열의 바이트 수를 반환(Oracle).",
    "INSTR": "INSTR(문자열, 찾을문자열[, 시작, n번째]) — 위치 반환. 없으면 0.",
    "LPAD": "LPAD(문자열, n, 채움문자) — 왼쪽을 채워 전체 길이를 n으로 맞춤. RPAD는 오른쪽.",
    "LTRIM": "LTRIM(문자열[, 문자집합]) — 왼쪽에서 집합에 속한 문자를 연속으로 제거. 생략 시 공백 제거.",
    "RTRIM": "RTRIM(문자열[, 문자집합]) — 오른쪽에서 집합에 속한 문자를 연속으로 제거.",
    "TRIM": "TRIM([LEADING|TRAILING|BOTH] 'x' FROM 문자열) — 양쪽(기본) 공백 또는 지정한 한 문자를 제거.",
    "REPLACE": "REPLACE(문자열, 찾을, 바꿀) — 일치하는 부분을 모두 치환. 바꿀 문자열을 생략하면 삭제.",
    # FN2 숫자
    "ROUND": "ROUND(n[, d]) — 소수점 d자리로 반올림. d가 음수면 정수부 자리에서 반올림(ROUND(1234.5, -2) = 1200).",
    "TRUNC": "TRUNC(n[, d]) — 소수점 d자리 아래를 버림(절삭). 날짜에도 사용 가능.",
    "CEIL": "n 이상인 가장 작은 정수(올림). CEIL(-1.5) = -1. SQL Server는 CEILING.",
    "FLOOR": "n 이하인 가장 큰 정수(내림). FLOOR(-1.5) = -2.",
    "MOD": "MOD(m, n) — m을 n으로 나눈 나머지. SQL Server는 % 연산자.",
    "문자형 MIN/MAX": "문자 컬럼의 MIN/MAX는 문자열 사전순 기준이다('9' > '10', 'B' > 'AZ').",
    # FN3 날짜
    "SYSDATE": "Oracle의 현재 날짜·시각. SQL Server는 GETDATE().",
    "Oracle 날짜 연산": "DATE + n은 n일 후, DATE + n/24는 n시간 후, DATE - DATE는 두 날짜 사이의 일수(숫자).",
    "TO_CHAR": "날짜·숫자를 지정한 포맷의 문자열로 변환(TO_CHAR(SYSDATE, 'YYYY-MM-DD')).",
    "Oracle 날짜 포맷": "TO_CHAR/TO_DATE의 포맷 모델 — YYYY, MM, DD, HH24, MI, SS, DY, MON 등.",
    "TO_DATE": "문자열을 지정한 포맷의 DATE로 변환(TO_DATE('20240131', 'YYYYMMDD')).",
    "TO_DATE 기본값": "포맷에서 생략된 요소는 기본값으로 채워진다 — 월·일 생략 시 '현재 월의 1일', 시각 생략 시 00:00:00.",
    "EXTRACT": "EXTRACT(YEAR | MONTH | DAY FROM 날짜) — 날짜에서 특정 요소를 숫자로 추출.",
    "DATE_FORMAT": "MySQL의 날짜 포맷 함수(DATE_FORMAT(d, '%Y-%m-%d')). Oracle은 TO_CHAR, SQL Server는 FORMAT/CONVERT를 쓴다.",
    "날짜 ROUND": "ROUND(날짜[, 단위]) — 날짜를 지정 단위로 반올림(기본 일 단위, 정오 기준; 'MM'은 16일 기준).",
    "날짜 TRUNC": "TRUNC(날짜[, 단위]) — 날짜를 지정 단위로 절삭(기본은 시각 제거 → 그날 00:00:00; 'MM'은 그 달 1일).",
    # FN4 조건·NULL 함수
    "CASE": "조건에 따라 다른 값을 반환하는 ANSI 표준 조건식. Simple CASE와 Searched CASE가 있으며 ELSE 생략 시 NULL.",
    "DECODE": "Oracle 전용 조건 함수 DECODE(식, 값1, 결과1, …, 기본값). 등가 비교만 가능하고 NULL과 NULL을 같다고 본다.",
    "NVL": "NVL(a, b) — a가 NULL이면 b, 아니면 a(Oracle). SQL Server는 ISNULL.",
    "NVL2": "NVL2(a, b, c) — a가 NULL이 아니면 b, NULL이면 c(Oracle).",
    "COALESCE": "COALESCE(a, b, c, …) — 처음으로 NULL이 아닌 인자를 반환하는 ANSI 표준 함수.",
    "NULLIF": "NULLIF(a, b) — a와 b가 같으면 NULL, 다르면 a를 반환.",
    # FN5 정규표현식
    "정규표현식": "문자열 패턴을 메타문자로 기술하는 표현식. Oracle의 REGEXP_* 함수에서 사용한다.",
    "정규식 메타문자": "정규표현식의 특수 기호 — . * + ? ^ $ [] {} | () \\d \\w 등.",
    "정규식 *": "앞 패턴이 0회 이상 반복.",
    "정규식 +": "앞 패턴이 1회 이상 반복.",
    "정규식 ?": "앞 패턴이 0회 또는 1회.",
    "정규식 ^": "문자열의 시작 위치(대괄호 안 [^...]에서는 부정).",
    "정규식 $": "문자열의 끝 위치.",
    "정규식 \\w": "단어 문자 [A-Za-z0-9_] 하나.",
    "정규식 {m,}": "앞 패턴이 m회 이상 반복({m}은 정확히 m회, {m,n}은 m~n회).",
    "정규표현식 함수": "Oracle 정규식 함수군 — REGEXP_LIKE, REGEXP_REPLACE, REGEXP_SUBSTR, REGEXP_INSTR, REGEXP_COUNT.",
    "REGEXP_LIKE": "REGEXP_LIKE(문자열, 패턴) — 패턴 일치 여부를 판단하는 조건(WHERE에서 사용).",
    "REGEXP_REPLACE": "REGEXP_REPLACE(문자열, 패턴, 바꿀문자열) — 패턴과 일치하는 부분을 치환.",
    "REGEXP_SUBSTR": "REGEXP_SUBSTR(문자열, 패턴[, 시작, n번째]) — 패턴과 일치하는 부분 문자열 반환.",
    "REGEXP_INSTR": "REGEXP_INSTR(문자열, 패턴[, 시작, n번째]) — 패턴이 일치하는 위치 반환(없으면 0).",
    "REGEXP_COUNT": "REGEXP_COUNT(문자열, 패턴) — 패턴이 일치하는 횟수 반환.",
}

RULES = {
    "SQL 논리 실행 순서": dict(
        why="별칭을 어디서 쓸 수 있는지, WHERE에 집계함수를 못 쓰는 이유, ORDER BY가 SELECT 별칭을 쓸 수 있는 이유가 모두 이 순서 하나로 설명된다.",
        rules=["FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY", "작성 순서(SELECT부터)와 논리 실행 순서는 다르다",
               "앞 단계는 뒤 단계에서 만든 것(별칭, 집계)을 볼 수 없다"],
        traps=["WHERE에서 SELECT 별칭 사용 불가, ORDER BY에서는 사용 가능.",
               "WHERE에서 집계함수 사용 불가 → HAVING 사용.",
               "실행 순서(HAVING이 SELECT보다 먼저)는 '학습 순서'가 아니다 — 학습은 SELECT부터."],
        examples=[{"sql": "SELECT deptno, SUM(sal) AS total\n  FROM emp\n WHERE sal > 1000\n GROUP BY deptno\nHAVING SUM(sal) > 5000\n ORDER BY total DESC;",
                   "explain": "평가: FROM emp → WHERE sal>1000 → GROUP BY deptno → HAVING SUM(sal)>5000 → SELECT(별칭 total 생성) → ORDER BY total"}],
    ),
    "SELECT": dict(
        why="모든 SQL 단원의 출발점. 현행 증거는 '단독 문제'가 아니라 다른 Concept 문제 속에 녹아 있다.",
        rules=["SELECT 목록 → FROM → [WHERE] → [GROUP BY] → [HAVING] → [ORDER BY] 순으로 작성"],
    ),
    "ALIAS": dict(
        rules=["컬럼 별칭: 컬럼 [AS] 별칭", "공백·특수문자·대소문자 유지 시 큰따옴표", "Oracle 테이블 별칭에는 AS 불가"],
        traps=["별칭은 WHERE·GROUP BY에서 쓸 수 없고 ORDER BY에서는 쓸 수 있다."],
    ),
    "DISTINCT": dict(
        rules=["SELECT 바로 뒤에 한 번만 사용", "지정한 모든 컬럼 조합 기준 중복 제거", "NULL끼리는 같은 값으로 취급"],
        traps=["SELECT DISTINCT a, b는 a만이 아니라 (a, b) 조합 기준으로 중복을 제거한다."],
    ),
    "공집합": dict(
        why="0행 상황에서 집계·스칼라 서브쿼리·NOT IN의 반환값이 현행 회차에서 반복 출제(3회).",
        rules=["GROUP BY 없는 집계 + 0행 → 1행 반환(COUNT=0, 나머지 NULL)", "GROUP BY 있는 집계 + 0행 → 0행",
               "스칼라 서브쿼리 결과가 0행이면 NULL"],
        traps=["SELECT SUM(sal) FROM emp WHERE 1=2 → NULL 1행 (0행이 아님)",
               "SELECT COUNT(*) FROM emp WHERE 1=2 → 0 (NULL 아님)"],
    ),
    "CHAR": dict(
        rules=["고정 길이, 남는 자리를 공백으로 채움", "CHAR끼리 비교는 짧은 쪽에 공백을 붙여 비교"],
        traps=["CHAR(5)에 'AB' 저장 → 'AB   ' (LENGTH = 5)."],
    ),
    "문자 비교": dict(
        rules=["CHAR vs CHAR: 공백 패딩 비교 → 'A' = 'A  ' TRUE", "VARCHAR가 포함되면 비패딩 비교 → 'A' ≠ 'A  '"],
        traps=["같아 보이는 두 문자열도 VARCHAR 비교에서는 후행 공백 때문에 다르다."],
    ),
    "암시적 형변환": dict(
        rules=["Oracle: 문자 vs 숫자 비교 시 문자를 숫자로 변환", "날짜와 문자 비교 시 문자를 날짜로 변환(NLS 포맷 의존)"],
        traps=["WHERE char_col = 100 은 char_col에 숫자로 바꿀 수 없는 값이 있으면 오류(ORA-01722).",
               "인덱스 컬럼에 암시적 형변환이 일어나면 인덱스를 사용하지 못할 수 있다."],
    ),
    "NULL": dict(
        why="SQLD에서 가장 여러 단원(WHERE·집계·JOIN·정렬·함수·방언)을 가로지르는 허브. 함정 문제의 절반 이상이 NULL에서 나온다.",
        rules=["NULL 비교 결과는 TRUE/FALSE가 아니라 UNKNOWN이 될 수 있다", "WHERE·HAVING·ON은 TRUE인 행만 통과시킨다",
               "NULL 판별은 IS NULL / IS NOT NULL", "NULL이 산술 연산에 들어가면 결과도 NULL",
               "집계 함수는 NULL을 무시한다(COUNT(*) 제외)"],
        traps=["NULL = NULL은 TRUE가 아니다(UNKNOWN).", "NOT IN (…, NULL)은 항상 0행.",
               "COUNT(col)은 NULL을 제외한다 — COUNT(*)와 결과가 다를 수 있다.",
               "NULL이 산술 연산에 들어가면 결과도 NULL(SAL + COMM이 NULL).",
               "AVG(col)은 NULL 행을 분모에서도 제외한다."],
        dialect=["Oracle은 빈 문자열('')을 NULL로 처리, SQL Server는 별개 값.",
                 "Oracle은 NULL을 가장 큰 값으로 정렬(ASC 마지막), SQL Server는 가장 작은 값(ASC 처음)."],
        examples=[{"sql": "SELECT COUNT(*), COUNT(comm), AVG(comm) FROM emp;",
                   "explain": "comm이 NULL인 행은 COUNT(comm)과 AVG(comm)의 분자·분모 모두에서 빠진다"},
                  {"sql": "SELECT * FROM emp WHERE comm = NULL;", "explain": "항상 0행 — IS NULL을 써야 한다"}],
    ),
    "NULL 비교": dict(
        rules=["col = NULL, col <> NULL → UNKNOWN", "UNKNOWN 행은 WHERE에서 제외"],
        traps=["WHERE col <> 10 은 col이 NULL인 행을 포함하지 않는다."],
    ),
    "UNKNOWN": dict(
        why="NOT IN + NULL, CHECK 제약 통과, OUTER JOIN 필터 등 NULL 함정의 공통 원리.",
        rules=["TRUE AND UNKNOWN = UNKNOWN, FALSE AND UNKNOWN = FALSE", "TRUE OR UNKNOWN = TRUE, FALSE OR UNKNOWN = UNKNOWN",
               "NOT UNKNOWN = UNKNOWN", "WHERE/HAVING/ON은 TRUE만 통과, CHECK 제약은 FALSE만 거부(UNKNOWN 통과)"],
        traps=["CHECK (sal > 0) 컬럼에 NULL은 입력된다(UNKNOWN은 거부되지 않음)."],
    ),
    "IS NULL": dict(rules=["NULL 판별은 반드시 IS NULL / IS NOT NULL"],
                    traps=["DECODE는 NULL끼리 같다고 보지만 = 비교는 그렇지 않다."]),
    "NULL 산술 연산": dict(
        rules=["NULL + 1 = NULL, NULL * 0 = NULL", "NULL을 0으로 보고 계산하려면 NVL/COALESCE로 치환"],
        traps=["SAL + COMM에서 COMM이 NULL인 사원은 결과가 NULL → NVL(COMM, 0) 필요."],
    ),
    "빈 문자열과 NULL(Oracle)": dict(
        rules=["Oracle: '' 는 NULL", "SQL Server: '' 는 길이 0인 일반 문자열"],
        traps=["Oracle에서 WHERE col = '' 는 항상 0행(col = NULL과 같음).", "Oracle에서 LENGTH('')는 NULL."],
    ),
    "NULL 정렬": dict(
        rules=["Oracle: NULL이 가장 큼 → ASC 마지막 / DESC 처음", "SQL Server: NULL이 가장 작음 → ASC 처음 / DESC 마지막",
               "Oracle은 NULLS FIRST / NULLS LAST로 위치 지정 가능"],
        traps=["SQL Server에는 NULLS FIRST/LAST 문법이 없다(CASE 정렬로 우회)."],
    ),
    "WHERE": dict(
        why="행 필터의 기본이며 NULL·IN·LIKE·BETWEEN·서브쿼리 등 대부분의 조건 문제가 WHERE에서 나온다.",
        rules=["조건이 TRUE인 행만 통과(FALSE·UNKNOWN 제외)", "집계 함수·SELECT 별칭 사용 불가"],
    ),
    "AND/OR 우선순위": dict(
        rules=["NOT > AND > OR", "괄호로 우선순위를 명시하는 것이 안전"],
        traps=["WHERE a = 1 OR b = 2 AND c = 3 은 a = 1 OR (b = 2 AND c = 3)으로 해석된다."],
    ),
    "BETWEEN": dict(
        rules=["BETWEEN a AND b = (>= a AND <= b), 양 끝 포함", "a > b면 결과 0행"],
        traps=["NOT BETWEEN a AND b = (< a OR > b).", "DATE 컬럼 BETWEEN은 종료일의 00:00:00까지만 포함."],
    ),
    "IN": dict(
        rules=["col IN (a, b) = col = a OR col = b", "목록의 NULL은 어떤 값과도 일치하지 않음"],
    ),
    "NOT IN": dict(
        why="NOT IN + NULL은 SQLD 대표 함정. 현행 회차에서 서브쿼리와 결합해 반복 출제된다.",
        rules=["col NOT IN (a, b) = col <> a AND col <> b", "목록/서브쿼리 결과에 NULL이 하나라도 있으면 col <> NULL이 UNKNOWN → 전체가 UNKNOWN 또는 FALSE"],
        traps=["NOT IN (1, 2, NULL)은 항상 0행.", "NOT IN 서브쿼리 결과에 NULL이 섞이면 0행 → NOT EXISTS 또는 IS NOT NULL 조건으로 회피.",
               "col 자체가 NULL인 행도 NOT IN 결과에 나오지 않는다."],
        examples=[{"sql": "SELECT ename FROM emp\n WHERE empno NOT IN (SELECT mgr FROM emp);",
                   "explain": "mgr 컬럼에 NULL(최상위 관리자)이 있으면 결과는 0행"}],
    ),
    "IN + NULL": dict(rules=["IN 목록의 NULL은 무시되는 것과 같다(어떤 행과도 일치하지 않음)"],
                      traps=["WHERE col IN (NULL)은 col이 NULL인 행도 반환하지 않는다."]),
    "LIKE": dict(
        rules=["% = 0개 이상 문자, _ = 정확히 1문자", "와일드카드 없는 LIKE는 = 와 같다"],
        traps=["LIKE '_A%'는 두 번째 글자가 A인 문자열.", "% 자체를 찾으려면 ESCAPE 필요."],
    ),
    "LIKE ESCAPE": dict(
        examples=[{"sql": "SELECT * FROM t WHERE code LIKE 'A#_%' ESCAPE '#';", "explain": "'A_'로 시작하는 문자열(밑줄 자체를 문자로 취급)"}],
    ),
    "날짜 경계": dict(
        rules=["DATE에는 시각이 포함된다", "종료일 포함 조회는 '< 종료일 + 1' 또는 TRUNC 사용"],
        traps=["BETWEEN TO_DATE('20240101','YYYYMMDD') AND TO_DATE('20240131','YYYYMMDD')는 1월 31일 09:00 데이터를 누락."],
    ),
    "SELECT 별칭 WHERE 사용 불가": dict(
        rules=["WHERE는 SELECT보다 먼저 평가 → 별칭이 아직 없다"],
        traps=["SELECT sal*12 AS annual FROM emp WHERE annual > 30000 → 오류."],
    ),
    "ORDER BY": dict(
        why="정렬 규칙(별칭·순서번호·NULL 위치·다중 키)은 Top-N, 윈도우 함수, 집합 연산자 문제의 전제이다.",
        rules=["기본 ASC", "컬럼명·별칭·순서번호·표현식 사용 가능", "SELECT에 없는 컬럼으로도 정렬 가능(단, DISTINCT·GROUP BY·집합 연산 시 제한)"],
        traps=["ORDER BY 2는 SELECT 목록 두 번째 컬럼. 목록 개수보다 큰 번호는 오류.",
               "ORDER BY는 논리적으로 마지막이라 SELECT 별칭을 쓸 수 있다."],
    ),
    "ORDER BY 별칭": dict(rules=["ORDER BY는 SELECT 이후 평가 → 별칭 사용 가능"]),
    "다중 열 ORDER BY": dict(traps=["ORDER BY a, b DESC는 a는 ASC, b만 DESC다."]),
    "SUBSTR": dict(
        rules=["SUBSTR(s, 시작, 길이), 위치는 1부터", "길이 생략 시 끝까지", "Oracle은 음수 시작 위치 가능(끝에서부터)"],
        examples=[{"sql": "SELECT SUBSTR('SQLDEVELOPER', 4, 3) FROM dual;", "explain": "'DEV'"}],
    ),
    "LTRIM": dict(
        rules=["두 번째 인자는 '문자열'이 아니라 '문자 집합' — 집합에 속한 문자가 나오는 동안 계속 제거"],
        traps=["LTRIM('xxyAxy', 'xy') = 'Axy' (왼쪽의 x, y를 모두 제거하고 A에서 멈춤)."],
    ),
    "TRIM": dict(
        rules=["기본은 양쪽 공백 제거", "TRIM('x' FROM s)처럼 지정할 수 있는 문자는 한 개"],
        traps=["Oracle TRIM은 제거 문자로 한 글자만 지정 가능(LTRIM/RTRIM은 집합 지정 가능)."],
    ),
    "ROUND": dict(
        rules=["ROUND(n, d): d자리에서 반올림", "d 음수 → 정수부 반올림"],
        examples=[{"sql": "ROUND(123.456, 2) → 123.46\nROUND(123.456, -1) → 120\nROUND(125, -1) → 130", "explain": "자릿수 인자의 부호에 주의"}],
    ),
    "TRUNC": dict(examples=[{"sql": "TRUNC(123.456, 1) → 123.4\nTRUNC(-1.7) → -1", "explain": "절삭은 0 방향"}]),
    "CEIL": dict(traps=["CEIL(-1.5) = -1, FLOOR(-1.5) = -2 (음수에서 헷갈리기 쉬움)."]),
    "FLOOR": dict(traps=["FLOOR(-1.5) = -2."]),
    "MOD": dict(traps=["Oracle MOD(-7, 3) = -1 (나머지 부호는 피제수 부호)."]),
    "Oracle 날짜 연산": dict(
        rules=["DATE + 1 = 1일 후", "DATE + 1/24 = 1시간 후", "DATE - DATE = 일수(소수 포함)"],
        traps=["DATE + DATE는 오류."],
    ),
    "TO_DATE 기본값": dict(
        rules=["TO_DATE('2024', 'YYYY') → 2024년 '현재 월' 1일 00:00:00"],
        traps=["월을 생략하면 1월이 아니라 '현재 월'이 된다."],
    ),
    "CASE": dict(
        why="조건 분기의 표준 문법. DECODE·ORDER BY CASE·수동 PIVOT으로 이어진다.",
        rules=["Simple CASE: CASE expr WHEN v1 THEN r1 … END", "Searched CASE: CASE WHEN 조건 THEN r … END",
               "위에서부터 처음 만족하는 WHEN 하나만 적용", "ELSE 생략 시 NULL"],
        traps=["Simple CASE에서 WHEN NULL은 절대 일치하지 않는다(= 비교이므로). DECODE와 다름.",
               "ELSE가 없으면 일치하지 않는 행은 NULL."],
        examples=[{"sql": "SELECT ename,\n       CASE WHEN sal >= 3000 THEN 'HIGH'\n            WHEN sal >= 1000 THEN 'MID'\n            ELSE 'LOW' END AS grade\n  FROM emp;", "explain": "sal=3000은 첫 WHEN에서 'HIGH'로 끝난다"}],
    ),
    "DECODE": dict(
        rules=["DECODE(식, v1, r1, v2, r2, …, 기본값)", "등가 비교만 가능", "NULL과 NULL을 같다고 본다"],
        traps=["기본값을 생략하면 일치하지 않을 때 NULL."],
    ),
    "NVL": dict(
        why="NULL 치환의 기본 함수. COALESCE·NVL2·ISNULL과의 차이가 비교 문제로 나온다.",
        rules=["NVL(a, b): a가 NULL이면 b", "a와 b의 자료형이 호환되어야 함"],
        traps=["NVL(comm, 0)을 SUM 안에 쓰든 밖에 쓰든 SUM 결과는 같지만, 행이 없을 때는 SUM 결과 자체가 NULL이다."],
    ),
    "NVL2": dict(rules=["NVL2(a, b, c): a NOT NULL → b, a NULL → c"], traps=["NVL과 인자 의미가 다르다(첫 인자가 반환값이 아님)."]),
    "COALESCE": dict(rules=["인자 중 처음으로 NULL이 아닌 값", "모두 NULL이면 NULL", "ANSI 표준 — Oracle/SQL Server 모두 지원"]),
    "NULLIF": dict(rules=["NULLIF(a, b): a = b면 NULL, 아니면 a"],
                   examples=[{"sql": "NULLIF(10, 10) → NULL\nNULLIF(10, 20) → 10", "explain": "0으로 나누기 방지: x / NULLIF(y, 0)"}]),
    "정규식 메타문자": dict(
        rules=[". 임의 1문자, * 0회+, + 1회+, ? 0~1회", "^ 시작, $ 끝, [abc] 문자 집합, [^abc] 부정", "{m} m회, {m,} m회 이상, {m,n} m~n회",
               "\\d 숫자, \\w 단어 문자, | OR, () 그룹"],
        traps=["기본 매칭은 탐욕적(greedy) — 가능한 한 길게 일치한다."],
    ),
    "REGEXP_SUBSTR": dict(
        examples=[{"sql": "SELECT REGEXP_SUBSTR('A-12-345', '[0-9]+', 1, 2) FROM dual;", "explain": "두 번째 숫자 덩어리 '345'"}],
    ),
    "REGEXP_COUNT": dict(
        examples=[{"sql": "SELECT REGEXP_COUNT('banana', 'an') FROM dual;", "explain": "2"}],
    ),
}

RULES.update({
    "테이블 별칭": dict(rules=["FROM t a 형태", "별칭을 지정하면 그 문장에서는 원래 테이블명 대신 별칭을 써야 함(Oracle)"],
                   traps=["Oracle에서 FROM emp AS e는 오류(테이블 별칭에 AS 불가).", "별칭을 붙인 뒤 emp.ename처럼 원래 테이블명으로 참조하면 오류."]),
    "와일드카드": dict(rules=["% : 0개 이상 임의 문자", "_ : 정확히 1개 임의 문자"],
                  traps=["LIKE 'A%'는 'A' 자체도 포함(% = 0개 이상).", "LIKE '__'는 정확히 두 글자."]),
    "정규표현식": dict(rules=["LIKE보다 강력한 패턴 언어", "Oracle REGEXP_* 함수의 패턴 인자로 사용"],
                  traps=["정규식 패턴은 기본적으로 부분 일치 — 전체 일치는 ^…$로 고정."]),
    "정규식 *": dict(rules=["앞 문자/그룹 0회 이상"], traps=["'ab*'는 'a'에도 일치한다(b가 0회)."]),
    "정규표현식 함수": dict(rules=["REGEXP_LIKE: 조건", "REGEXP_REPLACE: 치환", "REGEXP_SUBSTR: 추출", "REGEXP_INSTR: 위치", "REGEXP_COUNT: 횟수"],
                      traps=["REGEXP_LIKE는 값을 반환하는 함수가 아니라 WHERE 조건식으로 쓴다."]),
})
