"""Merged rule/trap content and search aliases."""

from . import content_manage, content_modeling, content_sql_adv, content_sql_basic

_PARTS = (content_modeling, content_sql_basic, content_sql_adv, content_manage)

DEFINITIONS = {}
RICH_RULES = {}
for _part in _PARTS:
    for _name, _text in _part.DEFS.items():
        if _name in DEFINITIONS:
            raise ValueError(f"duplicate definition: {_name}")
        DEFINITIONS[_name] = _text
    for _name, _rule in _part.RULES.items():
        if _name in RICH_RULES:
            raise ValueError(f"duplicate rule: {_name}")
        RICH_RULES[_name] = _rule

# Search aliases (also used to resolve free-text concept lists such as 20_Hubs_Rules).
ALIASES = {
    "NULL": ["널", "null 값"],
    "UNKNOWN": ["3값 논리", "3-valued logic", "삼값 논리"],
    "NVL": ["ISNULL"],
    "COALESCE": ["NVL/COALESCE"],
    "COUNT(열)": ["COUNT(col)", "COUNT(컬럼)"],
    "IN + NULL": ["IN+NULL"],
    "IN·NOT IN": ["IN / NOT IN", "IN/NOT IN"],
    "윈도우 함수": ["분석 함수", "window function", "analytic function"],
    "OVER 절": ["OVER"],
    "순위 함수": ["RANK/DENSE_RANK/ROW_NUMBER", "그룹 내 순위 함수"],
    "행 순서 함수": ["LAG/LEAD", "그룹 내 행 순서 함수"],
    "ROWS/RANGE 프레임": ["ROWS/RANGE", "윈도우 프레임", "frame"],
    "계층형 질의": ["hierarchical query", "CONNECT BY 계층", "계층 쿼리"],
    "서브쿼리": ["subquery", "부속질의"],
    "Transaction": ["트랜잭션"],
    "WITH 절": ["WITH/CTE", "subquery factoring"],
    "CTE": ["공통 테이블 표현식"],
    "재귀 CTE": ["recursive CTE", "재귀 WITH"],
    "Top-N": ["TOP N", "상위 N"],
    "FETCH FIRST": ["OFFSET FETCH", "FETCH NEXT"],
    "MINUS": ["차집합"],
    "EXCEPT": ["차집합"],
    "Oracle (+) OUTER JOIN": ["Oracle (+)", "(+)"],
    "Oracle DDL 자동 커밋": ["DDL 자동 커밋", "DDL commit", "implicit commit"],
    "SQL 논리 실행 순서": ["실행 순서", "논리적 실행 순서", "execution order"],
    "집합 연산자": ["set operator"],
    "그룹함수 확장": ["ROLLUP/CUBE/GROUPING SETS"],
    "GROUP BY 확장": ["GROUP BY extension"],
    "집계 함수": ["aggregate", "그룹 함수"],
    "PK": ["기본키", "primary key", "주키"],
    "FK": ["외래키", "foreign key"],
    "후보키": ["candidate key"],
    "대리키": ["surrogate key"],
    "복합키": ["composite key"],
    "정규화": ["normalization"],
    "반정규화": ["역정규화", "denormalization"],
    "엔터티": ["entity", "엔티티"],
    "속성": ["attribute"],
    "인스턴스": ["instance"],
    "관계": ["relationship"],
    "ERD": ["E-R 다이어그램"],
    "IE 표기법": ["Crow's Foot", "까마귀발"],
    "Peter Chen 표기법": ["Chen 표기법"],
    "IDEFIX 표기법": ["IDEF1X"],
    "3단계 스키마": ["ANSI/SPARC"],
    "DCL": ["권한"],
    "TCL": ["트랜잭션 제어"],
    "DML": ["데이터 조작어"],
    "DDL": ["데이터 정의어"],
    "CTAS": ["CREATE TABLE AS SELECT"],
    "SELECT INTO": ["SELECT INTO 테이블 복사"],
    "LEN": ["SQL Server 길이"],
    "SUBSTR": ["SUBSTRING"],
    "CEIL": ["CEILING"],
    "SYSDATE": ["GETDATE"],
    "INSTR": ["CHARINDEX"],
    "CONCAT": ["||", "문자열 결합"],
    "순환 관계(자기참조)": ["self-referencing", "자기참조", "재귀 관계", "부모-자식 구조"],
    "셀프 조인": ["self join", "SELF JOIN"],
    "CARTESIAN PRODUCT": ["카티션 곱", "카테시안 곱"],
    "빈 문자열과 NULL(Oracle)": ["빈 문자열", "empty string", "Oracle 빈 문자열"],
    "NULL 정렬": ["NULL 정렬 차이"],
    "PIVOT·UNPIVOT": ["PIVOT/UNPIVOT"],
    "격리성": ["고립성", "isolation"],
    "지속성": ["영속성", "durability"],
    "원자성": ["atomicity"],
    "일관성": ["consistency"],
    "GRANT OPTION": ["WITH GRANT OPTION"],
    "ROW_NUMBER": ["ROWNUMBER"],
    "M:N 해소": ["다대다 해소"],
    "이상현상": ["anomaly", "삽입 이상", "갱신 이상", "삭제 이상"],
    "DECODE": ["조건 표현식"],
}

# Free-text tokens used in 20_Hubs_Rules 'Linked Concepts' -> concept names.
HUB_TOKEN_MAP = {
    "UNKNOWN": ["UNKNOWN"],
    "NOT IN": ["NOT IN"],
    "IN+NULL": ["IN + NULL"],
    "COUNT(열)": ["COUNT(열)"],
    "AVG": ["AVG"],
    "GROUP BY NULL": ["GROUP BY NULL"],
    "DISTINCT NULL": ["DISTINCT NULL"],
    "ORDER BY": ["ORDER BY"],
    "OUTER JOIN": ["OUTER JOIN"],
    "NVL/COALESCE": ["NVL", "COALESCE"],
    "SELECT": ["SELECT"],
    "WHERE": ["WHERE"],
    "GROUP BY": ["GROUP BY"],
    "HAVING": ["HAVING"],
    "SELECT 별칭 WHERE 사용 불가": ["SELECT 별칭 WHERE 사용 불가"],
    "ORDER BY 별칭": ["ORDER BY 별칭"],
    "INNER/OUTER/CROSS/NATURAL": ["INNER JOIN", "OUTER JOIN", "CROSS JOIN", "NATURAL JOIN"],
    "ON": ["ON"],
    "USING": ["USING"],
    "FK": ["FK"],
    "정규화": ["정규화"],
    "ON vs WHERE": ["ON vs WHERE"],
    "단일행": ["단일행 서브쿼리"],
    "다중행": ["다중행 서브쿼리"],
    "상관": ["상관 서브쿼리"],
    "스칼라": ["스칼라 서브쿼리"],
    "인라인뷰": ["인라인 뷰"],
    "IN/ANY/ALL/EXISTS": ["IN", "ANY", "ALL", "EXISTS"],
    "WITH/CTE": ["WITH 절", "CTE"],
    "COUNT": ["COUNT"],
    "SUM": ["SUM"],
    "MIN/MAX": ["MIN", "MAX"],
    "ROLLUP/CUBE/GROUPING SETS": ["ROLLUP", "CUBE", "GROUPING SETS"],
    "공집합 집계": ["공집합 집계"],
    "RANK/DENSE_RANK/ROW_NUMBER": ["RANK", "DENSE_RANK", "ROW_NUMBER"],
    "LAG/LEAD": ["LAG", "LEAD"],
    "PARTITION BY": ["PARTITION BY"],
    "ROWS/RANGE": ["ROWS/RANGE 프레임"],
    "START WITH": ["START WITH"],
    "CONNECT BY": ["CONNECT BY"],
    "PRIOR": ["PRIOR"],
    "LEVEL": ["LEVEL"],
    "NOCYCLE": ["NOCYCLE"],
    "CONNECT_BY_*": ["CONNECT_BY_ISLEAF", "CONNECT_BY_ISCYCLE", "CONNECT_BY_ROOT"],
    "ORDER SIBLINGS BY": ["ORDER SIBLINGS BY"],
    "ACID": ["ACID"],
    "COMMIT": ["COMMIT"],
    "ROLLBACK": ["ROLLBACK"],
    "SAVEPOINT": ["SAVEPOINT"],
    "AUTO COMMIT": ["AUTO COMMIT"],
    "DDL 자동 커밋": ["Oracle DDL 자동 커밋"],
    "MINUS↔EXCEPT": ["MINUS", "EXCEPT"],
    "ROWNUM/TOP/FETCH FIRST": ["ROWNUM", "TOP", "FETCH FIRST"],
    "Oracle (+)": ["Oracle (+) OUTER JOIN"],
    "NULL 정렬": ["NULL 정렬"],
}

# 20_Hubs_Rules 'Hub' -> concept names that carry the hub card.
HUB_NODE_MAP = {
    "NULL": ["NULL"],
    "SQL 논리 실행 순서": ["SQL 논리 실행 순서"],
    "JOIN": ["JOIN"],
    "서브쿼리": ["서브쿼리"],
    "집계·GROUP BY": ["집계 함수", "GROUP BY"],
    "윈도우 함수": ["윈도우 함수"],
    "계층형 질의": ["계층형 질의"],
    "Transaction": ["Transaction"],
    "DBMS 방언": ["ANSI/ISO SQL", "Oracle SQL", "SQL Server"],
}

# Curated non-DAG "related concept" links (RELATED_TO metadata). Shown in the detail panel's
# connection map; never used as prerequisite edges.
RELATED = {
    "NULL": ["UNKNOWN", "WHERE", "IN·NOT IN", "NOT IN", "IN + NULL", "COUNT", "COUNT(열)", "AVG", "GROUP BY NULL",
             "DISTINCT NULL", "OUTER JOIN", "NVL", "COALESCE", "빈 문자열과 NULL(Oracle)", "CHECK", "UNIQUE",
             "NULL 함정 종합", "NULL 처리 DBMS 차이", "NULL 정렬 DBMS 차이"],
    "계층형 질의": ["순환 관계(자기참조)", "셀프 조인", "재귀 CTE", "WHERE", "ORDER BY"],
    "윈도우 함수": ["집계 함수", "GROUP BY", "Top-N", "ORDER BY"],
    "JOIN": ["정규화", "FK", "서브쿼리", "집합 연산자"],
    "서브쿼리": ["JOIN", "WITH 절", "NOT IN", "VIEW"],
    "Transaction": ["DML", "DDL", "Oracle DDL 자동 커밋", "AUTO COMMIT", "DDL 커밋 동작 차이"],
    "ROWNUM": ["ROW_NUMBER", "Top-N 문법 차이", "인라인 뷰"],
    "GROUP BY": ["윈도우 함수", "PIVOT", "DISTINCT"],
    "SQL 논리 실행 순서": ["별칭 가시성 종합", "ROWNUM", "윈도우 함수"],
    "OUTER JOIN": ["OUTER JOIN 필터 위치 종합", "스칼라 서브쿼리", "NVL"],
    "DISTINCT": ["UNION", "GROUP BY", "COUNT(DISTINCT)"],
    "CTAS": ["SELECT INTO", "PK 제약 비상속", "NOT NULL"],
    "DELETE": ["TRUNCATE", "DROP"],
}
