"""ANSI / Oracle / SQL Server differences (metadata, never DAG edges)."""

DIALECTS = [
    {"id": "dl_null_func", "topic": "NULL 치환 함수",
     "concepts": ["NVL", "COALESCE", "NVL2", "NULL 처리 DBMS 차이"],
     "ansi": "COALESCE(a, b, …)", "oracle": "NVL(a, b), NVL2(a, b, c), COALESCE", "sqlserver": "ISNULL(a, b), COALESCE",
     "note": "COALESCE는 양쪽 모두 사용 가능한 표준 함수."},
    {"id": "dl_empty_string", "topic": "빈 문자열('')과 NULL",
     "concepts": ["빈 문자열과 NULL(Oracle)", "NULL", "NULL 처리 DBMS 차이"],
     "ansi": "''와 NULL은 다르다", "oracle": "''를 NULL로 처리 (LENGTH('') = NULL)", "sqlserver": "''는 길이 0 문자열 (LEN('') = 0)",
     "note": "Oracle에서 WHERE col = ''는 항상 0행."},
    {"id": "dl_null_sort", "topic": "NULL 정렬 위치",
     "concepts": ["NULL 정렬", "Oracle NULL 정렬", "SQL Server NULL 정렬", "NULLS FIRST", "NULLS LAST", "NULL 정렬 DBMS 차이"],
     "ansi": "NULLS FIRST / NULLS LAST (구현 정의)", "oracle": "NULL = 최댓값 → ASC 마지막 / DESC 처음, NULLS FIRST·LAST 지원",
     "sqlserver": "NULL = 최솟값 → ASC 처음 / DESC 마지막, NULLS FIRST·LAST 미지원",
     "note": "SQL Server에서 NULL을 뒤로 보내려면 ORDER BY CASE WHEN col IS NULL THEN 1 ELSE 0 END, col."},
    {"id": "dl_unique_null", "topic": "UNIQUE 제약과 NULL",
     "concepts": ["UNIQUE", "NULL 처리 DBMS 차이"],
     "ansi": "NULL은 서로 다른 값으로 간주(여러 개 허용)", "oracle": "NULL 여러 개 허용", "sqlserver": "UNIQUE 제약 컬럼에 NULL은 1개만",
     "note": ""},
    {"id": "dl_topn", "topic": "Top-N",
     "concepts": ["ROWNUM", "TOP", "FETCH FIRST", "LIMIT", "WITH TIES", "Top-N", "Top-N 문법 차이"],
     "ansi": "ORDER BY … FETCH FIRST n ROWS ONLY | WITH TIES", "oracle": "ROWNUM(인라인 뷰), 12c+ FETCH FIRST",
     "sqlserver": "SELECT TOP(n) [PERCENT] [WITH TIES], ORDER BY … OFFSET m ROWS FETCH NEXT n ROWS ONLY",
     "note": "LIMIT은 MySQL/PostgreSQL 문법."},
    {"id": "dl_minus", "topic": "차집합",
     "concepts": ["MINUS", "EXCEPT", "차집합 MINUS/EXCEPT 차이"],
     "ansi": "EXCEPT", "oracle": "MINUS (21c부터 EXCEPT도 지원)", "sqlserver": "EXCEPT",
     "note": "의미는 같다."},
    {"id": "dl_set_precedence", "topic": "집합 연산자 우선순위",
     "concepts": ["집합 연산자 우선순위"],
     "ansi": "INTERSECT가 UNION/EXCEPT보다 우선", "oracle": "모든 집합 연산자 우선순위 동일(위→아래)", "sqlserver": "INTERSECT 우선",
     "note": "괄호로 명시하는 것이 안전."},
    {"id": "dl_ddl_commit", "topic": "DDL과 트랜잭션",
     "concepts": ["Oracle DDL 자동 커밋", "DDL", "TRUNCATE", "SQL Server 트랜잭션", "DDL 커밋 동작 차이", "Oracle/SQL Server DDL 차이"],
     "ansi": "구현 정의", "oracle": "DDL 실행 전후 자동 COMMIT → ROLLBACK 불가",
     "sqlserver": "BEGIN TRAN 안의 DDL·TRUNCATE는 ROLLBACK 가능",
     "note": "Oracle에서 DML 후 DDL을 실행하면 앞선 DML도 확정된다."},
    {"id": "dl_autocommit", "topic": "AUTO COMMIT 기본값",
     "concepts": ["AUTO COMMIT", "SQL Server 트랜잭션", "Transaction", "DDL 커밋 동작 차이"],
     "ansi": "-", "oracle": "DML은 수동 COMMIT이 기본(도구 설정 SET AUTOCOMMIT)", "sqlserver": "AUTO COMMIT 모드가 기본, BEGIN TRAN으로 명시적 트랜잭션",
     "note": ""},
    {"id": "dl_savepoint", "topic": "SAVEPOINT 문법",
     "concepts": ["SAVEPOINT", "ROLLBACK TO SAVEPOINT"],
     "ansi": "SAVEPOINT s / ROLLBACK TO SAVEPOINT s", "oracle": "SAVEPOINT s / ROLLBACK TO s", "sqlserver": "SAVE TRANSACTION s / ROLLBACK TRANSACTION s",
     "note": ""},
    {"id": "dl_strlen", "topic": "문자열 길이",
     "concepts": ["LENGTH", "LEN", "LENGTHB", "문자열 함수 DBMS 차이"],
     "ansi": "CHAR_LENGTH", "oracle": "LENGTH(문자 수), LENGTHB(바이트 수)", "sqlserver": "LEN(후행 공백 제외), DATALENGTH(바이트)",
     "note": ""},
    {"id": "dl_concat", "topic": "문자열 결합",
     "concepts": ["CONCAT", "문자열 함수 DBMS 차이"],
     "ansi": "||", "oracle": "|| 또는 CONCAT(a, b) (인자 2개)", "sqlserver": "+ 또는 CONCAT(a, b, …)",
     "note": "SQL Server의 'A' + NULL은 NULL, CONCAT('A', NULL)은 'A'."},
    {"id": "dl_substr", "topic": "부분 문자열 / 위치",
     "concepts": ["SUBSTR", "INSTR", "문자열 함수 DBMS 차이"],
     "ansi": "SUBSTRING(s FROM p FOR n), POSITION", "oracle": "SUBSTR(s, p, n), INSTR(s, t)", "sqlserver": "SUBSTRING(s, p, n), CHARINDEX(t, s)",
     "note": "Oracle SUBSTR은 음수 시작 위치 지원."},
    {"id": "dl_date_now", "topic": "현재 날짜·날짜 연산",
     "concepts": ["SYSDATE", "Oracle 날짜 연산", "DATE"],
     "ansi": "CURRENT_TIMESTAMP, CURRENT_DATE", "oracle": "SYSDATE, DATE + n(일), ADD_MONTHS", "sqlserver": "GETDATE(), DATEADD(day, n, d), DATEDIFF",
     "note": ""},
    {"id": "dl_date_format", "topic": "날짜 → 문자 변환",
     "concepts": ["TO_CHAR", "DATE_FORMAT", "Oracle 날짜 포맷", "명시적 형변환"],
     "ansi": "CAST", "oracle": "TO_CHAR(d, 'YYYY-MM-DD'), TO_DATE", "sqlserver": "CONVERT(VARCHAR, d, 스타일), FORMAT(d, 'yyyy-MM-dd'), CAST",
     "note": "DATE_FORMAT은 MySQL 함수."},
    {"id": "dl_ceil_mod", "topic": "숫자 함수 이름",
     "concepts": ["CEIL", "MOD"],
     "ansi": "CEILING, MOD", "oracle": "CEIL, MOD(m, n)", "sqlserver": "CEILING, m % n",
     "note": ""},
    {"id": "dl_case_decode", "topic": "조건 분기",
     "concepts": ["CASE", "DECODE"],
     "ansi": "CASE", "oracle": "CASE, DECODE", "sqlserver": "CASE, IIF",
     "note": "DECODE는 Oracle 전용."},
    {"id": "dl_outer_join", "topic": "OUTER JOIN 표기",
     "concepts": ["Oracle (+) OUTER JOIN", "OUTER JOIN", "LEFT OUTER JOIN", "FULL OUTER JOIN", "OUTER JOIN 필터 위치 종합"],
     "ansi": "LEFT/RIGHT/FULL OUTER JOIN … ON", "oracle": "ANSI 문법 + 전통 (+) 표기(FULL 불가)", "sqlserver": "ANSI 문법 (구 *= 표기는 폐지)",
     "note": ""},
    {"id": "dl_row_in", "topic": "다중 컬럼(행값) IN",
     "concepts": ["행값 IN"],
     "ansi": "(a, b) IN ((1, 2), …)", "oracle": "지원", "sqlserver": "미지원(EXISTS로 우회)",
     "note": ""},
    {"id": "dl_like", "topic": "LIKE 패턴",
     "concepts": ["LIKE", "SQL Server LIKE []", "와일드카드"],
     "ansi": "%, _, ESCAPE", "oracle": "%, _, ESCAPE", "sqlserver": "%, _, [abc], [a-z], [^a], ESCAPE",
     "note": ""},
    {"id": "dl_regexp", "topic": "정규표현식 함수",
     "concepts": ["정규표현식 함수", "REGEXP_LIKE", "REGEXP_SUBSTR", "REGEXP_REPLACE", "REGEXP_INSTR", "REGEXP_COUNT"],
     "ansi": "SIMILAR TO / LIKE_REGEX", "oracle": "REGEXP_LIKE, REGEXP_SUBSTR, REGEXP_REPLACE, REGEXP_INSTR, REGEXP_COUNT",
     "sqlserver": "시험 범위 버전에는 정규식 함수 없음(LIKE 패턴 사용)",
     "note": "SQLD의 정규식 문제는 Oracle 기준."},
    {"id": "dl_hierarchy", "topic": "계층형 질의",
     "concepts": ["계층형 질의", "CONNECT BY", "재귀 CTE"],
     "ansi": "WITH RECURSIVE (재귀 CTE)", "oracle": "START WITH … CONNECT BY PRIOR (재귀 WITH도 지원)", "sqlserver": "재귀 CTE (WITH … UNION ALL)",
     "note": ""},
    {"id": "dl_ctas", "topic": "SELECT 결과로 테이블 생성",
     "concepts": ["CTAS", "SELECT INTO", "PK 제약 비상속"],
     "ansi": "CREATE TABLE … AS (SELECT …)", "oracle": "CREATE TABLE t AS SELECT … (NOT NULL만 복사)", "sqlserver": "SELECT … INTO t FROM …",
     "note": ""},
    {"id": "dl_alter_column", "topic": "컬럼 변경·이름 변경",
     "concepts": ["MODIFY", "ALTER COLUMN", "ALTER/MODIFY", "RENAME", "RENAME COLUMN", "Oracle/SQL Server DDL 차이"],
     "ansi": "ALTER TABLE … ALTER COLUMN", "oracle": "ALTER TABLE t MODIFY (c 타입); RENAME a TO b; ALTER TABLE t RENAME COLUMN a TO b",
     "sqlserver": "ALTER TABLE t ALTER COLUMN c 타입; EXEC sp_rename",
     "note": ""},
    {"id": "dl_identity", "topic": "자동 증가 값",
     "concepts": ["IDENTITY", "대리키"],
     "ansi": "GENERATED … AS IDENTITY", "oracle": "SEQUENCE, 12c+ GENERATED AS IDENTITY", "sqlserver": "IDENTITY(시작, 증가), SEQUENCE(2012+)",
     "note": ""},
    {"id": "dl_drop_cascade", "topic": "참조되는 테이블 삭제",
     "concepts": ["CASCADE CONSTRAINTS", "DROP CASCADE", "DROP", "DROP 의존성"],
     "ansi": "DROP TABLE t CASCADE | RESTRICT", "oracle": "DROP TABLE t CASCADE CONSTRAINTS", "sqlserver": "참조하는 FK를 먼저 삭제해야 함",
     "note": ""},
    {"id": "dl_alias", "topic": "테이블 별칭 AS",
     "concepts": ["테이블 별칭", "ALIAS"],
     "ansi": "FROM t AS a", "oracle": "FROM t a (AS 사용 불가)", "sqlserver": "FROM t AS a 또는 FROM t a",
     "note": "컬럼 별칭의 AS는 양쪽 모두 사용 가능."},
    {"id": "dl_grant", "topic": "권한 회수 연쇄",
     "concepts": ["REVOKE", "권한 연쇄 회수", "REVOKE RESTRICT", "GRANT OPTION"],
     "ansi": "REVOKE … CASCADE | RESTRICT", "oracle": "WITH GRANT OPTION 객체 권한은 자동 연쇄 회수", "sqlserver": "재부여가 있으면 REVOKE … CASCADE 필요",
     "note": ""},
]
